### ISSUE TITLE
Sometimes the device mapper is stuck in an infinite “mount/remount” loop

### ISSUE THREAD

**Issue by foretspaisibles** [moby/moby#20401]
When this happens, the system is very unresponsive, a simple _docker ps_ can last for about 1 minute, and containers need even more time to be started, if they start at all. Application logs and docker logs do not display any error, the only low-level curious activity is found in the system logs:

```
Feb  6 23:58:04 ip-172-16-4-30 kernel: [723943.329608] XFS (dm-26): Unmounting Filesystem
Feb  6 23:58:24 ip-172-16-4-30 kernel: [723963.978634] XFS (dm-26): Mounting V4 Filesystem
Feb  6 23:59:22 ip-172-16-4-30 kernel: [724021.561906] XFS (dm-26): Ending clean mount
Feb  6 23:59:22 ip-172-16-4-30 kernel: [724021.564932] XFS (dm-267): Unmounting Filesystem
Feb  6 23:59:42 ip-172-16-4-30 kernel: [724041.461206] XFS (dm-111): Mounting V4 Filesystem
Feb  7 00:00:42 ip-172-16-4-30 kernel: [724101.702141] XFS (dm-111): Ending clean mount
```

This is a not so rare condition, it affects about 3% of the systems deployed. There is about one iteration each second. It can last over 1 day and there is no obvious way to resolve it, aside ditching the systems and ordering brand new ones. (Service restart, reboot, or docker library removal will not salvage the system.)

```
$ docker info
Containers: 3
Images: 17
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-264750-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 795.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 27.62 GB
 Metadata Space Used: 2.032 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-15.23.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 3.862 GiB
Name: ip-172-16-1-241
ID: MKMR:UVOD:VZ5M:AZWU:5CH7:YXWZ:UOI3:FY4R:YBZA:3MU4:AFG7:CH7U
Username: quintlyworker
Registry: https://index.docker.io/v1/
```

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64
```

```
$ uname -a
Linux ip-172-16-1-241 4.1.7-15.23.amzn1.x86_64 #1 SMP Mon Sep 14 23:20:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Is this related to #20400?

**Comment by michipili** [comment]
These are independent issued observed on distinct systems.

**Comment by cpuguy83** [comment]
Thanks for adding the additional info.

Can you enable debug mode on the daemon and paste the daemon logs?
Or even we can start with just the daemon logs as is.

**Comment by michipili** [comment]
We replaced all affected systems but still would like to understand or help fixing the issue. I will follow up with the details you ask as soon as possible.

**Comment by joaocc** [comment]
Hi.
I have also this problem on freshly installed ubuntu 14.04.3-LTS on Azure.

The following packages are installed
- btrfs-tools
- xfsprogs
- lvm2
- lxc-docker

**uname -a**
```
Linux nn02 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**/var/log/apt/history.log**
```

Start-Date: 2016-02-01  22:22:35
Commandline: apt-get -y install walinuxagent cifs-utils unscd linux-hwe-virtual-trusty linux-image-virtual-lts-vivid linux-lts-vivid-cloud-tools-common cloud-init
Install: walinuxagent:amd64 (2.0.14-0ubuntu1~14.04.1), linux-lts-vivid-cloud-tools-common:amd64 (3.19.0-18.18~14.04.1), libnl-genl-3-200:amd64 (3.2.21-1, automatic), python-crypto:amd64 (2.6.1-4build1, automatic), python-samba:amd64 (4.1.6+dfsg-1ubuntu2.14.04.11, automatic), iw:amd64 (3.4-1, automatic), linux-image-3.19.0-49-generic:amd64 (3.19.0-49.55~14.04.1, automatic), wireless-regdb:amd64 (2013.02.13-1ubuntu1, automatic), linux-image-extra-virtual:amd64 (3.13.0.77.83, automatic), libcups2:amd64 (1.7.2-0ubuntu1.7, automatic), linux-image-virtual-lts-utopic:amd64 (3.16.0.60.51, automatic), libntdb1:amd64 (1.0-2ubuntu1, automatic), linux-headers-3.16.0-60:amd64 (3.16.0-60.80~14.04.1, automatic), python-tdb:amd64 (1.2.12-1, automatic), libtevent0:amd64 (0.9.19-1, automatic), linux-image-extra-3.13.0-77-generic:amd64 (3.13.0-77.121, automatic), libnl-3-200:amd64 (3.2.21-1, automatic), linux-hwe-virtual-trusty:amd64 (3.13.0.77.83), samba-common-bin:amd64 (4.1.6+dfsg-1ubuntu2.14.04.11, automatic), libldb1:amd64 (1.1.16-1ubuntu0.1, automatic), libavahi-common-data:amd64 (0.6.31-4ubuntu1, automatic), libavahi-client3:amd64 (0.6.31-4ubuntu1, automatic), libtdb1:amd64 (1.2.12-1, automatic), libgmp10:amd64 (5.1.3+dfsg-1ubuntu1, automatic), linux-image-virtual-lts-vivid:amd64 (3.19.0.49.34), samba-libs:amd64 (4.1.6+dfsg-1ubuntu2.14.04.11, automatic), keyutils:amd64 (1.5.6-1, automatic), libavahi-common3:amd64 (0.6.31-4ubuntu1, automatic), libtalloc2:amd64 (2.1.0-1, automatic), crda:amd64 (1.1.2-1ubuntu2, automatic), linux-image-3.16.0-60-generic:amd64 (3.16.0-60.80~14.04.1, automatic), linux-firmware:amd64 (1.127.20, automatic), cifs-utils:amd64 (6.0-1ubuntu2), python-talloc:amd64 (2.1.0-1, automatic), libwbclient0:amd64 (4.1.6+dfsg-1ubuntu2.14.04.11, automatic), linux-image-hwe-virtual-trusty:amd64 (3.13.0.77.83, automatic), python-ldb:amd64 (1.1.16-1ubuntu0.1, automatic), samba-common:amd64 (4.1.6+dfsg-1ubuntu2.14.04.11, automatic), linux-headers-3.16.0-60-generic:amd64 (3.16.0-60.80~14.04.1, automatic), linux-headers-virtual-lts-utopic:amd64 (3.16.0.60.51, automatic), python-ntdb:amd64 (1.0-2ubuntu1, automatic), linux-headers-generic-lts-utopic:amd64 (3.16.0.60.51, automatic), linux-image-generic:amd64 (3.13.0.77.83, automatic), unscd:amd64 (0.51-1build2)
End-Date: 2016-02-01  22:28:15

Start-Date: 2016-02-01  22:28:18
Commandline: apt-get -y purge linux-image-virtual linux-.*3.13.*
Purge: linux-headers-generic:amd64 (3.13.0.77.83), linux-image-extra-virtual:amd64 (3.13.0.77.83), linux-image-virtual:amd64 (3.13.0.77.83), linux-virtual:amd64 (3.13.0.77.83), linux-image-extra-3.13.0-77-generic:amd64 (3.13.0-77.121), linux-headers-virtual:amd64 (3.13.0.77.83), linux-image-3.13.0-77-generic:amd64 (3.13.0-77.121), linux-headers-3.13.0-77:amd64 (3.13.0-77.121), linux-headers-3.13.0-77-generic:amd64 (3.13.0-77.121), linux-image-generic:amd64 (3.13.0.77.83)
End-Date: 2016-02-01  22:28:35

Start-Date: 2016-02-01  22:28:36
Commandline: apt-get -y autoremove
Remove: libnl-genl-3-200:amd64 (3.2.21-1), iw:amd64 (3.4-1), wireless-regdb:amd64 (2013.02.13-1ubuntu1), libnl-3-200:amd64 (3.2.21-1), crda:amd64 (1.1.2-1ubuntu2)
End-Date: 2016-02-01  22:28:41

Start-Date: 2016-02-17  19:08:22
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install btrfs-tools xfsprogs lvm2
Install: lvm2:amd64 (2.02.98-6ubuntu2), libreadline5:amd64 (5.2+dfsg-2, automatic), watershed:amd64 (7, automatic), liblzo2-2:amd64 (2.06-1.2ubuntu1.1, automatic), xfsprogs:amd64 (3.1.9ubuntu2), libdevmapper-event1.02.1:amd64 (1.02.77-6ubuntu2, automatic), btrfs-tools:amd64 (3.12-1ubuntu0.1)
End-Date: 2016-02-17  19:08:58

Start-Date: 2016-02-17  19:10:09
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install lxc-docker
Install: lxc-docker:amd64 (1.9.1), aufs-tools:amd64 (3.2+20130722-1.1, automatic), lxc-docker-1.9.1:amd64 (1.9.1, automatic), liberror-perl:amd64 (0.17-1.1, automatic), cgroup-lite:amd64 (1.9, automatic), git-man:amd64 (1.9.1-1ubuntu0.2, automatic), git:amd64 (1.9.1-1ubuntu0.2, automatic)
End-Date: 2016-02-17  19:10:31

```

**Comment by cpuguy83** [comment]
logs from the docker daemon would be helpful.

**Comment by joaocc** [comment]
Sure. Where can I find them?

**Comment by joaocc** [comment]
Seems to be here **/var/log/upstart/docker.log**.
Attaching

[docker-logs.zip](https://github.com/docker/docker/files/135353/docker-logs.zip)

**Comment by joaocc** [comment]
adding logs from a different VM where the message is slightly different.
[docker-logs-xfs.zip](https://github.com/docker/docker/files/135356/docker-logs-xfs.zip)

**Comment by HackToday** [comment]
hi @joaocc  I am not sure how do you install docker.
according to 
https://docs.docker.com/engine/installation/linux/ubuntulinux/

It seems lxc-docker is not suggested to install, but you given info said lxc-docker installed

**Comment by joaocc** [comment]
Hi.
You are right. I have since replaced lxc-docker with docker-engine. The problem still holds.
I can refresh the logs if you need to
Thx

**Comment by HackToday** [comment]
Then @joaocc  Please provide 
1. how do you install the docker? What configuration did you do ?

2. Append docker logs with debug level enabled.


Thanks

**Comment by joaocc** [comment]
Docker install steps (via tf and ansible, but simplified below)
- ubuntu 14.04.3-LTS
- install 
      - btrfs-tools
      - xfsprogs
      - lvm2
      - apt-transport-https
      - ca-certificates
- repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
- repo key: 58118E89F3A912897C070ADBF76221572C52609D
- apt-get purge lxc-docker
- apt-get install docker-engine
- add user to group docker and create if not exist
- start docker

The docker logs are already attached before.

**Comment by joaocc** [comment]
All the 4 machines I had before stopped exhibiting this problem.
Based on my observations, I think this has probably been fixed in 1.10.

**Comment by thaJeztah** [comment]
Should we close this issue if there's no system left to reproduce?

**Comment by joaocc** [comment]
I would agree.

**Comment by michipili** [comment]
We have a new case, details follow ASAP.

**Comment by michipili** [comment]
Here are the logs of the latest restart, using `--debug=true`.  My comments follow in a separate entry.

[docker.txt](https://github.com/docker/docker/files/140381/docker.txt)

**Comment by michipili** [comment]
The logs were prepared on an already affected system, restarting the docker daemon with the `--debug=true` flag. Part of the observable activity might be ascribed to the broken state the daemon is in, even after restarting, but there is no detailed log available for the precise time when the trouble started.

Problems seems to start two days ago, as our ecs-agent (piece of software responsible for creating containers) repeatedly tries to instantiate new containers, at a rate of 10 in an hour.  All these containers are listed in the output of `docker ps -a` with the status `Created` – not `Exited(?)` .

**Comment by michipili** [comment]
The inspection of the oldest of these containers gives

```
# docker inspect 0da4cb2cb36f
[
{
    "Id": "0da4cb2cb36fc35e74fe75dd82525b78c9c42801d582426ad66a8f8fc7117172",
    "Created": "2016-02-19T13:39:49.762851757Z",
    "Path": "/bin/sh",
    "Args": [
        "-c",
        "PLOP-PLOP FIZZ-FIZZ"
    ],
    "State": {
        "Status": "created",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "fbcbd36743c13400a88bdf515650a290115d801c2bf720c7a734d9c7217ba714",
    "ResolvConfPath": "",
    "HostnamePath": "",
    "HostsPath": "",
    "LogPath": "",
    "Name": "/ecs-PLOP-PLOP-FIZZ-FIZZ-989c98fdd7bcea9a7600",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/worker-logs:/quintly/logs"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 524288000,
        "MemoryReservation": 0,
        "MemorySwap": 1048576000,
        "KernelMemory": 0,
        "CpuShares": 256,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": null,
        "Links": null,
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "194",
            "DeviceName": "docker-202:1-263198-0da4cb2cb36fc35e74fe75dd82525b78c9c42801d582426ad66a8f8fc7117172",
            "DeviceSize": "107374182400"
        }
    },
    "Mounts": [
        {
            "Source": "/worker-logs",
            "Destination": "/quintly/logs",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "0da4cb2cb36f",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "PLOP-PLOP FIZZ-FIZZ"
        ],
        "Image": "PLOP-PLOP-FIZZ-FIZZ",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": null
    }
}
]
```

I stripped away the actual command used and labels used internally by the ecs-agent. The ids given can be tracked in the logs.

**Comment by michipili** [comment]
These are the logs (without debugging information available) around `2016-02-19T13:39:49.762851757Z` the creation time of the first container that has been `Created` but not `Started`.

```
time="2016-02-19T13:39:40.487292428Z" level=info msg="GET /v1.21/containers/070218d69143/json" 
time="2016-02-19T13:39:48.642697524Z" level=info msg="POST /v1.17/images/create?fromImage=quintly%2FXXXXXXXXXX" 
time="2016-02-19T13:39:49.746898919Z" level=info msg="POST /v1.17/containers/create?name=ecs-XXXXXXXXXr-989c98fdd7bcea9a7600" 
time="2016-02-19T13:40:40.346575909Z" level=info msg="GET /v1.21/containers/json?all=1" 
time="2016-02-19T13:40:40.520502438Z" level=info msg="GET /v1.21/containers/0da4cb2cb36f/json" 
time="2016-02-19T13:41:16.264203431Z" level=error msg="Handler for GET /v1.21/containers/0da4cb2cb36f/json returned error: Unknown device 0da4cb2cb36fc35e74fe75dd82525b78c9c42801d582426ad66a8f8fc7117172" 
time="2016-02-19T13:41:16.264265246Z" level=error msg="HTTP Error" err="Unknown device 0da4cb2cb36fc35e74fe75dd82525b78c9c42801d582426ad66a8f8fc7117172" statusCode=500 
time="2016-02-19T13:41:16.264576864Z" level=info msg="GET /v1.21/images/0da4cb2cb36f/json" 
time="2016-02-19T13:41:16.264746648Z" level=error msg="Handler for GET /v1.21/images/0da4cb2cb36f/json returned error: No such image: 0da4cb2cb36f" 
time="2016-02-19T13:41:16.264768118Z" level=error msg="HTTP Error" err="No such image: 0da4cb2cb36f" statusCode=404 
time="2016-02-19T13:41:16.265048168Z" level=info msg="GET /v1.21/containers/b1d78171ab85/json" 
```

**Comment by michipili** [comment]
Last, the system messages around the creation time of that container:

```
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.736770] veth4f194fd: renamed from eth0
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.748370] docker0: port 3(veth964f6d6) entered disabled state
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.763765] docker0: port 3(veth964f6d6) entered disabled state
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.768117] device veth964f6d6 left promiscuous mode
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.771708] docker0: port 3(veth964f6d6) entered disabled state
Feb 19 13:34:57 ip-172-16-2-242 kernel: [276447.805528] XFS (dm-5): Unmounting Filesystem
Feb 19 13:35:59 ip-172-16-2-242 kernel: [276509.332854] veth0ed8d9d: renamed from eth0
Feb 19 13:35:59 ip-172-16-2-242 kernel: [276509.336151] docker0: port 2(vetha15180c) entered disabled state
Feb 19 13:35:59 ip-172-16-2-242 kernel: [276509.363782] docker0: port 2(vetha15180c) entered disabled state
Feb 19 13:35:59 ip-172-16-2-242 kernel: [276509.368134] device vetha15180c left promiscuous mode
Feb 19 13:35:59 ip-172-16-2-242 kernel: [276509.372111] docker0: port 2(vetha15180c) entered disabled state
Feb 19 13:36:05 ip-172-16-2-242 kernel: [276515.970156] XFS (dm-5): Mounting V4 Filesystem
Feb 19 13:36:59 ip-172-16-2-242 kernel: [276569.315272] XFS (dm-5): Ending clean mount
Feb 19 13:36:59 ip-172-16-2-242 kernel: [276569.323694] XFS (dm-6): Unmounting Filesystem
Feb 19 13:37:04 ip-172-16-2-242 kernel: [276574.869042] XFS (dm-5): Unmounting Filesystem
Feb 19 13:37:26 ip-172-16-2-242 kernel: [276596.945112] XFS (dm-5): Mounting V4 Filesystem
Feb 19 13:38:20 ip-172-16-2-242 kernel: [276650.248112] XFS (dm-5): Ending clean mount
Feb 19 13:38:20 ip-172-16-2-242 kernel: [276650.718126] XFS (dm-5): Unmounting Filesystem
Feb 19 13:38:40 ip-172-16-2-242 kernel: [276670.326992] XFS (dm-5): Mounting V4 Filesystem
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.365458] XFS (dm-5): Ending clean mount
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.381059] device veth573b76f entered promiscuous mode
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.399653] IPv6: ADDRCONF(NETDEV_UP): veth573b76f: link is not ready
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.509029] eth0: renamed from veth088dd19
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.512745] IPv6: ADDRCONF(NETDEV_CHANGE): veth573b76f: link becomes ready
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.517661] docker0: port 2(veth573b76f) entered forwarding state
Feb 19 13:39:32 ip-172-16-2-242 kernel: [276722.536733] docker0: port 2(veth573b76f) entered forwarding state
Feb 19 13:39:33 ip-172-16-2-242 kernel: [276723.400804] veth0ef82b5: renamed from eth0
Feb 19 13:39:33 ip-172-16-2-242 kernel: [276723.406119] docker0: port 5(veth74c5a58) entered disabled state
Feb 19 13:39:33 ip-172-16-2-242 kernel: [276723.439228] docker0: port 5(veth74c5a58) entered disabled state
Feb 19 13:39:33 ip-172-16-2-242 kernel: [276723.444928] device veth74c5a58 left promiscuous mode
Feb 19 13:39:33 ip-172-16-2-242 kernel: [276723.448205] docker0: port 5(veth74c5a58) entered disabled state
Feb 19 13:39:35 ip-172-16-2-242 kernel: [276725.253845] XFS (dm-4): Unmounting Filesystem
Feb 19 13:39:36 ip-172-16-2-242 kernel: [276726.241647] device-mapper: ioctl: remove_all left 6 open device(s)
Feb 19 13:39:47 ip-172-16-2-242 kernel: [276737.568101] docker0: port 2(veth573b76f) entered forwarding state
```

**Comment by joaocc** [comment]
@michipili: Did you install docker from [here](https://docs.docker.com/engine/installation/linux/ubuntulinux/) In the logs you posted it looks like you are using docker 1.9.x, whereas the latest version in the link above will get you 1.10.x. In my case, moving to 1.10 solved the issue.

**Comment by michipili** [comment]
@joaocc Thank you for your input, unfortunately this is not yet an option for us.

We now have several systems gathering extra debugging informations, given the rate at which the problem show up on these, it is likely that we can provide this information within one week or so.

On some systems (not gathering  extra debugging information) we see that some docker containers never leave the state `Created`. I guess, the state `Created` is entered when the file-system for the container has been prepared and that the state should move to `Starting` right after that. But somehow this does not happen.

An additional interesting phenomenon on the affected systems is that `top` report a really heavy workload but none of the processes running on the system seem directly responsible for this. This usually hints towards a heavy kernel activity – which would likely correspond to the mounting-unmounting loop reported in my original description of the problem.

Is it possible that some system resource used by the devicemapper system is totally consumed and not reclaimed early enough, so that the system ends in this apparent deadlock? The question is prompted by these options we are using:

```
--storage-driver devicemapper
--storage-opt dm.fs=xfs
--storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool
--storage-opt dm.use_deferred_removal=true
--storage-opt dm.use_deferred_deletion=true
```

**Comment by michipili** [comment]
As expected, a problem soon showed up on an instance where debugging is enabled. I will prepare logs to post here. @thaJeztah What would be useful to see here besides system messages and docker daemon logs?

**Comment by thaJeztah** [comment]
@michipili those two sound good, but possibly @cpuguy83 or @rhvgoyal have additional suggestions for useful information to add

**Comment by michipili** [comment]
So, I would have liked to provide output of `docker inspect` for all containers on the machine but `docker ps` did not respond after more than one hour (!).  First, let's take a look at top:

```
top - 09:41:34 up 1 day, 23:55,  2 users,  load average: 2.48, 2.27, 2.13
Tasks: 1331 total,   1 running, 1330 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.3%us,  0.7%sy,  0.0%ni,  0.0%id, 98.7%wa,  0.0%hi,  0.0%si,  0.3%st
Mem:   2051636k total,  1951940k used,    99696k free,   134560k buffers
Swap:        0k total,        0k used,        0k free,   691432k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND           
11303 root      20   0     0    0    0 S  0.3  0.0   0:00.88 kworker/u30:2      
12316 root      28   8  441m  37m 7556 S  0.3  1.9   7:20.56 aws                
30367 root      20   0 37784  32m 7612 S  0.3  1.6  13:00.51 agent              
    1 root      20   0 19512 2480 2184 S  0.0  0.1   0:00.70 init               
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.06 kthreadd           
    3 root      20   0     0    0    0 S  0.0  0.0   0:23.00 ksoftirqd/0 
```

As you see the load average (2.41) is rather high (I saw peeks at 3.15) while no process seems to cause this activity, which is a sign than this activity takes place in the kernel. While investigating the system, my SSH connection dropped (SIGPIPE) which of course can have a variety of causes but could be a further symptom than some system resource is short.

This is the last segment of very strange activity

```
[  +0.467019] XFS (dm-4): Unmounting Filesystem
[ +20.139963] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:17] XFS (dm-4): Ending clean mount
[ +18.886583] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:18] XFS (dm-6): Ending clean mount
[  +0.002568] XFS (dm-4): Unmounting Filesystem
[Apr 7 17:19] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:20] XFS (dm-4): Ending clean mount
[  +0.379894] XFS (dm-4): Unmounting Filesystem
[ +19.722320] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:21] XFS (dm-4): Ending clean mount
[ +19.441943] XFS (dm-8): Mounting V4 Filesystem
[Apr 7 17:22] XFS (dm-8): Ending clean mount
[  +0.003967] XFS (dm-6): Unmounting Filesystem
[ +19.935995] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:23] XFS (dm-6): Ending clean mount
[  +0.157200] XFS (dm-6): Unmounting Filesystem
[  +1.949623] XFS (dm-4): Unmounting Filesystem
[Apr 7 17:24] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:25] XFS (dm-4): Ending clean mount
[  +0.548252] XFS (dm-4): Unmounting Filesystem
[  +1.303811] XFS (dm-8): Unmounting Filesystem
[  +0.004251] veth64ca5be: renamed from eth0
[  +0.002877] docker0: port 3(vethd4c3f56) entered disabled state
[  +0.027881] docker0: port 3(vethd4c3f56) entered disabled state
[  +0.007145] device vethd4c3f56 left promiscuous mode
[  +0.005787] docker0: port 3(vethd4c3f56) entered disabled state
[ +17.959230] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:26] XFS (dm-4): Ending clean mount
[  +0.497421] XFS (dm-4): Unmounting Filesystem
[ +19.412757] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:27] XFS (dm-4): Ending clean mount
[ +17.735705] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:28] XFS (dm-6): Ending clean mount
[Apr 7 17:29] XFS (dm-8): Mounting V4 Filesystem
[Apr 7 17:30] XFS (dm-8): Ending clean mount
[  +0.008627] XFS (dm-5): Unmounting Filesystem
[ +19.657035] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:31] XFS (dm-5): Ending clean mount
[ +17.320923] XFS (dm-9): Mounting V4 Filesystem
[Apr 7 17:32] XFS (dm-9): Ending clean mount
[  +0.002930] XFS (dm-6): Unmounting Filesystem
[ +19.607763] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:33] XFS (dm-6): Ending clean mount
[  +0.219859] XFS (dm-6): Unmounting Filesystem
[Apr 7 17:34] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:35] XFS (dm-6): Ending clean mount
[ +16.683462] XFS (dm-10): Mounting V4 Filesystem
[Apr 7 17:36] XFS (dm-10): Ending clean mount
[  +0.003253] XFS (dm-5): Unmounting Filesystem
[ +16.864628] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:37] XFS (dm-5): Ending clean mount
[  +0.200108] XFS (dm-5): Unmounting Filesystem
[  +1.788298] XFS (dm-9): Unmounting Filesystem
[ +19.211344] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:38] XFS (dm-5): Ending clean mount
[  +0.449888] XFS (dm-5): Unmounting Filesystem
[  +2.113912] XFS (dm-4): Unmounting Filesystem
[Apr 7 17:39] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:40] XFS (dm-4): Ending clean mount
[  +0.283606] XFS (dm-4): Unmounting Filesystem
[  +1.851654] XFS (dm-6): Unmounting Filesystem
[ +18.579646] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:41] XFS (dm-4): Ending clean mount
[  +0.279984] XFS (dm-4): Unmounting Filesystem
[ +19.185764] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:42] XFS (dm-4): Ending clean mount
[Apr 7 17:43] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:44] XFS (dm-5): Ending clean mount
[  +0.005070] XFS (dm-8): Unmounting Filesystem
[ +18.203188] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:45] XFS (dm-6): Ending clean mount
[  +0.833799] XFS (dm-6): Unmounting Filesystem
[ +21.465551] XFS (dm-6): Mounting V4 Filesystem
[Apr 7 17:46] XFS (dm-6): Ending clean mount
[  +0.007852] XFS (dm-10): Unmounting Filesystem
[ +19.628602] XFS (dm-8): Mounting V4 Filesystem
[Apr 7 17:47] XFS (dm-8): Ending clean mount
[  +0.091196] XFS (dm-8): Unmounting Filesystem
[Apr 7 17:48] XFS (dm-8): Mounting V4 Filesystem
[Apr 7 17:49] XFS (dm-8): Ending clean mount
[ +16.641921] XFS (dm-9): Mounting V4 Filesystem
[Apr 7 17:50] XFS (dm-9): Ending clean mount
[ +19.338014] XFS (dm-10): Mounting V4 Filesystem
[Apr 7 17:51] XFS (dm-10): Ending clean mount
[  +0.003331] XFS (dm-5): Unmounting Filesystem
[ +19.264335] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:52] XFS (dm-5): Ending clean mount
[  +0.329826] XFS (dm-5): Unmounting Filesystem
[Apr 7 17:53] XFS (dm-5): Mounting V4 Filesystem
[Apr 7 17:54] XFS (dm-5): Ending clean mount
[ +20.266164] XFS (dm-11): Mounting V4 Filesystem
[Apr 7 17:55] XFS (dm-11): Ending clean mount
[ +17.799925] XFS (dm-12): Mounting V4 Filesystem
[Apr 7 17:56] XFS (dm-12): Ending clean mount
[  +0.004854] XFS (dm-4): Unmounting Filesystem
[ +17.559186] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:57] XFS (dm-4): Ending clean mount
[  +0.419773] XFS (dm-4): Unmounting Filesystem
[Apr 7 17:58] XFS (dm-4): Mounting V4 Filesystem
[Apr 7 17:59] XFS (dm-4): Ending clean mount
[ +17.538426] XFS (dm-13): Mounting V4 Filesystem
[Apr 7 18:00] XFS (dm-13): Ending clean mount
[ +18.712564] XFS (dm-14): Mounting V4 Filesystem
[Apr 7 18:01] XFS (dm-14): Ending clean mount
[  +0.002531] XFS (dm-10): Unmounting Filesystem
[Apr 7 18:02] XFS (dm-10): Mounting V4 Filesystem
[ +59.047333] XFS (dm-10): Ending clean mount
[Apr 7 18:03] XFS (dm-10): Unmounting Filesystem
[ +19.334478] XFS (dm-10): Mounting V4 Filesystem
```

after about 1200 similar messages comes the message

```
[Apr 8 02:19] XFS (dm-35): Mounting V4 Filesystem
[ +52.041289] XFS (dm-35): Ending clean mount
[Apr 8 02:20] device-mapper: thin: Data device (dm-1) discard unsupported: Disabling discard passdown.
[  +0.006215] device-mapper: thin: 253:2: growing the data device from 18000 to 21600 blocks
[  +4.714625] XFS (dm-92): Mounting V4 Filesystem
[Apr 8 02:21] XFS (dm-92): Ending clean mount
```
Then come about 1000 similar lines with the ending clean-mount, unmounting filesystem mounting, v4 filesystem, trilogy, occasionally peppered by messages of the device-mapper as above. As you see, the mounting operation can take as much as 55 seconds!

Skimming through the logs at that time is tedious, because of the huge level of information available here:

```
% awk '/2016-04-07T17/,/2016-04-07T17/ {c[$2]+=1} END {for(i in c){print(i, c[i]);}}' docker-obliterated.log 
level=info 148
level=debug 12703
level=error 28
```

All the errors look like this

```
% awk '/2016-04-07T17/,/2016-04-07T17/ { if($2 == "level=error") { print } }' docker-obliterated.log      
time="2016-04-07T17:02:50.621660570Z" level=error msg="Handler for GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json returned error: no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" 
time="2016-04-07T17:02:50.621694542Z" level=error msg="HTTP Error" err="no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" statusCode=404 
…
```

and the complete docker logs around the first error mentioned above are

```
% grep -F 'time="2016-04-07T17:02:50.621660570Z"' -C 10 docker-obliterated.log
time="2016-04-07T17:02:49.108050685Z" level=debug msg="[devmapper] deactivateDevice END(a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619)" 
time="2016-04-07T17:02:49.791019449Z" level=debug msg="unregisterDevice(87, a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619)" 
time="2016-04-07T17:02:49.991149057Z" level=debug msg="devmapper: DeleteDevice(hash=a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619 syncDelete=false) END" 
time="2016-04-07T17:02:49.991260464Z" level=debug msg="devmapper: DeleteDevice(hash=a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619-init syncDelete=false) START" 
time="2016-04-07T17:02:49.991278921Z" level=debug msg="[devmapper] deactivateDevice(a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619-init)" 
time="2016-04-07T17:02:49.991328694Z" level=debug msg="[devmapper] deactivateDevice END(a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619-init)" 
time="2016-04-07T17:02:50.481024707Z" level=debug msg="unregisterDevice(86, a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619-init)" 
time="2016-04-07T17:02:50.617337446Z" level=debug msg="devmapper: DeleteDevice(hash=a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619-init syncDelete=false) END" 
time="2016-04-07T17:02:50.621477347Z" level=debug msg="Calling GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json" 
time="2016-04-07T17:02:50.621503613Z" level=info msg="GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json" 
time="2016-04-07T17:02:50.621660570Z" level=error msg="Handler for GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json returned error: no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" 
time="2016-04-07T17:02:50.621694542Z" level=error msg="HTTP Error" err="no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" statusCode=404 
time="2016-04-07T17:02:50.623246522Z" level=debug msg="Calling GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json" 
time="2016-04-07T17:02:50.623268575Z" level=info msg="GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json" 
time="2016-04-07T17:02:50.623353372Z" level=error msg="Handler for GET /v1.17/containers/a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619/json returned error: no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" 
time="2016-04-07T17:02:50.623374429Z" level=error msg="HTTP Error" err="no such id: a0614fd0be0d8e203dde77ab4a26e95d4cb6785e4b1ca067983052da17299619" statusCode=404 
time="2016-04-07T17:02:51.382312402Z" level=debug msg="Calling DELETE /v1.17/containers/72408de76334937793373d65746f5839130bf6bd58704b78f1b683816b9c6c20" 
time="2016-04-07T17:02:51.382362215Z" level=info msg="DELETE /v1.17/containers/72408de76334937793373d65746f5839130bf6bd58704b78f1b683816b9c6c20?v=1" 
time="2016-04-07T17:02:51.397667596Z" level=debug msg="devmapper: DeleteDevice(hash=72408de76334937793373d65746f5839130bf6bd58704b78f1b683816b9c6c20 syncDelete=false) START" 
time="2016-04-07T17:02:51.397690393Z" level=debug msg="[devmapper] deactivateDevice(72408de76334937793373d65746f5839130bf6bd58704b78f1b683816b9c6c20)" 
time="2016-04-07T17:02:51.397739315Z" level=debug msg="[devmapper] deactivateDevice END(72408de76334937793373d65746f5839130bf6bd58704b78f1b683816b9c6c20)" 
```

On the system, two services interact with docker: an ecs-agent (AWS) and a custom monitoring program polling `docker ps` and `docker inspect` for the given containers at a regular interval (5 minutes IIRC).

[messages.log.gz](https://github.com/docker/docker/files/209974/messages.log.gz)
[docker-obliterated.log.gz](https://github.com/docker/docker/files/209976/docker-obliterated.log.gz)

For obvious reasons, I obliterated `Cmd` and `Env` fields from the docker logs with the following sed script:

```
s/\\"Env\\":\[[^]]*\]/\\"Env\\":["XXX=XXX"]/g
s/\\"Cmd\\":\[[^]]*\]/\\"Cmd\\":["XXX"]/g
```

If some of this information could be relevant, please let me know.

**Comment by anosulchik** [comment]
I'd like to report that the problem described here exists in docker 1.11.1. Please see details below.

We noticed that sometimes docker fails to unmount/delete devicemapper volumes and freezes whole system. `dmsetup ls` command shows hundreds of unmounted volumes while there're a few containers running. Looks like it's related to `dm.use_deferred_deletion` and/or `dm.use_deferred_removal` options for devicemapper.

**Storage options**:
```
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true --storage-opt dm.fs=ext4"
```

**Docker info**: 
```
[root@es-staging2-node0 ~]# docker info
Containers: 37
 Running: 1
 Paused: 0
 Stopped: 36
Images: 10
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 1.988 GB
 Data Space Total: 67.96 GB
 Data Space Available: 65.97 GB
 Metadata Space Used: 3.092 MB
 Metadata Space Total: 71.3 MB
 Metadata Space Available: 68.21 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.10-22.54.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: es-staging2-node0
ID: 6E7W:RYPN:JZML:JD7L:LYM5:YTEK:ZM52:5J7R:XRBX:OXCG:KYJN:WZV7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

***Symptoms***: docker commands like "docker ps" or "docker info" hangs forever, "top" shows high iowait time produced by docker and kernel (e.g. about 99%). As soon as docker service is stopped iowait returns to normal. Docker restart doesn't help -- once it started system is frozen again.

**Errors in docker logs**:
```
time="2016-07-08T04:04:46.150154271Z" level=error msg="devmapper: Error unmounting device bf69649cf4a86fac5e2116fc840f207f514b40f6a81f36a522cca13b66c04a76: invalid argument"
time="2016-07-08T04:04:46.150205172Z" level=error msg="Error unmounting container bf2dbc65609755453fd8039598d1df79881772f161f3c24aad989ee359261f1a: invalid argument"
```

```
time="2016-07-08T04:05:52.686392425Z" level=error msg="Driver devicemapper couldn't return diff size of container 47516e77d87ec23f4b7d2675beb91d1ca2cc369553bdcc457b0862c58b92552f: open /dev/mapper/docker-202:1-263217-87434c081209301d11cb7fcfb92f518beb436f4881e66c2e8bec45d86118ab7d: no such file or directory"
```

```
2016/07/08 04:15:17 http: multiple response.WriteHeader calls
time="2016-07-08T04:15:17.848510748Z" level=error msg="Handler for GET /v1.23/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
2016/07/08 04:15:17 http: multiple response.WriteHeader calls
```

**Steps to reproduce**: start/stop list of containers multiple times until system becomes frozen. Usually it happens after a few hours of stopping/starting containers. At the same time it may happen arbitrary during normal work when there's no flapping containers. In case use_deferred_removal and use_deferred_deletion device mapper options are set to false system freezes almost instantly -- within minutes.

**Comment by cpuguy83** [comment]
Thanks @anosulchik, this is unrelated and already resolved in 1.11.2!

**Comment by anosulchik** [comment]
@cpuguy83 Just to confirm that the problem is still present in 1.11.2, please see my comment https://github.com/docker/docker/issues/24446#issuecomment-232003769 Please let me know if you need any debugging info from me - I can reproduce the problem in a few hours.

**Comment by rhvgoyal** [comment]
@anosulchik If you are seeing lots of active devices,  I suspect that mount point of these devices have leaked into other mount namespaces and that's why they are still active. Try doing "dmsetup info" on those devices and see if deferred removal has been scheduled. If yes, that means devices are waiting for last mount point to go away, so that devices become free and can be removed.

**Comment by rhvgoyal** [comment]
Are you running docker daemon in host mount namespace or in a separate mount namespace of its own. If you run docker daemon in a separate mount namespace of its own, there is less likelihood of mount points leaking.

**Comment by anosulchik** [comment]
@rhvgoyal Not sure about your message regarding separate mount namespace. Docker daemon is configured with device mapper on separate disk, here's configuration:

```
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true --storage-opt dm.fs=ext4"
```

Devicemapper devices are created using this script when host starts: https://github.com/projectatomic/docker-storage-setup

P.S. I'm about to reproduce it again to get output `dmsetup info` as you requested.

**Comment by rhvgoyal** [comment]
how are you starting docker. If you are using systemd, then in docker unit file (docker.service), check if you have the option MountFlags=slave in docker.service file or not. If it is there, that means docker daemon will start in a separate mount namespace with slave relationship from parent.

**Comment by anosulchik** [comment]
@rhvgoyal Docker daemon is started by SysV Init since we're on Amazon Linux (RHEL compatible). Please see init script for docker below. It's started with `unshare -m`:

```
$ man unshare
...
-m, --mount
              Unshare the mount namespace.
...
```

```
#!/bin/sh
#
#       /etc/rc.d/init.d/docker
#
#       Daemon for docker.com
#
# chkconfig:   2345 95 05
# description: Daemon for docker.com

### BEGIN INIT INFO
# Provides:       docker
# Required-Start: $network cgconfig
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop docker
# Description: Daemon for docker.com
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="docker"
unshare=/usr/bin/unshare
exec="/usr/bin/$prog"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
logfile="/var/log/$prog"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
[ -e /etc/sysconfig/${prog}-storage ] && . /etc/sysconfig/${prog}-storage

[ -n "${DAEMON_MAXFILES}" ] && ulimit -n "${DAEMON_MAXFILES}"

# Additional start options for the Docker daemon can
# be defined in the $OPTIONS variable in /etc/sysconfig/docker,
# which is also the variable name referenced by the systemd unit.
# If $OPTIONS is not defined, we set it to the value of $other_args,
# which is the variable name expected by the upstream sysvinit script.
OPTIONS="${OPTIONS:-${other_args}}"


prestart() {
    service cgconfig status > /dev/null

    if [[ $? != 0 ]]; then
        service cgconfig start
    fi

}

start() {
    if [ ! -x $exec ]; then
      if [ ! -e $exec ]; then
        echo "Docker executable $exec not found"
      else
        echo "You do not have permission to execute the Docker executable $exec"
      fi
      exit 5
    fi

    check_for_cleanup

    if ! [ -f $pidfile ]; then
        prestart
        printf "Starting $prog:\t"
        echo "\n$(date)\n" >> $logfile
        "$unshare" -m -- nohup $exec daemon ${OPTIONS} ${DOCKER_STORAGE_OPTIONS} &>> $logfile &
        pid=$!
        touch $lockfile
        # wait up to 10 seconds for the pidfile to exist.  see
        # https://github.com/docker/docker/issues/5359
        tries=0
        while [ ! -f $pidfile -a $tries -lt 10 ]; do
            sleep 1
            tries=$((tries + 1))
            echo -n '.'
        done
        if [ ! -f $pidfile ]; then
          failure
          echo
          exit 1
        fi
        success
        echo
    else
        failure
        echo
        printf "$pidfile still exists...\n"
        exit 7
    fi
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile -d 300 $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


check_for_cleanup() {
    if [ -f ${pidfile} ]; then
        /bin/ps -fp $(cat ${pidfile}) > /dev/null || rm ${pidfile}
    fi
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac

exit $?
```

**Comment by novakg** [comment]
Hi All,
I can still see this issue with Docker 1.12.5 (running inside Kubernetes).
Is there any way to fix it?

**Comment by gswallow** [comment]
Have been fighting this problem all week.  I *think* that switching the --dm.fs option to "ext4" on a *freshly built box* fixes it, but only if --dm.use_deferred_deletion and --dm.use_deferred_removal are also set to true.

OS: Ubuntu 16.04.2 LTS
Kernel: 4.4.0-67-generic #88-Ubuntu
Docker version: 1.11.2

docker info:
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: vg0-pool0
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 5.703 GB
 Data Space Total: 73.01 GB
 Data Space Available: 67.31 GB
 Metadata Space Used: 6.877 MB
 Metadata Space Total: 4.291 GB
 Metadata Space Available: 4.284 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-67-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-172-21-215-208
ID: U3MQ:ONOL:YG4A:JLZ2:KVMJ:RN6V:4X76:DIME:6K3O:7TR4:K5WK:ZBOK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

/etc/docker/daemon.json:

{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.thinpooldev=/dev/mapper/vg0-pool0",
    "dm.use_deferred_deletion=true",
    "dm.use_deferred_removal=true",
    "dm.fs=ext4"
  ],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  }
}

If docker starts up and detects any container images created using xfs, then the storage driver will choose to use xfs instead of ext4 and the devicemapper stalling problem occurs.

**Comment by zq-david-wang** [comment]
I have exact issue with docker 1.12.6/centos7.3

> # docker info
> Containers: 1536
>  Running: 61
>  Paused: 0
>  Stopped: 1475
> Images: 29
> Server Version: 1.12.6
> Storage Driver: devicemapper
>  Pool Name: docker-docker--pool
>  Pool Blocksize: 524.3 kB
>  Base Device Size: 10.74 GB
>  Backing Filesystem: xfs
>  Data file: 
>  Metadata file: 
>  Data Space Used: 42.91 GB
>  Data Space Total: 522.3 GB
>  Data Space Available: 479.3 GB
>  Metadata Space Used: 21.15 MB
>  Metadata Space Total: 553.6 MB
>  Metadata Space Available: 532.5 MB
>  Thin Pool Minimum Free Space: 52.23 GB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: true
>  Deferred Deletion Enabled: false
>  Deferred Deleted Device Count: 0
>  Library Version: 1.02.135-RHEL7 (2016-11-16)
> Logging Driver: json-file
> Cgroup Driver: systemd
> Plugins:
>  Volume: local
>  Network: null bridge host overlay
> Swarm: inactive
> Runtimes: docker-runc runc
> Default Runtime: docker-runc
> Security Options: seccomp
> Kernel Version: 3.10.0-514.6.2.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> Number of Docker Hooks: 2
> CPUs: 8
> Total Memory: 62.69 GiB
> Name: ennew-gpu-148
> ID: PHDR:KCER:EEDL:UUCH:WRDF:U7IB:B5WX:6VSG:LRYT:3NK5:VGRZ:N7MZ
> Docker Root Dir: /data/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Insecure Registries:
>  10.19.140.200:30100
>  127.0.0.0/8
> Registries: docker.io (secure)

I was stress testing kubernetes pod creation, which would start about 100*2 docker container on each node, but on some node, it would take a very long time to start running those docker containers, most of the containers were stuck in "Created" status. But eventually, after about 1 hours, the containers would start to run. (I am not sure whether docker recovered itself or kubernets did some help) 
When containers were stucked in "Created", following logs were observed in system log

> # /var/log/messages
> May  4 10:56:22 hostname dockerd-current: time="2017-05-04T10:56:22.401729002+08:00" level=info msg="{Action=create, LoginUID=4294967295, PID=21057}"
> May  4 10:56:22 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:23 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:23 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:23 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:23 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:23 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:24 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:24 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:24 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:25 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:25 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:25 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:26 hostname dockerd-current: time="2017-05-04T10:56:26.159383572+08:00" level=info msg="{Action=create, LoginUID=4294967295, PID=21057}"
> May  4 10:56:26 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:26 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:26 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:27 hostname kubelet: E0504 10:56:27.242944   21057 docker_manager.go:2324] container start failed: RunContainerError: runContainer: operation timeout: context deadline exceeded
> May  4 10:56:27 hostname kubelet: E0504 10:56:27.243021   21057 pod_workers.go:184] Error syncing pod c009e7fe-306d-11e7-b303-9c7da38259a3, skipping: failed to "StartContainer" for "podstresstest-592" with RunContainerError: "runContainer: operation timeout: context deadline exceeded"
> May  4 10:56:27 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:27 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:27 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:27 hostname dockerd-current: time="2017-05-04T10:56:27.773147145+08:00" level=info msg="{Action=create, LoginUID=4294967295, PID=21057}"
> May  4 10:56:28 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:28 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:28 hostname kernel: XFS (dm-56): Unmounting Filesystem
> May  4 10:56:28 hostname kernel: XFS (dm-56): Mounting V5 Filesystem
> May  4 10:56:28 hostname kernel: XFS (dm-56): Ending clean mount
> May  4 10:56:28 hostname kernel: XFS (dm-56): Unmounting Filesystem

**Comment by zq-david-wang** [comment]
Just compare loop based device-mapper with lvm-thin-pool based device-mapper, it seems that the "stuck" happened only on nodes with lvm-thin-pool based device-mapper.

**Comment by bmhkb4** [comment]
Still seeing this issue on latest docker release docker-ce-17.06.1 and kube 1.7 on Centos 7.3.

Containers: 32
 Running: 16
 Paused: 0
 Stopped: 16
Images: 11
Server Version: 17.06.1-ce
Storage Driver: devicemapper
 Pool Name: vg--docker-data
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 7.885GB
 Data Space Total: 102GB
 Data Space Available: 94.12GB
 Metadata Space Used: 3.564MB
 Metadata Space Total: 1.07GB
 Metadata Space Available: 1.066GB
 Thin Pool Minimum Free Space: 10.2GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.667GiB
Name: <redacted>
ID: RC4R:XCUI:QSSR:YYA6:BI7M:HY53:Q5BJ:TOII:ACXE:QC3I:EFNS:IARC
Docker Root Dir: /srv/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

kern.log spam prior to dockerd hang:
device-mapper: thin: Deletion of thin device 14002 failed.

**Comment by RRAlex** [comment]
I'm having the problem directly on creation with XFS on a lvm thin pool (in preparation of glusterfs) on Ubuntu 16.04.3. 
On creation I can only mount it once before it gives those log lines where mount succeeds but gets unmounted right away.
If I reboot, it seems to allow multiple mount/umount without issues.
So I'm guessing it might not be docker related at all.

**Comment by esabol** [comment]
We just upgraded to 17.12.0-ce on a freshly updated CentOS 7.4 system, and we started seeing similar messages (except V5 instead of V4):
```
[ 6139.366530] XFS (dm-12): Unmounting Filesystem
[ 6139.433734] XFS (dm-12): Mounting V5 Filesystem
[ 6139.480419] XFS (dm-12): Ending clean mount
[ 6139.889452] XFS (dm-12): Unmounting Filesystem
[ 6628.155238] XFS (dm-12): Mounting V5 Filesystem
[ 6628.280623] XFS (dm-12): Ending clean mount
[ 6628.307901] XFS (dm-12): Unmounting Filesystem
[ 6628.454615] XFS (dm-12): Mounting V5 Filesystem
[ 6628.562696] XFS (dm-12): Ending clean mount
[ 6628.578117] XFS (dm-12): Unmounting Filesystem
[ 6628.675100] XFS (dm-12): Mounting V5 Filesystem
[ 6628.742618] XFS (dm-12): Ending clean mount
```
`docker ps -a` is plenty fast, but I first noticed the issue because our test suite benchmarks (which involves docker containers) increased 80-100%. :(

docker info:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 569
Server Version: 17.12.0-ce
Storage Driver: devicemapper
 Pool Name: os-dkthinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 39.94GB
 Data Space Total: 51.64GB
 Data Space Available: 11.7GB
 Metadata Space Used: 14.08MB
 Metadata Space Total: 25.17MB
 Metadata Space Available: 11.08MB
 Thin Pool Minimum Free Space: 5.163GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: Scientific Linux 7.4 (Nitrogen)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.685GiB
Name: heabox
ID: K7AD:FT4R:OSNP:CEAL:VZHD:FG6N:DQEG:G5MU:UNMF:3IBV:RLCM:KDT3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
Any ideas?

**Comment by bmhkb4** [comment]
I switched to overlay2 and still saw issues and finally figured out it was a bug in the container processes that caused it to spiral. Good luck

**Comment by esabol** [comment]
>  finally figured out it was a bug in the container processes that caused it to spiral

I don't know what that means. Can you elaborate, @bmhkb4 ? Thanks!

**Comment by bmhkb4** [comment]
I don't remember all the facts because we never did determine the exact root cause. Essentially, it was a custom compiled python module running inside a container that was causing the issue. The only way I figured it out was by process of elimination, not by actually figuring out what the problem was.

**Comment by esabol** [comment]
That doesn't make any sense to me, frankly.

We tried reverting the SPECTRE kernel patch. That didn't help. We're going to try to downgrade Docker CE from 17.09.1-ce to 17.12.0-ce next.

**Comment by esabol** [comment]
> We're going to try to downgrade Docker CE from 17.12.0-ce to 17.09.1-ce next.

That didn't resolve the problem, unfortunately. I did see a 15% improvement to performance in my benchmarks after downgrading from 17.12.0-ce back to 17.09.1-ce. That's very disappointing, but presumably a separate issue.

Also, my sys admin has changed his tune. At first he was sure these XFS messages were a new development, but he's since found evidence that it predates our last round of kernel and Docker updates. Trying to track down when exactly these XFS messages started for us.

**Comment by esabol** [comment]
Well, we finally transitioned  to overlay2, and that solved our problem. No more constant "XFS... Mounting V5 Filesystem ... Ending clean mount ... Unmounting Filesystem" messages! Plus response times increased by close to 50%. Pretty happy about the switch. This is on CentOS 7.4 with all the latest updates.
