### ISSUE TITLE
Removal of containers concurrently using aufs storage often fails

### ISSUE THREAD

**Issue by trianglee** [moby/moby#21111]
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /tmp/docker1.graph/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.8 GiB
Name: prov-dev
ID: N5JQ:J4OH:U2D2:EAHM:K2RK:L5TI:5RBL:IMCE:72AO:7NHA:ERK3:EKC7
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine.

**Steps to reproduce the issue:**
1. Create and remove containers concurrently in multiple processes.
This can be reproduced by running the following scripts (the number of iterations may need to be adjusted) -
**resource_busy_test.sh**

```
#!/bin/bash

DIRS_COUNT=3

docker pull ubuntu

DIRS=`seq -s" " 1 $DIRS_COUNT`
for DIR in $DIRS; do
        mkdir -p $DIR
        pushd $DIR
        /bin/bash ../resource_busy_test_body.sh &
        echo $!
        popd
done
```

Which uses -
**resource_busy_test_body.sh**

```
#!/bin/bash

ITERATIONS=5

for i in `seq -s' ' 1 $ITERATIONS` ; do
        rm -f cid.txt
        docker run -d --cidfile=cid.txt ubuntu /bin/bash
        docker rm -f `cat cid.txt`
        if [ $? -ne 0 ] ; then
                echo "docker rm failed!"
                exit 1
        fi
done
```

**Describe the results you received:**
During the run of these scripts (which concurrently create nad destroy containers), very often the following error is displayed -

```
Failed to remove container (5e23ed6749678348c439524950871629c8e7bb9e712a6f402f5e8965f4c2fe10): 
Error response from daemon: Unable to remove filesystem for 5e23ed6749678348c439524950871629c8e7bb9e712a6f402f5e8965f4c2fe10: 
remove /tmp/docker1.graph/containers/5e23ed6749678348c439524950871629c8e7bb9e712a6f402f5e8965f4c2fe10/shm: 
device or resource busy
docker rm failed!
```

**Describe the results you expected:**
Such concurrency errors shouldn't happen.

**Additional information you deem important (e.g. issue happens only occasionally):**
A work-around for this problem is to avoid using the aufs storage. The problem doesn't happen when using device-mapper (maybe because it is slower, so a race isn't as likely?).

**Comment by bprodoehl** [comment]
This looks like #21101 and #21078.

**Comment by trianglee** [comment]
I don't see a lot of similarity with either.
In #21101 - the error message is different, and the eventual outcome is a "lockup" - which I never see with this problem.
In #21078 - the error messages are also different, and things end up with a "panic", which I don't see.
Am I missing something?

**Comment by bprodoehl** [comment]
In the discussion on #21078, @cpuguy83 said:

"This is probably because of https://github.com/docker/docker/blob/v1.10.2/daemon/graphdriver/aufs/aufs.go#L230
Modification is happening while not protected by a mutex.
This is most likely fixed in master since it is now protected: https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L232"

Sounds like a possible root cause of just the concurrency issue you're running into. I would try a current build off of https://master.dockerproject.org/ if you can, as that should have the lock.

**Comment by trianglee** [comment]
I tried with latest master. Problem is unfortunately still reproduced.

Version details -

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   ed6fb41
 Built:        Sat Mar 12 22:53:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   ed6fb41
 Built:        Sat Mar 12 22:53:45 2016
 OS/Arch:      linux/amd64
```

Same reproduction instructions cause the problem.

**Comment by allencloud** [comment]
Can I start a container without mounting shm into itself?
@thaJeztah

**Comment by thaJeztah** [comment]
The AuFS storage driver has been deprecated and has been removed from our code base (https://github.com/moby/moby/pull/45342) for the upcoming v24.0.0 release, so we're closing tickets related to AuFS
