### ISSUE TITLE
hostnames with new networking are case-sensitive

### ISSUE THREAD

**Issue by schmunk42** [moby/moby#21169]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        2016-03-10T21:49:11.235199091+00:00
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 101
Images: 522
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1205
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
CPUs: 3
Total Memory: 1.463 GiB
Name: dev7
ID: C63I:2K5W:YZ5P:7M54:KD65:SVJE:QKDE:H5JS:BXHI:I27N:BOOP:GECU
Debug mode (server): true
 File Descriptors: 49
 Goroutines: 75
 System Time: 2016-03-13T21:06:17.199571395Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: schmunk42
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox

**Steps to reproduce the issue:**
1. ping another host

**Describe the results you received:**

```
root@8eaa8bfbd08b:/app# ping HUB
ping: unknown host
root@8eaa8bfbd08b:/app# ping hub
PING hub (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: icmp_seq=0 ttl=64 time=0.066 ms
```

**Describe the results you expected:**

An answer also for `ping HUB`

**Comment by thaJeztah** [comment]
labeling as bug; afaik, DNS lookups should be case insensitive (although this may be a corner case)

**Comment by schmunk42** [comment]
@thaJeztah Just as a general info, I often used uppercase hostnames in config files, etc... because I found it easier to remember that they were set by links or ENV vars.

**Comment by tfasz** [comment]
I opened a similar issue last week here: docker/libnetwork#993

Our work around for the time being has been to create multiple network aliases for each container - one in UPPERCASE and one in lowercase.

**Comment by thaJeztah** [comment]
Thanks for linking that issue @tfasz

**Comment by philcontrolf1** [comment]
For what it's worth, the `System.Uri` class in .NET Core automatically lower cases any host name it's given, which isn't unreasonable as it makes no difference to a standards-compliant implementation. This makes upper-case host names unusable in Docker (Swarm in our case). We're working around this by creating all the service names in lower case, but it would certainly be less confusing all round if Docker's DNS were case-insensitive.

**Comment by BretFisher** [comment]
Having read the related issues to this, repro'd the issue, [skimmed a related RFC on DNS insensitivity](https://tools.ietf.org/html/rfc4343) and now seen it in the wild, I vote for at least @stevvooe's recommendation in https://github.com/moby/moby/issues/28689#issuecomment-262407822 that when there's no container naming conflicts, that DNS resolves lowercase names of containers with mixed-case container names.

If you have a system/admin creating containers with mixed case names for easier reading of `container ls`, one might assume that DNS inside containers resolves a lower case name, which it currently does not.

Another example of current behavior:

```shell
~ docker network create app
d9911774eb93530b90bc3e7cbd3e7e4a69303e9f2c3c8f495d748d8642096fc5
~ docker run --name app1SQL --network app -d postgres
880df697ad7b23e94103655a86708c0ca103859883c062b0170c2b96022e384f
~ docker run --rm --network app alpine ping app1sql
ping: bad address 'app1sql'
~ docker run --rm --network app alpine ping app1SQL
PING app1SQL (172.19.0.2): 56 data bytes
```

**Comment by philcontrolf1** [comment]
@BretFisher Sounds good to me - it's essentially exactly that which burned us when creating our swarm.

**Comment by stevvooe** [comment]
@philcontrolf1 @BretFisher Reading back over https://github.com/moby/moby/issues/28689#issuecomment-262407822, that seems like the correct approach, albeit slightly tricky. :D 

@mavenugo Does this approach seem reasonable?

**Comment by bvandehey** [comment]
This appears to still be an open issue. Here is an example of the problem that case sensitive DNS on the embedded DNS server causes within at least Windows:

Using the sample docker-compose file below, the first "command" line doesn't resolve any alias named myservice whereas the second "command" line resolves an alias named MyService. It also appears after the first lookup, if the name wasn't an exact match based on the case, the fact that the name wasn't found is cached whereas in the second example where the correct case was used and found in the alias list, the name is cached and is no longer case sensitive from that point forward.

Example docker-compose.yaml file:
~~~~
version: "3.3"
services: 
  testservice:
    image: microsoft/windowsservercore
    command: powershell.exe "ping myservice -n 1; ping MyService -n 1; ping myservice -n 1; "
    command: powershell.exe "ping MyService -n 1; ping myservice -n 1; ping MyService -n 1; "
    networks: 
       backend:
        aliases:
            - MyService
networks:
  backend:
~~~~

This shows that if the first query to the embedded DNS server doesn't match the case, then it will be cached in the local DNS cache and not able to be resolved.

**Comment by philcontrolf1** [comment]
@bvandehey Oooh, that's fun. So I can poison Window's DNS cache by forcing a lookup of a name with different capitalization. I think the obvious attack is disallowed because I can't call a container "Google.Co.Uk" but I wonder if there's something here...

**Comment by thaJeztah** [comment]
The caching only seems to be an issue on Windows, not linux (from some quick testing)

**Comment by thaJeztah** [comment]
ping @jhowardmsft PTAL for the DNS caching issue

**Comment by friism** [comment]
@msabansal might now what's up

**Comment by kleptog** [comment]
Ran into an issue today with case sensitivity of DNS in Docker. There are DNS libraries (like evdns) which implement case randomisation of DNS queries for extra security (see this [IETF draft](https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00)) which means a connection to a service "test-1-database" will generate a DNS query like "TeST-1-daTabAse", which docker does not recognise. See https://github.com/pgbouncer/pgbouncer/issues/122 for an example.

Incidentally, it looks like you can disable this by putting `options randomize-case:0
` in the `/etc/resolve.conf` but I have not yet tested this.

**Comment by thaJeztah** [comment]
@kleptog didn't know about that proposal; note that instead of manually editing `/etc/resolv.conf` you can also pass `--dns-opt randomize-case:0` on `docker run` (or add it to your daemon configuration) to have docker set that option.

**Comment by kleptog** [comment]
@thaJeztah Thanks. Though that would require telling the user of the image to take special steps, since it can't be "baked into" the image. Modifying the `resolv.conf` make the image Just Work.

Still, I think this is something that should be fixed in Docker itself, do you agree?

**Comment by thaJeztah** [comment]
> I think this is something that should be fixed in Docker itself, do you agree?

Yes, [I agree](https://github.com/moby/moby/issues/21169#issuecomment-196232538) this should be addressed; https://github.com/moby/moby/issues/21169#issuecomment-323106446 provides some pointers as to how it could possibly be addressed (but backward-compatibility could definitely be a thing).

I don't think someone is working on it currently, but contributions are welcome if someone wants to look into it

**Comment by peterpundy** [comment]
Yes I agree.  This is still an issue with Docker 18.03.1-ce-win65 (17513).   Hostname resolution should be case insensitive.

**Comment by FiloSottile** [comment]
Ran into this as well because I run a resolver with the dns0x20 security feature enabled. Case sensitive DNS resolution is off-spec and will cause mysterious failures due to caching.

**Comment by riccardo** [comment]
Same problem here. I want to directly call the [Azure IoT Edge edgeHub component ](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition) from my docker container without binding its ports to the docker host. Unfortunately, the Azure IoT Edge team decided to call the container _edgeHub_ instead of _edgehub_ , resulting in inconsistencies in the way different libraries resolve the host name.

Since this is quite an old issue now: is there a reasonable workaround to this behaviour ?

**Comment by gbolo** [comment]
This is also an issue for me. When using nginx as a reverse proxy for other containers, nginx will always lower-case the host name (even when the case is correct in the config file) and as a result will not be able to resolve the name! DNS names are supposed to be case insensitive (RFC 4343), docker should follow this when faking DNS...

**Comment by gbolo** [comment]
@thaJeztah is this still planning to be addressed?

**Comment by thaJeztah** [comment]
Not being worked on currently, but help would definitely be welcome if someone wants to give this a go (see https://github.com/moby/moby/issues/28689#issuecomment-262407822 for details on implementation). 

From a quick glance, the resolver code lives in libnetwork (https://github.com/docker/libnetwork/blob/a86d2765b829fb122c70eea7a914d59a8fb1df4a/resolver.go), with implementations of the `Resolver` interface in [sandbox.go](https://github.com/docker/libnetwork/blob/a86d2765b829fb122c70eea7a914d59a8fb1df4a/sandbox.go#L522-L588) and [network.go](https://github.com/docker/libnetwork/blob/a86d2765b829fb122c70eea7a914d59a8fb1df4a/network.go#L1935-L1975)

**Comment by thaJeztah** [comment]
Also /cc @arkodg in case you have thoughts on this

**Comment by arkodg** [comment]
@thaJeztah raised a PR

TODOs

1. Make sure we return a `err.Conflict` if two containers with different names but same case-insensitive names try to connect to the same network (eg. containers `FOO` and `foo` connecting to network `bar` should *NOT* be permitted) . This might break some old functionality but at least abides by the RFC434, and is less extreme than forcing all container-names to be lowercase (which is definitely something you could share your thoughts on :))
2. Add test-cases in `libnetwork` and `moby` for all the scenarios
