### ISSUE TITLE
Docker pushing too much

### ISSUE THREAD

**Issue by MatthewHerbst** [moby/moby#21536]
When I push my container, one of the layers I am pushing (270.4MB) pushes more information than the size of the layer. I don't know what it's pushing, but the upload count just keeps growing past the actual layer size.

What's going on?

```
docker push myRepo/myApp
The push refers to a repository [docker.io/myRepo/myApp]
8797480d7665: Pushing [==================================================>] 284.9 MB
cc6fc4ca1de5: Layer already exists
...
3ee473a9522d: Layer already exists
```

Note how the pushed size is larger than the actual layer.

After a while the push does succeed, but it claims to have pushed almost 100MB more than the layer size. Why?

I'm running on OS X 10.10.5

**Output of `docker version`:**

```
Docker version 1.10.0, build 590d5108
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NEXJ:YQ3T:N6K6:HKNY:FIAT:5NIT:FQSA:WOWK:J4BI:46V3:EQBH:JNIK
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 34
 System Time: 2016-03-26T02:29:31.511267029Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mherbst
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by thaJeztah** [comment]
just to be sure, have you tried upgrading to the latest version of boot2docker / docker-machine? There have been three patch releases since docker 1.10.0 (we're at 1.10.3 currently), so it's possible that things have been fixed.

**Comment by MatthewHerbst** [comment]
@thaJeztah I'll try that. Do you know if there are any DockerToolbox mirrors in Asia? In China right now, and download over VPN is going to take all day basically.

**Comment by MatthewHerbst** [comment]
The issue persists after upgrading to 1.10.3. A layer of 266.2 MB tried to push more - I killed it at 269.9 MB. See console output below.

(Below shows: I run push just to get output of size, then kill it. Restart the machine to wipe push cache, then push again. You can the same layer - looked at hashes - is pushing beyond its actual size.)

![screen shot 2016-03-26 at 2 51 35 pm](https://cloud.githubusercontent.com/assets/1287375/14058668/8b6934da-f362-11e5-9096-d07763351bbe.png)

**Comment by thaJeztah** [comment]
Thanks!

ping @aaronlehmann any ideas?

**Comment by aaronlehmann** [comment]
Hi @MatthewHerbst - I took a look at this and it looks like size that's used to produce this progress bar is calculated a bit differently from the actual size of the data being uploaded. Specifically, it doesn't take into account file metadata. This normally doesn't make much difference, but if a layer has many small files, it could account for the large discrepancy you see.

In a future version, we might store the exact size of the layer archive to produce a more accurate progress bar. In the mean time, rest assured that the upload continuing after completion of the progress bar doesn't necessarily mean anything is wrong.

**Comment by MatthewHerbst** [comment]
@aaronlehmann that's great to know, thanks! Hopefully anyone else confused finds this thread. Would you like me to leave this open so it can be addressed in the future?

**Comment by aaronlehmann** [comment]
Sure, let's keep this open.

**Comment by linlinlinlin** [comment]
+1, hope this can be fix in the future. #22352

**Comment by LK4D4** [comment]
@thaJeztah @aaronlehmann do you know if this was worked on?

**Comment by aaronlehmann** [comment]
I don't think it has.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I haven't heard about this specific issue in a long time
