### ISSUE TITLE
Ubuntu 16.04 install for 1.11.2 hangs

### ISSUE THREAD

**Issue by corbinu** [moby/moby#23347]
---
## BUG REPORT INFORMATION

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 16.04
Linux Kernel 4.6.0-040600 (had to upgrade to fix a Wifi issue)
Docker 1.11.2

**Steps to reproduce the issue:**
1. Try to install docker according to Ubuntu install instructions

**Describe the results you received:**
Install hangs at 

```
The following NEW packages will be installed:
  docker-engine
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/14.5 MB of archives.
After this operation, 73.4 MB of additional disk space will be used.
Selecting previously unselected package docker-engine.
(Reading database ... 226108 files and directories currently installed.)
Preparing to unpack .../docker-engine_1.11.2-0~xenial_amd64.deb ...
Unpacking docker-engine (1.11.2-0~xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu6) ...
Setting up docker-engine (1.11.2-0~xenial) ...

Progress: [ 66%] [#######################################...................] 
```

**Additional information you deem important (e.g. issue happens only occasionally):**
/var/log/apt/term.log

```
Preparing to unpack .../docker-engine_1.11.2-0~xenial_amd64.deb ...
Unpacking docker-engine (1.11.2-0~xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu6) ...
Setting up docker-engine (1.11.2-0~xenial) ...
```

/var/log/dpkg.log

```
2016-06-07 11:33:02 startup packages configure
2016-06-07 11:35:42 startup archives unpack
2016-06-07 11:35:42 install docker-engine:amd64 <none> 1.11.2-0~xenial
2016-06-07 11:35:42 status half-installed docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:44 status triggers-pending man-db:amd64 2.7.5-1
2016-06-07 11:35:44 status triggers-pending ureadahead:amd64 0.100.0-19
2016-06-07 11:35:44 status triggers-pending systemd:amd64 229-4ubuntu6
2016-06-07 11:35:44 status triggers-pending ureadahead:amd64 0.100.0-19
2016-06-07 11:35:44 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:44 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:44 trigproc man-db:amd64 2.7.5-1 <none>
2016-06-07 11:35:44 status half-configured man-db:amd64 2.7.5-1
2016-06-07 11:35:45 status installed man-db:amd64 2.7.5-1
2016-06-07 11:35:45 trigproc ureadahead:amd64 0.100.0-19 <none>
2016-06-07 11:35:45 status half-configured ureadahead:amd64 0.100.0-19
2016-06-07 11:35:45 status installed ureadahead:amd64 0.100.0-19
2016-06-07 11:35:45 trigproc systemd:amd64 229-4ubuntu6 <none>
2016-06-07 11:35:45 status half-configured systemd:amd64 229-4ubuntu6
2016-06-07 11:35:45 status installed systemd:amd64 229-4ubuntu6
2016-06-07 11:35:45 startup packages configure
2016-06-07 11:35:45 configure docker-engine:amd64 1.11.2-0~xenial <none>
2016-06-07 11:35:45 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:45 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:45 status triggers-pending systemd:amd64 229-4ubuntu6
2016-06-07 11:35:45 status triggers-pending ureadahead:amd64 0.100.0-19
2016-06-07 11:35:45 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:45 status triggers-pending ureadahead:amd64 0.100.0-19
2016-06-07 11:35:45 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-06-07 11:35:45 status half-configured docker-engine:amd64 1.11.2-0~xenial
```

**Comment by justinoue** [comment]
I would just like to chime in and say I am having the same issue on Ubuntu 16.04

**Comment by thaJeztah** [comment]
Is this on bare-metal, cloud? Are you also using a non-standard kernel? I tried to reproduce this, but not able to

**Comment by corbinu** [comment]
@thaJeztah Baremetal Dell E6330 yes the kernel is non standard is Linux Kernel 4.6.0-04060

**Comment by justinoue** [comment]
@thaJeztah I am installing on my laptop, bare metal, no VM. I can provide more details if necessary, just let me know what to pull.

**Comment by ilyakitaev** [comment]
It freezes on /bin/systemd-tty-ask-password-agent 

```
root      6350  0.0  0.0  61924  3988 pts/18   S+   20:21   0:00 sudo dpkg --configure -a
root      6351  0.0  0.0  30880  8276 pts/18   S+   20:21   0:00 dpkg --configure -a
root      6352  0.0  0.0   4508  1712 pts/18   S+   20:21   0:00 /bin/sh /var/lib/dpkg/info/docker-engine.postinst configure
root      6375  0.0  0.0   4508  1724 pts/18   S+   20:21   0:00 /bin/sh /usr/sbin/invoke-rc.d docker start
root      6410  0.0  0.0  33236  1392 pts/18   S+   20:21   0:00 systemctl --job-mode=ignore-dependencies start docker.service
root      6411  0.0  0.0  15408  1020 pts/18   S+   20:21   0:00 /bin/systemd-tty-ask-password-agent --watch
```

**Comment by ilyakitaev** [comment]
sudo dmsetup mknodes fixed it for me

**Comment by corbinu** [comment]
@ilyakitaev Thanks that fixed it!

**Comment by corbinu** [comment]
Nvm it installed but I still can't connect

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-06-10 00:56:21 PDT; 38s ago
     Docs: https://docs.docker.com
 Main PID: 940 (docker)
    Tasks: 21
   Memory: 48.1M
      CPU: 237ms
   CGroup: /system.slice/docker.service
           ├─ 940 /usr/bin/docker daemon -H fd://
           └─1043 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --start-timeout 2m

Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.539345000-07:00" level=info msg="Graph migration to content-addressability
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.570993000-07:00" level=info msg="Firewalld running: false"
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.654696000-07:00" level=info msg="Default bridge (docker0) is assigned with
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.760047000-07:00" level=warning msg="Your kernel does not support swap memo
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.762168000-07:00" level=info msg="Loading containers: start."
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.781919000-07:00" level=info msg="Loading containers: done."
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.781968000-07:00" level=info msg="Daemon has completed initialization"
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.782011000-07:00" level=info msg="Docker daemon" commit=b9f10c9 graphdriver
Jun 10 00:56:21 Corbinu-E6330 systemd[1]: Started Docker Application Container Engine.
Jun 10 00:56:21 Corbinu-E6330 docker[940]: time="2016-06-10T00:56:21.801788000-07:00" level=info msg="API listen on /var/run/docker.sock"
~

➜  ~ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by justinoue** [comment]
I'm having issues with my containers exiting with code 139 now. The ubuntu container and hello world container run fine. But the alpine container or any of the ones that I've developed do not.

This is my syslog while trying to run "docker run -it alpine sh"

[syslog.txt](https://github.com/docker/docker/files/309585/syslog.txt)

**Comment by kinsomicrote** [comment]
I'm having same issue on my machine. I ran the code posted by @ilyakitaev  and I got the prompt: `sudo: dmsetup: command not found`. Am I doing anything wrong?

**Comment by joedoes** [comment]
Thanks @ilyakitaev , worked for me on fresh install of 16.04

**Comment by cpswan** [comment]
Same issue here with Ubuntu 16.04 with stock 4.4.0-7-generic x86_64 kernel on a VMware Workstation VM

I tried running ```docker info``` in a separate shell, and that also hung

Trying to run ```sudo dmsetup mknodes``` as suggested by @ilyakitaev resulted in the same ```sudo: dmsetup: command not found``` as seen by @kinsomicrote of course ```sudo apt-get install dmsetup -y``` fails at this point due to the hung docker-engine install. Running ```sudo dpkg --configure -a``` seemed to complete the docker-engine (1.11.2-0-xenial) setup, but I still get a hang on ```docker info``` (even after successfully installing dmsetup and doing ```sudo dmsetup mknodes```).

After all that... ```sudo apt-get install -y --reinstall docker-engine``` seems to have sorted things out. At least ```docker info``` works:

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-526250-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 460.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 18.36 GB
 Metadata Space Used: 1.106 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-7-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 975.1 MiB
Name: xenial
ID: ICIC:6PYH:JZDP:AGKC:I7AO:BECQ:6F7L:645L:4VQ6:YPAX:4WOA:WZON
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

But ```docker run hello-world``` fails:

```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a9d36faac0fe: Pull complete
Digest: sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: Container command '/hello' not found or does not exist..
```

I want overlay rather than device mapper anyway so I follow my [own guidance](http://blog.thestateofme.com/2015/12/24/using-overlay-file-system-with-docker-on-systemd-ubuntu/) to reconfigure the storage driver, and at last things work as expected:

```
$docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a9d36faac0fe: Pull complete
Digest: sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619
Status: Downloaded newer image for hello-world:latest

Hello from Docker.
This message shows that your installation appears to be working correctly.

<snipped>
```

**Comment by lillem4n** [comment]
On kernel 4.7.0-rc3 I have the same issue (hangs on Setting up docker-engine (1.11.2-0~xenial) ...)

However, it got working again, hello world and all, when doing this:
sudo kill <apt PID>;
sudo rm /var/lib/dpkg/lock;
sudo dmsetup mknodes
sudo apt-get install -y --reinstall docker-engine

debug info:
lilleman@rex:~$ uname -a
Linux rex 4.7.0-040700rc3-generic #201606121131 SMP Sun Jun 12 15:34:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chb0github** [comment]
I am running on cloud VM and I get the same issue
Linux ubuntu 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ShakataGaNai** [comment]
I too have run across this issue with a brand new Linode 16.04 instance. I did all the usual dist-upgrade stuff before install, no dice. I also tried switching from the Linode kernel to the the distribution default kernel (per https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm ) and had the same issue. 

On my most recent attempt I did the `curl -sSL https://get.docker.com/ | sh` method of install, hung as well. Here's the full process list:

`root@ubuntu:~# ps -axu
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.3  0.3  38424  6528 ?        Ss   21:27   0:02 /sbin/init
root         2  0.0  0.0      0     0 ?        S    21:27   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        S    21:27   0:00 [ksoftirqd/0]
root         4  0.0  0.0      0     0 ?        S    21:27   0:00 [kworker/0:0]
root         5  0.0  0.0      0     0 ?        S<   21:27   0:00 [kworker/0:0H]
root         6  0.0  0.0      0     0 ?        S    21:27   0:00 [kworker/u2:0]
root         7  0.0  0.0      0     0 ?        S    21:27   0:00 [rcu_sched]
root         8  0.0  0.0      0     0 ?        S    21:27   0:00 [rcu_bh]
root         9  0.0  0.0      0     0 ?        S    21:27   0:00 [migration/0]
root        10  0.0  0.0      0     0 ?        S    21:27   0:00 [kdevtmpfs]
root        11  0.0  0.0      0     0 ?        S<   21:27   0:00 [netns]
root       277  0.0  0.0      0     0 ?        S<   21:27   0:00 [writeback]
root       279  0.0  0.0      0     0 ?        S<   21:27   0:00 [crypto]
root       280  0.0  0.0      0     0 ?        S<   21:27   0:00 [kintegrityd]
root       281  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root       283  0.0  0.0      0     0 ?        S<   21:27   0:00 [kblockd]
root       365  0.0  0.0      0     0 ?        S<   21:27   0:00 [ata_sff]
root       379  0.0  0.0      0     0 ?        S<   21:27   0:00 [md]
root       474  0.0  0.0      0     0 ?        S<   21:27   0:00 [rpciod]
root       616  0.0  0.0      0     0 ?        S    21:27   0:00 [kswapd0]
root       617  0.0  0.0      0     0 ?        S<   21:27   0:00 [vmstat]
root       723  0.0  0.0      0     0 ?        S    21:27   0:00 [ecryptfs-kthrea]
root       725  0.0  0.0      0     0 ?        S<   21:27   0:00 [nfsiod]
root       734  0.0  0.0      0     0 ?        S<   21:27   0:00 [cifsiod]
root       746  0.0  0.0      0     0 ?        S    21:27   0:00 [jfsIO]
root       747  0.0  0.0      0     0 ?        S    21:27   0:00 [jfsCommit]
root       748  0.0  0.0      0     0 ?        S    21:27   0:00 [jfsSync]
root       754  0.0  0.0      0     0 ?        S<   21:27   0:00 [xfsalloc]
root       755  0.0  0.0      0     0 ?        S<   21:27   0:00 [xfs_mru_cache]
root       758  0.0  0.0      0     0 ?        S<   21:27   0:00 [glock_workqueue]
root       759  0.0  0.0      0     0 ?        S<   21:27   0:00 [delete_workqueu]
root       765  0.0  0.0      0     0 ?        S<   21:27   0:00 [gfs_recovery]
root       856  0.0  0.0      0     0 ?        S<   21:27   0:00 [acpi_thermal_pm]
root      1388  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1389  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1390  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1391  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1392  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1393  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1394  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1395  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1396  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1397  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1398  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1399  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1400  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1401  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1402  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1403  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1437  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1440  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1442  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1445  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1448  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1451  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1454  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1457  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1460  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1462  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1463  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1464  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1465  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1466  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1467  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1468  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1469  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1470  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1471  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1472  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1473  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1474  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1475  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1476  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1511  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1512  0.0  0.0      0     0 ?        S<   21:27   0:00 [drbd-reissue]
root      1513  0.0  0.0      0     0 ?        S<   21:27   0:00 [rbd]
root      1515  0.0  0.0      0     0 ?        S    21:27   0:00 [scsi_eh_0]
root      1516  0.0  0.0      0     0 ?        S<   21:27   0:00 [scsi_tmf_0]
root      1519  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1526  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1785  0.0  0.0      0     0 ?        S    21:27   0:00 [scsi_eh_1]
root      1791  0.0  0.0      0     0 ?        S    21:27   0:00 [kworker/u2:3]
root      1792  0.0  0.0      0     0 ?        S<   21:27   0:00 [scsi_tmf_1]
root      1802  0.0  0.0      0     0 ?        S    21:27   0:00 [scsi_eh_2]
root      1807  0.0  0.0      0     0 ?        S<   21:27   0:00 [scsi_tmf_2]
root      1835  0.0  0.0      0     0 ?        S<   21:27   0:00 [kpsmoused]
root      1839  0.0  0.0      0     0 ?        S<   21:27   0:00 [raid5wq]
root      1843  0.0  0.0      0     0 ?        S<   21:27   0:00 [dm_bufio_cache]
root      1867  0.0  0.0      0     0 ?        S<   21:27   0:00 [ipv6_addrconf]
root      1884  0.0  0.0      0     0 ?        S<   21:27   0:00 [ceph-msgr]
root      1907  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1927  0.0  0.0      0     0 ?        S<   21:27   0:00 [deferwq]
root      1928  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1935  0.0  0.0      0     0 ?        S<   21:27   0:00 [bioset]
root      1939  0.0  0.0      0     0 ?        S<   21:27   0:00 [kworker/0:1H]
root      1940  0.0  0.0      0     0 ?        S    21:27   0:00 [jbd2/sda-8]
root      1941  0.0  0.0      0     0 ?        S<   21:27   0:00 [ext4-rsv-conver]
root      1976  0.0  0.1  35280  3472 ?        Ss   21:27   0:00 /lib/systemd/systemd-journald
root      1981  0.0  0.0      0     0 ?        S    21:27   0:00 [kauditd]
root      2002  0.0  0.1  41948  3436 ?        Ss   21:27   0:00 /lib/systemd/systemd-udevd
root      2015  0.0  0.0      0     0 ?        S    21:27   0:00 [kworker/0:5]
systemd+  2594  0.0  0.1 100328  2544 ?        Ssl  21:27   0:00 /lib/systemd/systemd-timesyncd
syslog    3251  0.0  0.1 256400  3360 ?        Ssl  21:27   0:00 /usr/sbin/rsyslogd -n
root      3267  0.0  0.2 275772  6076 ?        Ssl  21:27   0:00 /usr/lib/accountsservice/accounts-daemon
root      3283  0.0  0.1  29012  3024 ?        Ss   21:27   0:00 /usr/sbin/cron -f
message+  3293  0.0  0.1  42896  3736 ?        Ss   21:27   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activ
root      3311  0.0  0.1  28552  3016 ?        Ss   21:27   0:00 /lib/systemd/systemd-logind
root      3454  0.0  0.1  15760  2200 ttyS0    Ss+  21:27   0:00 /sbin/agetty --keep-baud 115200 38400 9600 ttyS0 vt220
root      3455  0.0  0.0  15944  1852 tty1     Ss+  21:27   0:00 /sbin/agetty --noclear tty1 linux
root      3650  0.0  0.3  65616  6240 ?        Ss   21:27   0:00 /usr/sbin/sshd -D
root      3660  0.0  0.3  95496  7128 ?        Ss   21:28   0:00 sshd: root@pts/0
root      3663  0.0  0.2  38104  5648 ?        Ss   21:28   0:00 /lib/systemd/systemd --user
root      3669  0.0  0.1  61876  2632 ?        S    21:28   0:00 (sd-pam)
root      3689  0.0  0.2  22156  4880 pts/0    Ss   21:28   0:00 -bash
root      3856  0.0  0.0   4512  1728 pts/0    S    21:30   0:00 sh
root      3876  0.0  0.0   4512   756 pts/0    S    21:30   0:00 sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
root      4271  0.3  3.4 109232 70228 pts/0    S    21:30   0:01 apt-get install -y -q docker-engine
root      5971  0.0  0.1  19796  4092 pts/1    Ss+  21:30   0:00 /usr/bin/dpkg --status-fd 60 --configure perl-modules-5.22:all libperl5.22:amd64 perl
root      6055  0.0  0.0   4512  1752 pts/1    S+   21:30   0:00 /bin/sh /var/lib/dpkg/info/docker-engine.postinst configure
root      6108  0.0  0.0   4512  1760 pts/1    S+   21:30   0:00 /bin/sh /usr/sbin/invoke-rc.d docker start
root      6142  0.0  0.0  26172  1384 pts/1    S+   21:30   0:00 systemctl start docker.service
root      6144  0.0  1.2 400184 25448 ?        Ssl  21:30   0:00 /usr/bin/docker daemon -H fd://
root      6162  0.0  0.5 204020 10484 ?        Ssl  21:30   0:00 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime d
root      6175  0.0  0.0      0     0 ?        S<   21:30   0:00 [loop0]
root      6178  0.0  0.0      0     0 ?        S<   21:30   0:00 [loop1]
root      6183  0.0  0.0      0     0 ?        S<   21:30   0:00 [kdmflush]
root      6187  0.0  0.0      0     0 ?        S<   21:30   0:00 [bioset]
root      6188  0.0  0.0      0     0 ?        S<   21:30   0:00 [kcopyd]
root      6189  0.0  0.0      0     0 ?        S<   21:30   0:00 [bioset]
root      6190  0.0  0.0      0     0 ?        S<   21:30   0:00 [dm-thin]
root      6191  0.0  0.0      0     0 ?        S<   21:30   0:00 [bioset]
root      6250  0.0  0.1  37368  3256 pts/0    R+   21:39   0:00 ps -axu
root@ubuntu:~#`

**Comment by chb0github** [comment]
I actually was using a fresh linode instance too.

**Comment by justinoue** [comment]
I didn't do anything on purpose or specific, but I upgraded to kernel 4.6.2-040602-generic from 4.6.0 and docker seems to work fine.

**Comment by ericmok** [comment]
I'm running Linux Kernel 4.6.4-040604-generic and my install also hangs the same way.
I followed @thaJeztah and @watchwithmike's instructions in https://github.com/docker/docker/issues/23968 to run the docker-engine using the overlay engine:

I created `/etc/docker/daemon.json` and put:
```
{
    "storage-driver": "overlay"
}
```

After restarting my computer I ran `sudo dpkg --configure -a`.
`sudo docker run hello-world` works and `sudo service docker status` shows it is actively running. I guess that means its working.

Also probably relevant to: https://github.com/docker/docker/issues/24478

**Comment by kenny1har** [comment]
on a fresh linode : Ubuntu 16.04 LTS.
`2016-07-23 13:22:31 status unpacked libltdl7:amd64 2.4.6-0.1
2016-07-23 13:22:31 status half-configured libltdl7:amd64 2.4.6-0.1
2016-07-23 13:22:31 status installed libltdl7:amd64 2.4.6-0.1
2016-07-23 13:22:31 configure docker-engine:amd64 1.11.2-0~xenial <none>
2016-07-23 13:22:31 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-07-23 13:22:31 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-07-23 13:22:31 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-07-23 13:22:31 status unpacked docker-engine:amd64 1.11.2-0~xenial
2016-07-23 13:22:31 status half-configured docker-engine:amd64 1.11.2-0~xenial`

**Comment by fabiomontefuscolo** [comment]
I upgraded my Linode to Ubuntu 16.04 and docker stopped working. I was desperate, so I followed this tutorial: http://lukeberndt.com/2016/getting-docker-up-on-linode-with-ubuntu-16-04/.

After that, my Linode did not  even boot. I returned with original configuration and everything started to work magically, linode, docker engine and my containers. I really don't know why.

**Comment by brentjanderson** [comment]
@lillem4n Your instructions worked like a champ for me on 4.6.0-040600rc7-generic for running a hello world example.

**Comment by schors** [comment]
This issue also applies to docker version 1.12.0. The problem is that the package missing critical dependencies.  But this issue does not appears on the standard Ubuntu editions, because standart editions contains that.

Docker trying to activate graphdrivers with hardcoded priority at startup (file daemon/graphdriver/driver_linux.go - "aufs", "btrfs", "zfs", "overlay", "devicemapper", "vfs" ). But AUFS is not supported in standart Ubuntu kernels. Then Docker trying to setup devmapper graphdriver. Devmapper initialization depends on dmsetup utility. The installation hangs with messages above if dmsetup is absent. 

There are three ways to solve the issue.

1. Add to package dependencies list "linux-image-extra-$(uname -r)" (this package add aufs support) AND/OR "dmsetup" for Ubuntu Xenial package.
2. Patch docker source similar way native canonical package:

```
Description: move "overlay" to a higher priority (now that AUFS is not supported in Debian kernels)
Author: Tianon Gravi <tianon@debian.org>
Forwarded: no

diff --git a/daemon/graphdriver/driver_linux.go b/daemon/graphdriver/driver_linux.go
index 410a62f..eab78e7 100644
--- a/daemon/graphdriver/driver_linux.go
+++ b/daemon/graphdriver/driver_linux.go
@@ -48,8 +48,8 @@ var (
 		"aufs",
 		"btrfs",
 		"zfs",
-		"devicemapper",
 		"overlay",
+		"devicemapper",
 		"vfs",
 	}
```
 3. Redesign setup process to force graphdriver for different clean systems or something like that

**Comment by cpswan** [comment]
@schors great detective work - though this reveals a miserable lack of testing that a high profile release doesn't work on the latest version of one of the most popular distros

considering the the Docker team have been advocating overlay over AUFS for over a year it's a shame that their good advice hasn't yet made it into the code

**Comment by acejam** [comment]
I am surprised this issue hasn't been resolved yet. I can't speak for others, but I'm still deploying 14.04 host machines - at least they are trusty. 😄

**Comment by tiangolo** [comment]
For those of you running on Linode, @brentjanderson's instructions worked for me on a Ubuntu 16.04 as root user on a new Linode.

Namely:

* In a new Linode, update and upgrade packages:

```bash
apt-get update
apt-get upgrade -y
```

* Install and setup dmsetup:

```bash
apt-get install -y dmsetup
dmsetup mknodes
```

* Follow the [official installation instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

For example, as of now:

```bash
apt-get install apt-transport-https ca-certificates

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list

apt-get update
apt-get install -y docker-engine
service docker start
```

**Comment by lordnynex** [comment]
this is an extremely painful one that leaves apt in a very screwed up state

**Comment by jamesacampbell** [comment]
@tiangolo @lillem4n the dmsetup route worked like a charm. Really not that hard as long as you remember the few extra steps besides what is on docker's install guide on their website. thanks!

**Comment by niij** [comment]
I was getting the errors when trying to install docker-engine on Ubuntu 16.04 Xenial:

my fix was:
apt-get install dmsetup
dmsetup mknodes
#then follow the standard docker install process at [docker](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

**Comment by niij** [comment]
....also:

make sure you REBOOT your server after installing docker (it appears the devicemapper requires a reboot to work correctly).

**Comment by grigio** [comment]
The bug is still present. Thanks @niij it fixed, no reboot needed

**Comment by bobiblazeski** [comment]
I was unable to install docker on kernel 4.7 no matter what I tried. I installed kernel 4.8.5 and installation went without a problem.

**Comment by equivalent** [comment]
this worked for me http://stackoverflow.com/a/37640824/473040

https://docker.github.io/engine/admin/systemd/


#### 1. create a new file `/etc/systemd/system/docker.service.d/overlay.conf` with the following content:

````
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -s overlay
```

#### 2. flush changes by executing:
`sudo systemctl daemon-reload`

#### 3.verify that the configuration has been loaded:
`systemctl show --property=ExecStart docker`

#### 4. restart docker:
`sudo systemctl restart docker`

**Comment by thaJeztah** [comment]
docker 1.13 will prioritize overlay and overlay2 over devicemapper, which should resolve this issue on recent kernels

**Comment by GillesJ** [comment]
This is still an issue for me. None of the above suggestions work, I have tried each one except restarting the server which is not an option.

Initially docker-ce install hanged when `apt-get upgrade`ing.

I am at a loss here, any suggestions are welcome.

Ubuntu 16.04 Bare metal
Kernel: 4.4.0-72-generic

**Comment by thaJeztah** [comment]
Closing this, because of my previous comment, and we didn't get new reports of this for a while. If you're running into this problem, please open a new issue with details

**Comment by mihai-dinu** [comment]
If anyone else has this problem, what fixed it for me was:
1. Remove any docker.service files from `/etc/systemd/system/` (e.g. /etc/systemd/system/docker.service.d/docker.conf) 
2. `sudo dpkg --configure -a`
3. `sudo apt-get install --reinstall docker-ce`
