### ISSUE TITLE
Flaky test: TestServiceUpdatePort on s390

### ISSUE THREAD

**Issue by tophj-ibm** [moby/moby#26601]
Seen failing on ppc64le: https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/1621/consoleFull

``` sh
FAIL: docker_cli_service_update_test.go:13: DockerSwarmSuite.TestServiceUpdatePort

[d14d89bed3a59] waiting for daemon to start
[d14d89bed3a59] daemon started
docker_cli_service_update_test.go:22:
     waitAndAssert(c, defaultReconciliationTimeout, d.checkActiveContainerCount, checker.Equals, 1)
docker_utils.go:1535:
     c.Assert(v, checker, args...)
 ... obtained int = 0
 ... expected int = 1

 [d14d89bed3a59] exiting daemon

```

It doesn't fail if run by itself, but does fail if run with the entire DockerSwarmSuite.

**Comment by tophj-ibm** [comment]
this seems to failing consistently on 16.04 machines and not at all on 14.04 machines

**Comment by thaJeztah** [comment]
I've seen some network related bug-reports that seemed to indicate that Ubuntu 16.04 was involved.

ping @mrjana do you recall what that issue was - could it be related?

**Comment by tophj-ibm** [comment]
Guess it's not 16.04 related, because It's now failing on x86 14.04 & aufs master as well. https://jenkins.dockerproject.org/job/Docker%20Master/6843/label=ubuntu-1404%20&&%20aufs/consoleFull

**Comment by xiaods** [comment]
@tophj-ibm do you know howto reproduce the specified func in make test

**Comment by xiaods** [comment]
got it. 

```
TESTFLAGS='-check.f DockerSwarmSuite.TestServiceUpdatePort*' make test-integration-cli
```

**Comment by aaronlehmann** [comment]
ping @mrjana

**Comment by aluzzardi** [comment]
Is this still happening?

**Comment by tophj-ibm** [comment]
Haven't seen it in a couple of days, but still doing some more tests over on jenkins https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/. It's possible it was fixed in one of the vendors so I'll close this for now, and if I see it happen again I'll reopen this.

**Comment by dnephin** [comment]
I'm still seeing these failures pretty regularly on master builds, so going to reopen this.

**Comment by LK4D4** [comment]
Yup, I saw this today too. Looks quite serious. Ping @mrjana

**Comment by aluzzardi** [comment]
@mrjana if it's not happening again could you close this down?

**Comment by aluzzardi** [comment]
@dnephin Have you seen this lately?

**Comment by dnephin** [comment]
There are a couple recent failures on arm master, one from today. Nothing recent on non-arm

**Comment by tophj-ibm** [comment]
I uploaded the docker.log from a failing test here https://gist.github.com/tophj-ibm/bc0c53c9a85758e2de9c3125ecdc6f4a. I can see various tasks trying to start and then proceed to fail, but I'm not entirely sure what I'm looking at yet. Comparing against a passing version and those failures aren't there.

```sh
time="2016-10-20T20:47:43.597166000Z" level=debug msg="task status updated" method="(*Dispatcher).processTaskUpdates" module=dispatcher state.transition="PREPARING->STARTING" task.id=70i16jtn2aebpqgi7kaw9hwm7 
time="2016-10-20T20:47:43.607342000Z" level=error msg="fatal task error" error= module=taskmanager task.id=70i16jtn2aebpqgi7kaw9hwm7 
time="2016-10-20T20:47:43.607495000Z" level=debug msg="state changed" module=taskmanager state.desired=RUNNING state.transition="STARTING->FAILED" task.id=70i16jtn2aebpqgi7kaw9hwm7 
```

**Comment by aluzzardi** [comment]
@tophj-ibm I went back a couple of weeks on Jenkins (https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/) and don't see any failures related to this.

Can you confirm?

/cc @mrjana

**Comment by tophj-ibm** [comment]
@aluzzardi I haven't seen it failing on power since I posted the log 12 days ago. I just checked the past couple of days for arm, z and master and I don't see it anywhere either.

**Comment by tophj-ibm** [comment]
@aluzzardi actually, I'm able to recreate this locally on x86_64 with 
```sh
BUILDFLAGS="-race" TESTFLAGS='-check.f TestServiceUpdatePort -test.count 10' make test-integration-cli
```

**Comment by tophj-ibm** [comment]
nevermind, that was docker on mac issue with aufs, I can't recreate the issue.

I'm going to close this as I just checked jenkins again and don't seen it failing anywhere. If you see it, or can reproduce this, feel free to open again.

**Comment by michael-holzheu** [comment]
This test also fails from time to time on s390:

```
$ grep DockerSwarmSuite.TestServiceUpdatePort * | grep FAIL
0905:FAIL: docker_cli_service_update_test.go:13: DockerSwarmSuite.TestServiceUpdatePort
0908:FAIL: docker_cli_service_update_test.go:13: DockerSwarmSuite.TestServiceUpdatePort
1144:FAIL: docker_cli_service_update_test.go:14: DockerSwarmSuite.TestServiceUpdatePort
1182:FAIL: docker_cli_service_update_test.go:14: DockerSwarmSuite.TestServiceUpdatePort
1317:FAIL: docker_cli_service_update_test.go:14: DockerSwarmSuite.TestServiceUpdatePort 
```

Last failure: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/1317/console

**Comment by thaJeztah** [comment]
Let me reopen the issue

**Comment by vdemeester** [comment]
I see still some `TestSwarmPublishDuplicatePorts` flakyness, but not this one, I'll close until we see it again 😓

**Comment by michael-holzheu** [comment]
The problem is back on s390 (Apr 3, 2017): https://jenkins.dockerproject.org/job/Docker%20Master%20(s390x)/2320/consoleFull

```
09:09:22 FAIL: docker_cli_service_update_test.go:14: DockerSwarmSuite.TestServiceUpdatePort
..
09:09:22 docker_cli_service_update_test.go:23:
09:09:22     waitAndAssert(c, defaultReconciliationTimeout, d.CheckActiveContainerCount, checker.Equals, 1)
09:09:22 docker_utils_test.go:872:
09:09:22     c.Assert(v, checker, args...)
09:09:22 ... obtained int = 0
09:09:22 ... expected int = 1
```
This time it failed together with `TestSwarmPublishDuplicatePorts` from #30427.

**Comment by vdemeester** [comment]
😓

**Comment by michael-holzheu** [comment]
Looks like that for both `TestSwarmPublishDuplicatePorts` and `TestServiceUpdatePort` a `docker service create` command runs into the defaultReconciliationTimeout.

**Comment by michael-holzheu** [comment]
Any idea how to debug this issue?

**Comment by aaronlehmann** [comment]
Since the container doesn't start up before the timeout, I'd guess it fails to start up for some reason. My hunch would be that the port is already in use, perhaps leaked by another test. I remember this came up in #30219, and `TestSwarmPublishDuplicatePorts` was switched to use different ports as a workaround. However, I don't see any other tests that use ports 5005 or 5006. pinging @tonistiigi, who added the workaround, in case he has any ideas.

**Comment by tophj-ibm** [comment]
@michael-holzheu have you seen any recent failures on this one or should I close it?

**Comment by michael-holzheu** [comment]
> @michael-holzheu have you seen any recent failures on this one or should I close it?

```
$ grep -w "^FAIL:" * | grep TestServiceUpdatePort
2020:FAIL: docker_cli_service_update_test.go:14: DockerSwarmSuite.TestServiceUpdatePort
```

Like with [TestSwarmPublishDuplicatePorts](https://github.com/moby/moby/issues/30427#issuecomment-301800612)  the last failure was with PR build 2020. 

``
`$ grep -w "^FAIL:" * | grep TestSwarmPublishDuplicatePorts 
2020:FAIL: docker_cli_swarm_test.go:1724: DockerSwarmSuite.TestSwarmPublishDuplicatePorts
``

So probably we can also close this one.

**Comment by thaJeztah** [comment]
Thanks for checking :+1: i'll close for now
