### ISSUE TITLE
COPY fails intermittently no such file or directory

### ISSUE THREAD

**Issue by DTHompson55** [moby/moby#27134]
**Description**
COPY command in Dockerfile fails intermittently with no such file or directory

**Steps to reproduce the issue:**
1. docker build -t dthompson55/mosquitto .
2. Dockerfile contains: COPY docker-entrypoint.sh /
3. Filesystem contains: -rwxrwxr-x 1 dant dant 30 Oct 3 11:50 docker-entrypoint.sh

**Describe the results you received:**
 ---> 7be6a723492a
 Step 5 : COPY docker-entrypoint.sh /
 stat /var/lib/docker/aufs/mnt/5c714d1adb30f1366a6d12a49bc6529b88cb2887e71cf640a5daa5e989dac4ea/docker-entrypoint.sh: no such file or directory

**Describe the results you expected:**

I expected it to copy the file into the build context.

**Additional information you deem important (e.g. issue happens only occasionally):**

The build works a few times, and then fails. Once it fails I can't get it to work again.  If I reinstall everything on a clean ubuntu image then it works again, for a while.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: dant-VirtualBox
ID: WMSY:GBWI:IODG:ZZJK:2UVM:HB7D:PRRW:R6HZ:TIFO:6PVL:JANB:EP5N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dthompson55
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox running Ubuntu client

**Comment by brendandburns** [comment]
I hit this as well, restarting the daemon fixed things...

**Comment by bastih** [comment]
We downgraded to 1.11 for the moment to work around this issue, because it kept breaking our builds.

**Comment by tonistiigi** [comment]
Can you retry with master build? The error reporting was wrong and always reported stat error. That was fixed in #27075

**Comment by dennis-bell** [comment]
This also occurs in combination with GitHub, Dockerhub and automated build. 
Also see this linke [Docker Forums link](https://forums.docker.com/t/automated-docker-build-fails/22831/3)

Also see: #27233

**Comment by mikedougherty** [comment]
In my experience this happens when adding a file to `/`. 

Add a file to not-root works correctly:
```
$ cat root-file.txt
$ cat Dockerfile
FROM alpine

COPY root-file.txt /tmp/
$ docker build -t test .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM alpine
 ---> ee4603260daa
Step 2 : COPY root-file.txt /tmp/
 ---> 3feac84a371c
Removing intermediate container 837a5749b9ff
Successfully built 3feac84a371c
```

Adding the same file to `/` fails as mentioned above:
```
$ cat Dockerfile
FROM alpine

COPY root-file.txt /
$ cat root-file.txt
$ docker build -t test .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM alpine
 ---> ee4603260daa
Step 2 : COPY root-file.txt /
stat /var/lib/docker/aufs/mnt/ca7d67bfde380c9f99e7aecc460e913fdc897bfa2cc01f9f1f557be3b0867224/root-file.txt: no such file or directory
```


---
My info and version:

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 18
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-10-7-31-190
ID: 52UX:KFYO:65GG:6EQI:GQI5:QZ3Q:LZT4:S6BQ:KTV3:FLD3:CG4Y:EH6W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dockerbuildbot
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment]
@mikedougherty so this could be a duplicate of https://github.com/docker/docker/issues/25925 ?

**Comment by mikedougherty** [comment]
@thaJeztah ah yes indeed. that's consistent with what i'm seeing.

**Comment by thaJeztah** [comment]
Is anyone still having this issue on a current version of docker (17.03 or up)? From the linked issue, I see several improvements have been made to resolve similar issues

**Comment by xtrasimplicity** [comment]
@thaJeztah I was having this issue with v1.13, upgraded to 17.03 and it seems to have gone away. :)

**Comment by RomanKrasavtsev** [comment]
I have the same problem.

```
docker build ruby
Sending build context to Docker daemon   2.56kB
Step 1/18 : FROM ubuntu
 ---> d355ed3537e9

...

Step 6/18 : ADD id_rsa /root/.ssh/
ADD failed: stat /var/lib/docker/tmp/docker-builder261253629/id_rsa: no such file or directory
```
### docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

### docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 21
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: TQEU:K5VY:BBCD:IMUV:7XYO:AB6P:JFJM:3RWM:UPWN:K4QN:ZGIZ:YTOV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 29
 System Time: 2017-07-02T16:24:44.843017955Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
thanks @xtrasimplicity 

Closing this as this issue should be resolved in docker 17.03 and up; if you are encountering this issue in more recent versions, please open a new issue with details

**Comment by DarthNato** [comment]
Hello!

Im still having this issue.

The content of my dockerfile:

```
FROM httpd:2.4
COPY /work/local.txt /usr/local/apache2/htdocs/
```

Command: `docker build -t my-img`
```
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM httpd:2.4
 ---> b1e597b50dd7
Step 2/2 : COPY /work/local.txt /usr/local/apache2/htdocs/
COPY failed: stat /var/lib/docker/tmp/docker-builder023567111/work/local.txt: no such file or directory
```

docker info:
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 2
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: EJD3:L2IB:AO52:PRTN:JO4R:B3BE:BRFH:2AHS:AKRX:TK3N:IGY5:3A3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-07-10T14:40:00.701695964Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Restarting docker daemon did not work, neither restarting my 
```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 2
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: EJD3:L2IB:AO52:PRTN:JO4R:B3BE:BRFH:2AHS:AKRX:TK3N:IGY5:3A3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-07-10T14:40:00.701695964Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Keep in mind that source paths in `COPY` and `ADD` Dockerfile instructions are relative to the _build context_. So if you run

```bash
docker build -t foo .
```

The trailing `.` indicates the current directory; that directory is used as build-context, and sent to the docker daemon to use for the build.

What does your local directory look like? `COPY /work/local.txt` looks for a file named `local.txt` in the current directory, so if it's missing, it fails:

```bash
$ mkdir repro-27134 && cd repro-27134

$ cat > Dockerfile -<<EOF
FROM httpd:2.4
COPY /work/local.txt /usr/local/apache2/htdocs/
EOF

$ docker build -t repro-27134 .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM httpd:2.4
 ---> b1e597b50dd7
Step 2/2 : COPY /work/local.txt /usr/local/apache2/htdocs/
COPY failed: stat /var/lib/docker/tmp/docker-builder333585158/work/local.txt: no such file or directory
```

However, after creating the file;

```bash
$ mkdir work
$ echo "foobar" > work/local.txt
```

Building works;

```bash
$ docker build -t repro-27134 .

Sending build context to Docker daemon  3.584kB
Step 1/2 : FROM httpd:2.4
 ---> b1e597b50dd7
Step 2/2 : COPY /work/local.txt /usr/local/apache2/htdocs/
 ---> 1759bd85fdf5
Removing intermediate container ad7b5df444f8
Successfully built 1759bd85fdf5
Successfully tagged repro-27134:latest
```

**Comment by RomanKrasavtsev** [comment]
I had the same problem and it doesn't work with full path, but it works with the current directory where you build the image with Dockerfile. Yes, we have workaround, but issue still exists.

**Comment by DarthNato** [comment]
That was it... Thanks!!

**Comment by thaJeztah** [comment]
> it doesn't work with full path, but it works with the current directory where you build the image with Dockerfile. Yes, we have workaround, but issue still exists.

It's not workaround. `COPY` does not take an absolute path. The `COPY` command is designed to take a [path relative to the (inside the) build context](https://docs.docker.com/engine/reference/builder/#copy). Otherwise the Dockerfile would depend on the location where it's built from, e.g. on my machine I would have to use `COPY /users/sebastiaan/projects/project-foo/work/local.txt` but that path won't exist for other people.

**Comment by ganeshbms** [comment]
I still see this issue with Docker version 17.09.0-ce, build afdb6d4 ..

**Comment by dhdanno** [comment]
I believe i just hit this with ```Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c```

**Comment by thaJeztah** [comment]
@ganeshbms @dhdanno the issue discussed here was fixed; if you think you're running into this; please open a new issue instead with the details asked for in the issue template; be sure to show the exact steps to reproduce, to exclude possible errors in your Dockerfile or setup

**Comment by thaJeztah** [comment]
I'm locking the conversation on this issue to prevent possibly unrelated issues being added here; see my comment above if you think you're running into this issue
