### ISSUE TITLE
Windows - 'docker pull microsoft/nanoserver' - ProcessBaseLayer: The parameter is incorrect

### ISSUE THREAD

**Issue by jonstelly** [moby/moby#27527]
**Description**

I'm getting the same error on two machines (One Windows 10 build 14931, the other is Windows Server 2016 RTM).  I have a few other machines where I do not get these errors.

Pulling microsoft/nanoserver image gets error:

> exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\[guid]: The parameter is incorrect.

**Steps to reproduce the issue:**
1. Install latest Docker per MSDN instructions [here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)
2. Execute step with 'docker pull microsoft/nanoserver
3. Get above error

**Describe the results you received:**
The image fails to extract, not listed in 'docker images'

**Describe the results you expected:**
Image to download, be available

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `dockerd -D` during pull:**

```
time="2016-10-18T23:40:16.545940700-05:00" level=debug msg="Calling GET /v1.25/info"
time="2016-10-18T23:40:16.550805600-05:00" level=debug msg="Calling POST /v1.25/images/create?fromImage=microsoft%2Fnanoserver&tag=latest"
time="2016-10-18T23:40:16.550805600-05:00" level=debug msg="Trying to pull microsoft/nanoserver from https://registry-1.docker.io v2"
time="2016-10-18T23:40:16.989814300-05:00" level=debug msg="Increasing token expiration to: 60 seconds"
time="2016-10-18T23:40:17.230586700-05:00" level=debug msg="Pulling ref from V2 registry: microsoft/nanoserver:latest"
time="2016-10-18T23:40:17.657121600-05:00" level=debug msg="pulling blob \"sha256:94b4ce7ac4c7c7d4ed75ac2bd9359a87204ad2d5a909759d8e77953874d8e7c2\""
time="2016-10-18T23:40:17.657121600-05:00" level=debug msg="pulling blob \"sha256:5496abde368a3dd39999745bf998c877ddc6a390a943bc3fd99ffaabf728ed88\""
time="2016-10-18T23:40:17.660789600-05:00" level=debug msg="Pulling sha256:94b4ce7ac4c7c7d4ed75ac2bd9359a87204ad2d5a909759d8e77953874d8e7c2 from foreign URL https://go.microsoft.com/fwlink/?linkid=830395"
time="2016-10-18T23:40:17.661800100-05:00" level=debug msg="Pulling sha256:5496abde368a3dd39999745bf998c877ddc6a390a943bc3fd99ffaabf728ed88 from foreign URL https://go.microsoft.com/fwlink/?linkid=830191"
time="2016-10-18T23:40:24.504368600-05:00" level=debug msg="Downloaded 94b4ce7ac4c7 to tempfile C:\\Users\\me\\AppData\\Local\\Temp\\GetImageBlob477680239"
time="2016-10-18T23:40:39.512208900-05:00" level=debug msg="Downloaded 5496abde368a to tempfile C:\\Users\\me\\AppData\\Local\\Temp\\GetImageBlob598086402"
time="2016-10-18T23:40:39.512708900-05:00" level=debug msg="hcsshim::CreateLayer Flavour 1 ID f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27 parent "
time="2016-10-18T23:40:39.515208700-05:00" level=debug msg="hcsshim::CreateLayer  - succeeded id=f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27 parent= flavour=1"
time="2016-10-18T23:40:54.593270700-05:00" level=debug msg="Cleaning up layer f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27: re-exec error: exit status 1: output: ProcessBaseLayer C:\\ProgramData\\docker\\windowsfilter\\f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27: The parameter is incorrect."
time="2016-10-18T23:40:54.593755800-05:00" level=debug msg="hcsshim::DestroyLayer Flavour 1 ID f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27"
time="2016-10-18T23:40:57.624805000-05:00" level=debug msg="hcsshim::DestroyLayer succeeded flavour=1 id=f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27"
time="2016-10-18T23:40:57.631897800-05:00" level=error msg="Error trying v2 registry: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\\ProgramData\\docker\\windowsfilter\\f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27: The parameter is incorrect."
time="2016-10-18T23:40:57.631897800-05:00" level=error msg="Attempting next endpoint for pull after error: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\\ProgramData\\docker\\windowsfilter\\f9a89de80f3d37554b8cf2188edf530ee3804649e46cf423a0446d7284845e27: The parameter is incorrect."
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   cd0e399
 Built:        Mon Oct 17 23:06:56 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   cd0e399
 Built:        Mon Oct 17 23:06:56 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.89 GiB
Name: srv
ID: SWVX:62AL:DNL7:I4YB:KKID:EE3X:ODHW:O4LI:KZ3H:BAYB:TYG2:YHSM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machines

**Comment by jhowardmsft** [comment]
Yes, we think we know what this is, a race condition in Windows itself. We're tracking a potential servicing fix, but no ETA yet. (Internal bug# 9386083). On some machines, re-trying makes it work, although I've seen one machine where it just never succeeds after multiple (10+) retries.

**Comment by jhowardmsft** [comment]
@swernli FYI

**Comment by jonstelly** [comment]
If it is a race condition, I've got a machine we can test a fix on.  I ran the following: 50 attempts and 50 failures.

`foreach($i in 1..50) { Write-Host "PULLING..."; $output = docker pull microsoft/nanoserver; if($LASTEXITCODE -eq 0) { Write-Host -ForegroundColor Green 'SUCCESS'; exit; } else { Write-Host -ForegroundColor Red "FAILURE($i): $LASTEXITCODE"; } }`

**Comment by jhowardmsft** [comment]
@darrenstahlmsft Pretty sure we can close this now with the workaround in docker. Can you confirm.

**Comment by darrenstahlmsft** [comment]
@jhowardmsft Are you thinking of https://github.com/docker/docker/issues/27588? I'm not aware of any workarounds that we can do for this bug. It needs a platform fix.

Since this is a Windows bug, not a Docker bug, should we close it anyway though?

**Comment by penenkel** [comment]
Is there any news on this issue? Does a fix or workaround exist? 
@jhowardmsft @darrenstahlmsft

**Comment by jhowardmsft** [comment]
Sorry, yes, thinking of wrong issue. Can you give the VSO# tracking this. Not sure there's a lot we can do on github as it's a platform issue.

**Comment by thesandbender** [comment]
Anywhere we can track the MSFT issue?  I'm in the same boat as jonstelly, it always fails.

**Comment by penenkel** [comment]
Are you sure that it is indeed a race condition? For me it always fails, same as thesandbender and jonstelly.
Is there any way for me to collect more information to help identifying the problem?

**Comment by darrenstahlmsft** [comment]
@penenkel We have a fix internally, but don't have an ETA for a Windows Update that includes it yet. We're not aware of any workaround at this time, but if we can get specs of the systems encountering this, it might help. Could you post specs here? I'm mostly interested in hard drive specs, ideally benchmarks, but anything might help.

@thesandbender I'm not aware of a way to track this yet. I'm following up with some internal folks to see what we can do about getting a way to track this.

@jhowardmsft VSO# 9386083

/cc @swernli @patricklang FYI

**Comment by jonstelly** [comment]
If it helps, Mushkin Reactor 1TB drive:

![image](https://cloud.githubusercontent.com/assets/967068/20332450/8505c1cc-ab71-11e6-98c0-b26f2cf09412.png)

**Comment by viebrock** [comment]
I also have this issue.  i'm able to install docker successfully, but am unable to pull or run any container.  according to windows update, my OS is fully updated (WS2016 RTM).

here's my info:
[environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

I've tried 2 different versions of docker.  here's the one i get from PSGallery:
PS C:\Windows\system32> docker version
Client:
Version: 1.12.2-cs2-ws-beta
API version: 1.25
Go version: go1.7.1
Git commit: 050b611
Built: Tue Oct 11 02:35:40 2016
OS/Arch: windows/amd64
 
Server:
Version: 1.12.2-cs2-ws-beta
API version: 1.25
Go version: go1.7.1
Git commit: 050b611
Built: Tue Oct 11 02:35:40 2016
OS/Arch: windows/amd64

As well, I've download 1.12.3 binaries, used them to replace the PSGallery docker binaries,  restarted the service, and I have this version:
PS C:\Windows\system32> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: overlay null nat
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3.997 GiB
Name: A0864T132
ID: 27MH:C6TO:MZOD:N6PD:U2ZF:LAVK:FIUS:G7MZ:5236:5LLS:63P2:SHTL
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://webproxysea:8181/
Username: daveviebrock
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

Neither version works to pull or run a container, both in powershell or CMD sessions.

Is there a list of recommended hotfixes or patches that I should be installing?

**Comment by mkracik** [comment]
It happens always on my computer. Disk is OWC Mercury Pro 6G 480 GB (SandForce), fully updated release Windows 10 Pro Anniversary Edition.

![image](https://cloud.githubusercontent.com/assets/17297517/20737149/0914aa8e-b679-11e6-87d2-f3237e092483.png)

PS C:\Users\Michal> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
5496abde368a: Extracting [==================================================>] 242.6 MB/242.6 MB
482ab31872a2: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\9de
834c852606d11099110fec029b28eaae5eca0b51535bfb6df84ba17c29fe8: The parameter is incorrect.
PS C:\Users\Michal> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92 GiB
Name: AAAAA
ID: USYI:QTID:3WJZ:LCYL:WKL6:BPBR:PCCZ:NIBH:ZRW5:VLIU:CHZE:LBRR
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by swernli** [comment]
We are still in the process of getting the workaround in Windows into a servicing update, but in the meantime we have one customer who is reporting success on a machine that was previously failing by following specific steps.  Unfortunately, it would require reinstalling Windows RTM to get it into a fresh state.  If anyone has a machine that they are willing to try this on, it could help confirm that these instructions successfully avoid the issue.

Here are the steps he took:
1.  Deploy an Windows Server 2016 RTM image (NOTE: this may also work for Windows client, but this customer has not tried that).  DO NOT RUN WINDOWS UPDATE YET.
2. Install the following patches:
    a.	http://www.catalog.update.microsoft.com/Search.aspx?q=KB3176936
    b.	http://www.catalog.update.microsoft.com/Search.aspx?q=KB3192366
3. Enable the container feature, including reboot.
4. Install Docker client and daemon.
5. Run full Windows Update to get the system up to date.

In his case, these steps, specifically the two patches before the containers feature is enabled and the rest of the updates delayed until afterward, allowed docker pull to start working on the system where he previously hit this error.

Please let me know if these steps work for any of you.

**Comment by ankitbko** [comment]
Facing same issue. I am on win 10 Pro.

**Comment by louyihua** [comment]
I suspect the failure is caused by some long pathes that exceed the MAX_PATH limit.
So maybe the Unicode-based API should be used to prevent such limitation.

**Comment by darrenstahlmsft** [comment]
To anyone facing this issue, try installing patch [KB3216755](http://www.catalog.update.microsoft.com/Search.aspx?q=KB3216755).

**Comment by mkracik** [comment]
Thanks! After installing KB3216755 the issue is now fixed on both my computers. Unfortunately I am not sure if it's because KB3216755 or an earlier update KB3211320.

**Comment by lqbweb** [comment]
I have both KB3216755 and KB3211320 still fails. No antivirus or anything active:

C:\WINDOWS\system32>docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>] 252.7 MB/252.7 MB
3ac17e2e6106: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\8b27ed7e9cf766e4a877eb93f9c248f6d0c102c6e443d4480dec5d5d8dc26f3f: The parameter is incorrect.

C:\WINDOWS\system32>]

**Comment by louyihua** [comment]
KB3216755 also fixes the issues on my servers running Windows Server 2016

**Comment by lqbweb** [comment]
May be [this](https://github.com/golang/go/issues/15388), the reason?

Have that something to do?

I have been monitoring a "docker load" process with Process Monitor. After having read and close the .tar.gz file, the process seems kind of stuck, no cpu activity or anything. Then, suddenly, all threads die.

Could someone try to change [this](https://github.com/docker/docker/blob/master/cli/command/image/load.go), line 48, to be wrapped in a buffer io as the last guy in that issue proposes?

**Comment by keslerm** [comment]
This is also a blocker issue for me as well. Unfortunately putting a damper in us trying to test this technology for production use.

Not sure about why, but I was able to pull nanoserver, then a day later it started reporting that error. Nothing changed outside of me removing the image and re-trying the download.

**Comment by ankitbko** [comment]
Is there any update on this? This is really a blocker.

**Comment by darrenstahlmsft** [comment]
@ankitbko Can you confirm if you have installed the patch linked above?

**Comment by ankitbko** [comment]
@darrenstahlmsft Yes. I have installed KB3216755 and it still fails with below error. I am trying to pull microsoft/dotnet:1.1-sdk-msbuild-nanoserver

```
ERROR: Service 'web' failed to build: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\135969f90e4d918cb365b1323144fb8bb3eb41db8635646b2ba42d687bfd618a: The parameter is incorrect.
```

`docker version`
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Comment by darrenstahlmsft** [comment]
@ankitbko @lqbweb @kesarion I'm going to need some additional tracing to understand what is happening here. If you're willing to collect additional tracing, here are the instructions:

Download HcsTraceProfile.wprp, found in https://gist.githubusercontent.com/jhowardmsft/71b37956df0b4248087c3849b97d8a71 then run the following:

```
Wpr.exe -start HcsTraceProfile.wprp!HcsArgon -filemode

docker run microsoft/nanoserver

Wpr.exe -stop HcsTrace.etl "ProcessBaseLayer parameter is incorrect"
```

Note that the resulting HcsTrace.etl may contain personal information, such as path names accessed on the host, current running executables, etc, so I suggest sending it to me directly at darst@microsoft.com.

Additionally, [analytic logs](https://technet.microsoft.com/en-us/library/cc749492(v=ws.11).aspx) for `Applications and Services Logs/Microsoft/Windows/Hyper-V-Compute` might provide some insights without running a full trace.

**Comment by ankitbko** [comment]
@darrenstahlmsft I have sent you the logs over mail. Really appreciate you helping us out here.

**Comment by kumarbayar** [comment]
I am trying to pull nanoserver image through docker. where Base image is nanoserver(VM) installed on windows server 2016. Iam facing same error while pulling nanoserver image on nanoserver. The error information are as shown below

[192.168.0.125]: PS C:\> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Pulling fs layer
58f68fa0ceda: Pulling fs layer
58f68fa0ceda: Verifying Checksum
58f68fa0ceda: Download complete
bce2fbc256ea: Verifying Checksum
bce2fbc256ea: Download complete
docker : failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer
C:\ProgramData\docker\windowsfilter\d40bf894353b945934e1d8f325f5c6d732325c2676d07c2d93ea4b135a886000: This operation
returned because the timeout period expired.
    + CategoryInfo          : NotSpecified: (failed to regis...period expired.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

docker info are as shown below.

[192.168.0.125]: PS C:\> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.1
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1023 MiB
Name: nanoserver
ID: 4LPX:OJ5Z:EOMG:QMDN:IBZD:P5FO:QLGU:RWAO:KS5K:GDEA:43ST:7HXJ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by mcoakley** [comment]
I'm getting the same issue on a Windows 10 Creator Update system - fully updated.

```
PS C:> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

```
PS C:> docker pull microsoft/windowsservercore
Using default tag: latest
latest: Pulling from microsoft/windowsservercore
3889bb8d808b: Extracting [==================================================>]  4.07 GB/4.07 GB
503d87f3196a: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\4637df7bae6b5d9ae0053448da320a472494655d3ac647fa9506548cb293c4b0\UtilityVM: The process cannot access the file because it is being used by another pr
ocess.
```
Here is my docker info
```
PS C:> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.88 GiB
Name: XXXXXX
ID: UZQ6:R4NQ:SFN3:3CII:4GNL:TSSS:KP7J:Z47G:OYQH:SPXJ:6APR:M5EC
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-04-11T09:10:50.6031831-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

My main system drive is a LiteOn CV3-8D256 (256Gb SSD) w/Firmware: T886201.
![liteon-benchmark](https://cloud.githubusercontent.com/assets/1500989/24911780/21d75d94-1e9a-11e7-9ba2-227e776b019e.png)

**Comment by darrenstahlmsft** [comment]
@mcoakley Your issue looks different (`The process cannot access the file because it is being used by used by another process` instead of `The parameter is incorrect.`). I suspect anti-virus is (incorrectly) scanning the new VHD for the image. Can you open a new issue and link me?

**Comment by mcoakley** [comment]
@darrenstahlmsft you are correct ... I did not read the entire error - clearly. The information in the other thread was helpful. I also have Kapersky and no settings I tried helped. Uninstalling Kapersky and simply using Windows Defender allowed me to pull Windows images. Thank you for the heads up.

**Comment by artisticcheese** [comment]
Seeing this issue on Win10 as well (1607 fully patched). Was there an official resolution recorded for this issue?

**Comment by tabakerov** [comment]
Facing same issue with Docker CE 17.09.0-ce-win33 13620 on Windows 10 15063.540

> failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\d3475a87616db06c8d47e5a0280f0357fa367e1f36da3701fa817959f4583c65: The parameter is incorrect.

**Comment by artisticcheese** [comment]
@tabakerov Which AV are you using?

**Comment by ericdagenais** [comment]
Also facing the same issue with Windows 10 1703 15063.674, Docker CE Version 17.09.0-ce-win33 (13620). No 3rd party AV installed, disabled Defender, and Bitlocker is not turned on.

```
λ docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
b0b5e40cb939: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\a6fc4e13d0fb4a8ae116d0d3400b6781408383cd1aa4050ce23fc49b1d651eaa: The parameter is incorrect.
```

I ran Sysinternal's Procmon and saw a `FSCTL_ALLOW_EXTENDED_DASD_IO invalid parameter` on the docker process when this happened.

If I switch to Linux Containers, I can pull images without the above error.

**Comment by artisticcheese** [comment]
Is bitlocker or another disk encryption in place?

**Comment by ericdagenais** [comment]
No bitlocker nor other disk encryption is in place.

Some other info that may help:

My primary Windows startup disk is connected to an Intel sata raid controller running in raid mode via the "Intel Rapid Storage Technology enterprise" (Intel(R) C600+/C220+ series chipset SATA RAID Controller); startup disk is a Samsung SSD 850 EVO 1TB (no raid) and have a set of disks running in a RAID 5 volume. Motherboard is a Supermicro X10SAE Xeon workstation model.

**Comment by tabakerov** [comment]
@artisticcheese - no disk encription, installed Kaspersky Endpoint Security (required by corporate policy)
The issue is only with Windows containers, Linux containers are working fine

**Comment by artisticcheese** [comment]
Linux containers work differently then windows in Windows for obvious reasons. Issue most likely with AV blocking it, you'd have to ask your IT to diagnose disable your AV to test. Or alternatively check straight up with vendor if they support Windows containers, only some do.

**Comment by MacDennis76** [comment]
The solution as provided by @artisticcheese worked for me. See: https://github.com/docker/for-win/issues/737

I first disabled Windows Defender and then I enabled and disabled BitLocker. Only then I was able to pull & exact the image. This was on an updated Windows 10 Pro OS.

**Comment by ericdagenais** [comment]
@MacDennis76 I just tried the solution provided by @artisticcheese and can confirm it fixed the `The parameter is incorrect` error that prevented me from using Docker for Windows for several months. Thanks a lot

**Comment by timotei** [comment]
I also got the same issue, this is my config:

```
C:\Users\t>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.82GiB
Name: my-pc
ID: -- redacted --
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2017-11-28T23:41:45.568362+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


C:\Users\t>docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true

```

**Comment by SSvilen** [comment]
Just stumbled upon that problem - the problem was anti virus software.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
