### ISSUE TITLE
1.13-rc2 "removal of container already in progress" after upgrade from 1.12

### ISSUE THREAD

**Issue by taiidani** [moby/moby#29040]
I am receiving the following error when on 1.13-rc2 and directing a Docker host to build a container through the mounted Docker socket.
```
ERRO[0000] error removing container: Error response from daemon: removal of container ce0976ad22495c7cbe9487752ea32721a282164862db036b2f3377bd07461c3a is already in progress
```

**Steps to reproduce the issue:**

One file "Dockerfile-builder" for the container which will initiate the build:
```docker
FROM debian:jessie

RUN apt-get update && apt-get install -y \
        ca-certificates \
        curl \
    --no-install-recommends && rm -r /var/lib/apt/lists/*

# Set up Docker
RUN  set -x \
    && curl -fSL "https://test.docker.com/builds/Linux/x86_64/docker-1.13.0-rc2.tgz" -o docker.tgz \
    && tar -xzvf docker.tgz \
    && mv docker/* /usr/local/bin/ \
    && rmdir docker \
    && rm docker.tgz \
    && docker -v

ENTRYPOINT [ "docker" ]
```

One file "Dockerfile" for a simple image being built:
```docker
FROM debian:jessie
```

Build the builder, then use it to build the simple image along with the build context for that directory:
```bash
docker build -f Dockerfile-builder -t builder .
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD --workdir $PWD builder build -t example .
```

You may have to run the second command a couple times to encounter the error.

**Describe the results you received:**

```
Sending build context to Docker daemon 3.072 kB
Step 1/1 : FROM debian:jessie
 ---> 73e72bf822ca
Successfully built 73e72bf822ca
ERRO[0000] error removing container: Error response from daemon: removal of container ce0976ad22495c7cbe9487752ea32721a282164862db036b2f3377bd07461c3a is already in progress
```

**Describe the results you expected:**

```
Sending build context to Docker daemon 3.072 kB
Step 1/1 : FROM debian:jessie
 ---> 73e72bf822ca
Successfully built 73e72bf822ca
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Running this on:
* Docker Machine `Version: 0.9.0-rc1, build ed849a7`
* Installed as part of Docker for Mac `Version: 0.9.0-rc1, build ed849a7`
* macOS Sierra 10.12.1.

The virtual machine is VMWare Fusion `Version 8.5.2 (4635224)`.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 511
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 706
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
Kernel Version: 4.4.34-boot2docker
Operating System: Boot2Docker 1.13.0-rc2 (TCL 7.2); HEAD : 51fa426 - Wed Nov 23 20:08:44 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: default
ID: EZ5K:RZIJ:SLYL:Q4DX:H5JL:L76H:OROI:D2BL:S34W:45FX:DGSN:L6VN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-12-01T22:07:58.068629497Z
 EventsListeners: 0
Username: taiidani
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by taiidani** [comment]
Hmm, adding more context for the issue. The Docker Machine I am running on was upgraded from 1.12.3 to 1.13.0-rc2, so it may have picked up something from the upgrade.

Also, it turns out that my example is more complex than required. I can reproduce with a simple
```bash
docker run --rm debian:jessie echo hello world
```

**Comment by cpuguy83** [comment]
Hmm, sounds like this is from the autoremove handling.

**Comment by cpuguy83** [comment]
```
 Version:      1.13.0-rc2
 API version:  1.24
```

That seems to be the problem.

`API version` should be 1.25.

**Comment by cpuguy83** [comment]
@taiidani How did you get this docker client?

**Comment by taiidani** [comment]
@cpuguy83 It was part of an upgrade while troubleshooting an unrelated issue I was having: https://dockercommunity.slack.com/archives/general/p1480623931007599
* I had a mostly vanilla Docker Machine instance on v1.12.3; no modifications to the Docker configuration on the VM. Docker Machine was installed on my machine using the Docker for Mac stable client.
* I reinstalled Docker for Mac under the beta channel, then ran `docker-machine upgrade` on the VM to get it up to v1.13.0-rc2.
* The VM upgraded and restarted, then I immediately started running into the issues above.

I was hoping to get an export of the VM for troubleshooting purposes but it looks like the problem (somehow?) cleared itself up on its own. I don't remember even restarting the VM but the API Version is now 1.25 and I'm not able to reproduce the error anymore.

Here's the new dump of `docker version` and `docker info` if that helps at all. I'll leave the VM as untouched as I can in case you would like me to troubleshoot further.
```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 13
Images: 474
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 736
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.34-boot2docker
Operating System: Boot2Docker 1.13.0-rc2 (TCL 7.2); HEAD : 51fa426 - Wed Nov 23 20:08:44 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: default
ID: EZ5K:RZIJ:SLYL:Q4DX:H5JL:L76H:OROI:D2BL:S34W:45FX:DGSN:L6VN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 23
 System Time: 2016-12-02T13:52:10.31490289Z
 EventsListeners: 0
Username: taiidani
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
@vieux Any ideas? It seems like the 1.13 client negotiated (temporarily) api 1.24 with a 1.13 daemon (should be 1.25)

**Comment by MadMub** [comment]
Not sure if this is related but I was trying to play with 1.13 with --experimental to test out C/R. Running hello world (or any container) seems to give me a similar issue (cant copy paste text because was using Veertu which doesnt have copy paste yet)
<img width="1261" alt="screen shot 2016-12-14 at 10 04 49 pm" src="https://cloud.githubusercontent.com/assets/2809870/21210546/05bf84d0-c24a-11e6-91be-d6cd39cfb19f.png">

docker info

<img width="510" alt="screen shot 2016-12-14 at 10 10 26 pm" src="https://cloud.githubusercontent.com/assets/2809870/21210576/2ae2989c-c24a-11e6-8b19-7e662a7c359d.png">

**Comment by thaJeztah** [comment]
ping @vieux PTAL

**Comment by thaJeztah** [comment]
This is a way to reproduce;

```
DOCKER_API_VERSION=1.23 docker run --rm busybox sh -c 'echo hello world'
hello world
ERRO[0001] error removing container: Error response from daemon: removal of container 3954cd6faf07771b155df2b1d295383be9e04bebf2308c09a971079f7e98271c is already in progress
```

I think if API version < 1.25, `AutoRemove` should never be set, and the client should be responsible for removing the container, not the daemon

**Comment by thaJeztah** [comment]
Working on a possible patch

**Comment by thaJeztah** [comment]
After discussion with @nathanleclaire, it turns out that `docker machine env` with docker machine 0.9 sets `DOCKER_API_VERSION`. Since the docker machine was upgraded from 1.12 to 1.13, we suspect that the `DOCKER_API_VERSION` was still set to the original value for docker 1.12, hence the client connecting to the daemon using the 1.24 API version.

**Comment by MikeiLL** [comment]
i am using Docker for Mac:
```
Docker version 17.03.1-ce, build c6d412e
```

Had issue following installing a bunch of node modules and was getting:

```
ERROR: for my-wp  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
```

So tried ``docker rm -fv container_id_as_returned_by_docker_ps_command`` and waited about 5 minutes. Then I killed the process.

Tried a second time and got:

```
Error response from daemon: removal of container bf4a3bc2cfa0 is already in progress
```

Trying to restart Docker from the task bar and it's been "starting" for about 8 minutes now.

**Comment by MikeiLL** [comment]
i am using Docker for Mac:
```
Docker version 17.03.1-ce, build c6d412e
```

Had issue following installing a bunch of node modules and was getting:

```
ERROR: for my-wp  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
```

So tried ``docker rm -fv container_id_as_returned_by_docker_ps_command`` and waited about 5 minutes. Then I killed the process.

Tried a second time and got:

```
Error response from daemon: removal of container bf4a3bc2cfa0 is already in progress
```

Trying to restart Docker from the task bar and it's been "starting" for about 8 minutes now.

**Comment by MikeiLL** [comment]
Restarting the computer seems to have solved.

**Comment by taiidani** [comment]
@thaJeztah As this behavior hasn't occurred in any future upgrades, shall we close this? I feel like any reoccurrences probably would benefit from new issues being filed anyways.

**Comment by thaJeztah** [comment]
Yes, this issue should be fixed in docker 17.03.1 through https://github.com/moby/moby/pull/30113, and https://github.com/moby/moby/pull/31692, looks like I forgot to link it to this issue, thanks for the ping 👍

**Comment by garar** [comment]
Hi guys!

Is it possible that these fixes didn't go into 17.03.1?

I still see this problem happening a lot on 17.0.3.1-ce:

```
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
`
-bash-4.2$ host
host         hostid       hostname     hostnamectl  
-bash-4.2$ hostnamectl 
   Static hostname: 
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a79f22499e4344809ab65966c407f3f0
           Boot ID: c4eaf436df094c1fbf0fc6a7bd162a85
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.6.1.el7.x86_64
      Architecture: x86-64
```

**Comment by thaJeztah** [comment]
@garar if you have steps to reproduce, that would be helpful. Be aware that the community edition of Docker 17.03 has reached EOL, so updating to 17.06 or 17.09 would be recommended.
