### ISSUE TITLE
Cannot join a node after previously removing it

### ISSUE THREAD

**Issue by PatrickLang** [moby/moby#29286]
**Description**
I initially joined a Windows node to a swarm mode master running on Linux. Things worked ok, but I wanted to run `docker service` to create a service from the Windows node. I left the swarm, then tried to join again using the master key. 

I tried a few different things to fix it, none of them worked:
- `docker node rm ...` on Linux master. This changed the error from the rpc error to permission denied (see below)
- `docker swarm join-token --recycle` No change
- `docker init ...` to reinitialize the cluster. No change in behavior

**Steps to reproduce the issue:**
1. `docker swarm init` on Linux node
2. `docker join ...` on Windows node with worker key
3. `docker leave ...` on Windows node 
4. `docker node rm ...` to remove Windows node from Linux master
5. `docker join ...` on Windows node with master key

**Describe the results you received:**

```
PS C:\Users\patrick\master\MusicStore-master>  docker swarm join --token ... 10.0.0.10:2377
Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join
another one.
PS C:\Users\patrick\master\MusicStore-master> docker swarm leave
Node left the swarm.
```

I then removed the node from the master, and tried adding it:

```
PS C:\Users\patrick\master\MusicStore-master>     docker swarm join     --token ... 10.0.0.10:2377
Error response from daemon: can't initialize raft node: rpc error: code = 7 desc = Permission denied: unauthorized peer
role: rpc error: code = 7 desc = Permission denied: node npb0ng2w9iz27lhnmtgsvr1o6 was removed from swarm
```

**I tried to fix this by cycling the keys. No change**

Manager:
```
patrick@plang-v13-l:~$ docker swarm join-token --rotate manager
Successfully rotated manager join token.

To add a manager to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-49jm4viud3wq4w7vyxxv2zob6l78f4iidrp7ux2ba70twn5lo7-ekus743xun2wpxujei6hqp34f \
    10.0.0.10:2377

patrick@plang-v13-l:~$ docker swarm join-token --rotate worker
Successfully rotated worker join token.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-49jm4viud3wq4w7vyxxv2zob6l78f4iidrp7ux2ba70twn5lo7-6z29tt8wv2xexc7lg9ox6qad1 \
    10.0.0.10:2377

```

Worker:
```
PS C:\Users\patrick\master\MusicStore-master>     docker swarm join     --token SWMTKN-1-49jm4viud3wq4w7vyxxv2zob6l78f4i
idrp7ux2ba70twn5lo7-ekus743xun2wpxujei6hqp34f     10.0.0.10:2377
Error response from daemon: can't initialize raft node: rpc error: code = 7 desc = Permission denied: unauthorized peer
role: rpc error: code = 7 desc = Permission denied: node npb0ng2w9iz27lhnmtgsvr1o6 was removed from swarm
```

**I tried to fix this by reinitializing the swarm. No luck**

Manager:
```none
patrick@plang-v13-l:~$ docker swarm init --force-new-cluster
Swarm initialized: current node (iz6q2tviob6eilm18hdm2i5yj) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token ... \
    10.0.0.10:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

patrick@plang-v13-l:~$ docker swarm join-token manager
To add a manager to this swarm, run the following command:

    docker swarm join \
    --token ... \
    10.0.0.10:2377
```

Worker node
```
PS C:\Users\patrick\master\MusicStore-master>     docker swarm join     --token ...     10.0.0.10:2377
Error response from daemon: can't initialize raft node: rpc error: code = 7 desc = Permission denied: unauthorized peer
role: rpc error: code = 7 desc = Permission denied: node npb0ng2w9iz27lhnmtgsvr1o6 was removed from swarm
```

**Describe the results you expected:**
I would have expected my first attempt to join the cluster as a manager to succeed

**Output of `docker version`:**

```
patrick@plang-v13-l:~$ docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
patrick@plang-v13-l:~$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.13.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: iz6q2tviob6eilm18hdm2i5yj
 Is Manager: true
 ClusterID: em9ruw7r35umshccoydxesrgu
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.10
 Manager Addresses:
  10.0.0.10:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.359 GiB
Name: plang-v13-l
ID: EKON:4RK4:6MF3:YB5P:DP4K:XDEV:GDD3:OGUK:TUXN:34U6:2SIZ:JP5E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

```
PS C:\Users\patrick\master\MusicStore-master> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 15
Server Version: 1.13.0-rc3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: plang-v13-win
ID: GBCF:6HCI:JXSN:WXDG:K366:SYWB:AEB5:T66E:5WPK:THYW:7ZOP:VZGU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Both are VMs running on Azure

**Comment by PatrickLang** [comment]
@tonistiigi - Could this be somehow related to the changes you made for  https://github.com/docker/docker/issues/28490 ?

**Comment by tonistiigi** [comment]
If I get it correctly that the manager never started then I don't think it's related. `could not connect to prospective new cluster member using its advertised address: rpc error: code = 4 desc = context deadline exceeded` seems to point that the advertised address for the manager wasn't correct. Maybe we don't have very good automatic detection in windows although I think in normal cases it should give a different error. If this is the problem then `--advertise-addr` can be used on join to manually override it. If it only happens after leaving the worker then it could be related though.

@johnstep Have you by any chance tested cross platform swarm managers.

cc @aaronlehmann

**Comment by PatrickLang** [comment]
You're right about the rpc error. Somehow my firewall exclusions got reset. I'll strike that dead lead from the first post. I double checked and set up a 3rd node which got past the rpc error 4 as well.

The node I removed is still stuck at:

```
Error response from daemon: can't initialize raft node: rpc error: code = 7 desc = Permission denied: unauthorized peer
role: rpc error: code = 7 desc = Permission denied: node npb0ng2w9iz27lhnmtgsvr1o6 was removed from swarm
```

**Comment by tonistiigi** [comment]
@PatrickLang If you have removed the node with `node rm` you have to `docker swarm leave` it and join again.

**Comment by johnstep** [comment]
@tonistiigi No, I have not tried cross platform swarm like this.

**Comment by PatrickLang** [comment]
@tonistiigi I did `docker swarm leave` before `docker node rm` - I just clarified the steps above

**Comment by tonistiigi** [comment]
@PatrickLang The new error indeed seems related, but it can't happen exactly like it is descibed in here. `swarm leave` should have finished with an error in the first attempt. This problem should be fixed by https://github.com/docker/docker/pull/28907 but it isn't included in `v1.13-rc3`. The workaround is to remove `{docker-storage-dir}/swarm` (if `swarm leave` again gives an error about the node not being part of swarm).

**Comment by uday31in** [comment]
I still have the same issue

docker : {"level":"debug","msg":"In windows NewClient","time":"2017-02-01T10:19:27-08:00"}
    + CategoryInfo          : NotSpecified: ({"level":"debug...0:19:27-08:00"}:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

{"level":"debug","msg":"Generating mock docker/docker client","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Inspecting desired and current node config","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Obtaining docker info","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Detected node CN via cert as: sbkldvw5ryvkbiiph6jiyxpsa","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Using swarm defined host address localhost","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"This swarm has the following managers: [10.123.144.40]","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Desired Node Config:
\u0026types.NodeConfig{ClusterConfig:types.ClusterConfig{ControllerPort:443, SwarmPort:2376, SwarmStrategy:\"spread\",
ImageVersion:\"2.1.0-tp1\", UCPInstanceID:\"removed\",
DNS:[]string{}, DNSOpt:[]string{}, DNSSearch:[]string{}, KVTimeout:5000, KVSnapshotCount:20000,
ProfilingEnabled:false, Uninstall:false, ExternalServiceLB:\"\", MetricsRetentionTime:\"24h0m0s\",
DTRHostAddress:\"\", DTRCAHash:\"\"}, NodeID:\"sbkldvw5ryvkbiiph6jiyxpsa\", IsManager:false, NodeCertExpiry:0,
CertsNeedRegen:false, CertsNeedPermissionsUpdate:false, HostAddress:\"localhost\", Hostname:\"\",
SANs:[]string{\"127.0.0.1\", \"localhost\", \"localhost\", \"\",
\"l42m-lruj-uirq-msjn-hmuc-f5js-6j2y-yjec-pmiq-s45e-r62m-3axn\"}, Managers:[]string{\"10.123.144.40\"},
ClusterCASigningURLs:[]string{\"https://10.123.144.40:12381/api/v1/cfssl/sign\"},
Containers:map[string]*types.OrcaContainer{\"ucp-cluster-root-ca\":(*types.OrcaContainer)(0xc042225480),
\"ucp-auth-api\":(*types.OrcaContainer)(0xc042225680), \"ucp-auth-worker\":(*types.OrcaContainer)(0xc042225700),
\"ucp-controller\":(*types.OrcaContainer)(0xc042225780), \"ucp-client-root-ca\":(*types.OrcaContainer)(0xc042225400),
\"ucp-kv\":(*types.OrcaContainer)(0xc042225500), \"ucp-auth-store\":(*types.OrcaContainer)(0xc042225580),
\"ucp-swarm-manager\":(*types.OrcaContainer)(0xc042225600), \"ucp-metrics\":(*types.OrcaContainer)(0xc042225800),
\"ucp-proxy\":(*types.OrcaContainer)(0xc042225380)}}","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-swarm-join not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"info","msg":"Engine cert detected, mocking proxy instance.","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-client-root-ca not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-cluster-root-ca not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-kv not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-auth-store not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-swarm-manager not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-auth-api not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-auth-worker not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-metrics not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Container ucp-controller not found","time":"2017-02-01T10:19:27-08:00"}
{"level":"debug","msg":"Current Node Config:
\u0026types.NodeConfig{ClusterConfig:types.ClusterConfig{ControllerPort:0, SwarmPort:0, SwarmStrategy:\"\",
ImageVersion:\"\", UCPInstanceID:\"\", DNS:[]string(nil), DNSOpt:[]string(nil), DNSSearch:[]string(nil), KVTimeout:0,
KVSnapshotCount:0, ProfilingEnabled:false, Uninstall:false, ExternalServiceLB:\"\", MetricsRetentionTime:\"\",
DTRHostAddress:\"\", DTRCAHash:\"\"}, NodeID:\"\", IsManager:false, NodeCertExpiry:0, CertsNeedRegen:false,
CertsNeedPermissionsUpdate:false, HostAddress:\"\", Hostname:\"\", SANs:[]string(nil), Managers:[]string(nil),
ClusterCASigningURLs:[]string(nil), Containers:map[string]*types.OrcaContainer{\"ucp-proxy\":(*types.OrcaContainer)(0xc
042225a00)}}","time":"2017-02-01T10:19:27-08:00"}

**Comment by donhui** [comment]
I had the same problem.

**Comment by GabrielTK** [comment]
+1

**Comment by VoteForNavalny** [comment]
`Docker version 17.03.1-ce, build c6d412e`

`Error response from daemon: Cannot stop container docker_web_1: Cannot kill container bbffecf8ca47bd25d94104fb0fb0927bea276ed7ccba497a211ff94416d8725b: rpc error: code = 7 desc = permission denied  `
Even as root.

**Comment by thaJeztah** [comment]
@VoteForNavalny your error is about killing a container, not joining/leaving a node to the swarm, so not related to the discussion here

**Comment by COS-egbertozanon** [comment]
Hi,
I had the same problem recently, I got it resolved by  running the following commands  on the  problematic  **worker**:

- [ ] docker swarm init 
- [ ] docker swarm leave --force

Then on one of the **Managers**:

- [ ] swarm

 join-token worker

Then I was able to join the worker to the swarm again.

**Comment by youngfer** [comment]
I remove /var/lib/docker/*,and restart docker daemon. then I can join the worker to the cluster.

**Comment by cghsir** [comment]
> I remove /var/lib/docker/*,and restart docker daemon. then I can join the worker to the cluster.

谢谢 解决了

**Comment by PatrickLang** [comment]
Closing stale issue - I'm not using swarm anymore
