### ISSUE TITLE
Docker exec and Orphan Process problem

### ISSUE THREAD

**Issue by sandyskies** [moby/moby#29700]
-->

**Description**

**Steps to reproduce the issue:**
1,

```
docker run -ti -d aa732f074453 bash
ca5ebc10df7df14ba706a606b00866613cc3e69d34c27375cb63ef4a36bbdb2e
docker exec -ti ca5ebc10df7df14ba706a606b0 bash 
sleep 1000&
exit  (hangs util sleep finish）
```
2,  

```
ps -elf  
F S UID         PID   PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root          1      0  0  80   0 -  2872 n_tty_ 17:26 ?        00:00:00 bash
4 S root         45      0  0  80   0 -  2872 wait   17:29 ?        00:00:00 bash
0 S root         66     45  0  80   0 -  1026 hrtime 17:29 ?        00:00:00 sleep 1000
0 R root         67     45  0  80   0 -  3338 -      17:29 ?        00:00:00 ps -elf
```

the sleep process PPID is the bash we run，but after  we exit the bash，and PPID becomes 0

```
ps -elf 
F S UID         PID   PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root          1      0  0  80   0 -  2872 n_tty_ 17:26 ?        00:00:00 bash
0 S root         66      0  0  80   0 -  1026 hrtime 17:29 ?        00:00:00 sleep 1000
4 S root         76      0  0  80   0 -  2872 wait   17:32 ?        00:00:00 bash
0 R root         96     76  0  80   0 -  3338 -      17:32 ?        00:00:00 ps -elf
```
if we try outside the container ,we will find out the ppid is actually the docker-containerd-shim process 
**Describe the results you received:**
1， exit hangs
2， ppid become 0
# **3， child process become zombie after exits**

**Describe the results you expected:**
1， exit quit normally
2,  ppid become 1

**Additional information you deem important (e.g. issue happens only occasionally):**
always
**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: xfs
 Dirs: 163
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.10.104.xxxxxx
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.3 GiB
Name: xxxxxxxxxxxxxxxxx
ID: VTSE:3AJP:MWYG:XSRO:VLHA:7RUN:S5KP:SDB4:HVDP:5HT3:24XC:VW52
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centos 6 with 3.10.x kernel version.

**Comment by thaJeztah** [comment]
ping @mlaventure @justincormack is this similar to https://github.com/docker/docker/issues/25348 ?

**Comment by sandyskies** [comment]
@thaJeztah I think the number 2 problem is similar to 25348 ,and I will try Runc rc4 to test , but I am not sure about the first on ,why exit will hangs until child process exits.

**Comment by sandyskies** [comment]
@thaJeztah  https://github.com/opencontainers/runc/pull/1018  It seems that  --console flag is removed and add --console-socket . So when running the new version of runc with docker ,  an error was reported : docker: Error response from daemon: oci runtime error: flag provided but not defined: -console.

**Comment by mlaventure** [comment]
Issue 1 is the expected behavior
Issue 2 should be fixed from 1.12.3 onward if I'm not mistaken.

Please update to 1.12.5 to fix the later.

To avoid the former ensure you close the new background process IOs, for instance :
```
sleep 1000 0<&- 2>&- 1>&- &
```

**Comment by sandyskies** [comment]
@mlaventure  1， it is not a excepted behavior , I don't have the problem when using docker 1.6.2 
issue  2 seems not fixed, it 's similar to #25348 ,and it's a runc problem.

**Comment by mlaventure** [comment]
@sandyskies 

1. is the correct behavior, we are waiting for the other side to close is IOs before exiting to avoid losing any logs. Since the sleep process keeps them open, we are not returning.


2. is working fine for me on 1.12.5 and 1.13.0. #25348 only applies when sharing a PID namespace with another container of the host

**Comment by sandyskies** [comment]
@mlaventure  issue 1，the behavior you said does not appear in docker 1.62

**Comment by sandyskies** [comment]
I will close this one, since runc is working on it .

**Comment by sandyskies** [comment]
https://github.com/opencontainers/runc/pull/993 @mlaventure  This fixes my issue，I will close.

**Comment by sandyskies** [comment]
not util https://github.com/opencontainers/runc/pull/976 is fixed

**Comment by sandyskies** [comment]
https://github.com/containerd/containerd/pull/1430 I create a pr for this issue,but just for 1.12.x ,hope someone find it useful.

**Comment by mlaventure** [comment]
Closing in favor of https://github.com/moby/moby/issues/34683
