### ISSUE TITLE
Removing stack that failed to fully deploy leaves behind stray networks

### ISSUE THREAD

**Issue by kinghuang** [moby/moby#30064]
**Description**

I have a four node swarm on Docker 1.13-rc5. I accidentally deployed a stack from a compose file whose services are all from a private registry, but without the `--with-registry-auth` option. My services failed to start, so I removed the stack.

While removing the stack, the docker client shows that it is moving the networks defined in the stack (all overlay/swarm in this case), as expected. But, upon listing the networks on the nodes, some of the stack networks have actually been left behind and now appear as overlay/local.

The stack cannot be deployed again until the stray networks are removed from all the nodes.

**Steps to reproduce the issue:**

Given a Docker Compose file with some networks defined, and services that use a private registry:

1. Create a Docker Compose file with services whose images are on a private registry, and with some networks.
2. Deploy a stack using the compose file, but without the `--with-registry-auth` option.
3. Remove the stack because the services failed to start due to missing images (they can't be pulled).
4. List the networks on the swarm nodes.

**Describe the results you received:**

Some of the networks that were created as part of the stack deployment are left behind. Their driver is still overly, but their scope has changed from swarm to local.

**Describe the results you expected:**

The networks that were created as part of the stack deployment should be all removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's the Docker Compose file I was trying to deploy, and output showing the problem.

```
networks:
  converis: {}
  front: {}
  traefik_rms-dev:
    external: true
services:
  converis:
    environment:
      CONVERIS_HOST: converis-db-configs-master.rms-test.ucalgary.ca
      CRA_HOST: converis-db-configs-master.rms-test.ucalgary.ca
    image: docker.ucalgary.ca/tr/converis:5.9.8
    networks:
      converis: null
      front: null
  converis-db:
    environment:
      CONVERIS_HOST: converis-db-configs-master.rms-test.ucalgary.ca
      CRA_HOST: converis-db-configs-master.rms-test.ucalgary.ca
    image: docker.ucalgary.ca/rms/converis-db-configs:master
    networks:
      converis: null
  converis-web:
    environment:
      CAS_LOGIN_URL: http://castestqa.ucalgary.ca/replicant/login
      CAS_VALIDATE_URL: http://castestqa.ucalgary.ca/replicant/ucserviceValidate
      CONVERIS_HOST: converis-db-configs-master.rms-test.ucalgary.ca
      CRA_HOST: converis-db-configs-master.rms-test.ucalgary.ca
    image: docker.ucalgary.ca/tr/converis-web:1.1.0
    networks:
      front: null
      traefik_rms-dev: null
version: '3.0'
volumes: {}
```

```
→  ~ docker stack ls
NAME  SERVICES

→  ~ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
58721ada8da1        bridge              bridge              local
45ac998dbf08        docker_gwbridge     bridge              local
3c2e6ce7fecf        host                host                local
68i730xxf68a        ingress             overlay             swarm
5430cf1700b3        none                null                local
vur2f7vb8eue        traefik_rms-dev     overlay             swarm

→  ~ docker stack deploy --compose-file /Users/kchuang/Downloads/converis-db-configs.yml converis-db-configs-master
Creating network converis-db-configs-master_default
Creating network converis-db-configs-master_converis
Creating network converis-db-configs-master_front
Creating service converis-db-configs-master_converis
Creating service converis-db-configs-master_converis-db
Creating service converis-db-configs-master_converis-web

→  ~ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
58721ada8da1        bridge                                bridge              local
svatalmcadi2        converis-db-configs-master_converis   overlay             swarm
k63biko0t0fm        converis-db-configs-master_default    overlay             swarm
pfkak51i75hr        converis-db-configs-master_front      overlay             swarm
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm

(time passes, services fail to start)

→  ~ docker stack rm converis-db-configs-master
Removing service converis-db-configs-master_converis-db
Removing service converis-db-configs-master_converis-web
Removing service converis-db-configs-master_converis
Removing network converis-db-configs-master_converis
Removing network converis-db-configs-master_front
Removing network converis-db-configs-master_default

→  ~ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
58721ada8da1        bridge                                bridge              local
fwe4wv5bc8md        converis-db-configs-master_converis   overlay             local
ks6pzoguzk3c        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm

→  ~ docker stack deploy --compose-file /Users/kchuang/Downloads/converis-db-configs.yml converis-db-configs-master
Creating network converis-db-configs-master_default
Creating service converis-db-configs-master_converis
Error response from daemon: network converis-db-configs-master_converis not found
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:43:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:43:46 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.0-rc5
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.406 GB
 Data Space Total: 65.28 GB
 Data Space Available: 60.87 GB
 Metadata Space Used: 1.126 MB
 Metadata Space Total: 683.7 MB
 Metadata Space Available: 682.5 MB
 Thin Pool Minimum Free Space: 6.527 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 3vz5vqb96ab3yh6mrhhbnf5ki
 Is Manager: true
 ClusterID: 9p9qjvvrp991zitpixlm8dpm5
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.45.32.40
 Manager Addresses:
  10.45.32.40:2377
  10.45.32.41:2377
  10.45.32.42:2377
  10.45.32.43:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: itpocnode01.ucalgary.ca
ID: OM7K:NNN7:75VJ:I34C:W5ZS:TCYH:ZGPH:SRXP:HINS:7O2W:IZQ4:QIGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on a four node swarm with Docker 1.13.0-rc5.

**Comment by thaJeztah** [comment]
ping @dnephin @vdemeester PTAL

**Comment by dnephin** [comment]
Possibly a duplicate of #29293. It feels like a swarmkit bug. From `stack deploy` we simply run a single `network rm`, it's up the swarmkit to remove all the networks.

If you inspect the networks that should have been removed, do they have the `com.docker.stack.namespace` label?  If you wait a while are the networks eventually removed?

**Comment by kinghuang** [comment]
I've tried it again and waited just over ten minutes. The stray networks are still there and haven't been removed. This is the case on the other swarm nodes, too.

```
→  converis-db-configs git:(stack-updates) ✗ date
Wed 11 Jan 2017 14:16:12 MST
→  converis-db-configs git:(stack-updates) ✗ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
bcd8459694fd        bridge              bridge              local
45ac998dbf08        docker_gwbridge     bridge              local
3c2e6ce7fecf        host                host                local
68i730xxf68a        ingress             overlay             swarm
5430cf1700b3        none                null                local
vur2f7vb8eue        traefik_rms-dev     overlay             swarm
→  converis-db-configs git:(stack-updates) ✗ docker stack deploy --compose-file converis-db-configs.yml converis-db-configs-master
Creating network converis-db-configs-master_converis
Creating network converis-db-configs-master_front
Creating network converis-db-configs-master_default
Creating service converis-db-configs-master_converis-web
Creating service converis-db-configs-master_converis
Creating service converis-db-configs-master_converis-db
→  converis-db-configs git:(stack-updates) ✗ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
bcd8459694fd        bridge                                bridge              local
uxsptalssouk        converis-db-configs-master_converis   overlay             swarm
m5xyxry040d2        converis-db-configs-master_default    overlay             swarm
qz7ht528v99a        converis-db-configs-master_front      overlay             swarm
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
→  converis-db-configs git:(stack-updates) ✗ date   
Wed 11 Jan 2017 14:17:09 MST
→  converis-db-configs git:(stack-updates) ✗ docker stack rm converis-db-configs-master
Removing service converis-db-configs-master_converis-db
Removing service converis-db-configs-master_converis
Removing service converis-db-configs-master_converis-web
Removing network converis-db-configs-master_default
Removing network converis-db-configs-master_front
Removing network converis-db-configs-master_converis
→  converis-db-configs git:(stack-updates) ✗ date
Wed 11 Jan 2017 14:17:21 MST
→  converis-db-configs git:(stack-updates) ✗ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
bcd8459694fd        bridge                                bridge              local
uxsptalssouk        converis-db-configs-master_converis   overlay             local
qz7ht528v99a        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
→  converis-db-configs git:(stack-updates) ✗ date
Wed 11 Jan 2017 14:22:50 MST
→  converis-db-configs git:(stack-updates) ✗ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
bcd8459694fd        bridge                                bridge              local
uxsptalssouk        converis-db-configs-master_converis   overlay             local
qz7ht528v99a        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
→  converis-db-configs git:(stack-updates) ✗ date
Wed 11 Jan 2017 14:28:33 MST
→  converis-db-configs git:(stack-updates) ✗ docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
bcd8459694fd        bridge                                bridge              local
uxsptalssouk        converis-db-configs-master_converis   overlay             local
qz7ht528v99a        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
```

The `com.docker.stack.namespace` label is on both networks. Here's the output from one of them.

```
→  converis-db-configs git:(stack-updates) ✗ docker network inspect converis-db-configs-master_converis
[
    {
        "Name": "converis-db-configs-master_converis",
        "Id": "uxsptalssoukt1vjtubiv7oxc",
        "Created": "2017-01-11T14:16:34.839593519-07:00",
        "Scope": "local",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {
            "com.docker.stack.namespace": "converis-db-configs-master"
        },
        "Peers": [
            {
                "Name": "itpocnode02.ucalgary.ca-37f0c4378103",
                "IP": "10.45.32.41"
            },
            {
                "Name": "itpocnode04.ucalgary.ca-7ca72cd6d9f7",
                "IP": "10.45.32.43"
            },
            {
                "Name": "itpocnode01.ucalgary.ca-3de9fae4a674",
                "IP": "10.45.32.40"
            }
        ]
    }
]
```

**Comment by kinghuang** [comment]
Just to be totally clear, if I deploy correctly with the `--with-registry-auth` option and the remove the stack, the networks are removed immediately and there's no problem. These stray networks that turn from `swarm` to `local` scope only happen when my stack isn't deployed successfully.

**Comment by kinghuang** [comment]
It's been about 25 minutes and they're still around. I don't think they're going away without manual intervention. 😀

```
→  converis-db-configs git:(stack-updates) ✗ date                                                      
Wed 11 Jan 2017 14:40:45 MST
→  converis-db-configs git:(stack-updates) ✗ docker network ls                                         
NETWORK ID          NAME                                  DRIVER              SCOPE
bcd8459694fd        bridge                                bridge              local
uxsptalssouk        converis-db-configs-master_converis   overlay             local
qz7ht528v99a        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
```

**Comment by thaJeztah** [comment]
ping @mavenugo @aboch PTAL

**Comment by fntlnz** [comment]
@kinghuang AFAIK this has been fixed in 1.13.1, can you try?

**Comment by kinghuang** [comment]
Will do.

**Comment by thaJeztah** [comment]
@kinghuang have you been able to test this on 1.13.1?

**Comment by kinghuang** [comment]
@thaJeztah I've just retried with the same Compose file and swarm, on 1.13.1. Still encountering the same problem. After running `docker stack rm converis-db-configs-master`, the stack networks get left behind with a `local` scope, then subsequent deploys fail. I waited about 10 minutes after `docker stack rm…`.

```
(swarm) →  ~ cd Desktop/30064 
(swarm) →  30064 docker stack ls
NAME  SERVICES
(swarm) →  30064 docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
a890177aa357        bridge              bridge              local
45ac998dbf08        docker_gwbridge     bridge              local
3c2e6ce7fecf        host                host                local
68i730xxf68a        ingress             overlay             swarm
5430cf1700b3        none                null                local
vur2f7vb8eue        traefik_rms-dev     overlay             swarm
(swarm) →  30064 docker stack deploy --compose-file converis-db-configs.yml converis-db-configs-master
Creating network converis-db-configs-master_converis
Creating network converis-db-configs-master_front
Creating service converis-db-configs-master_converis
Creating service converis-db-configs-master_converis-db
Creating service converis-db-configs-master_converis-web
(swarm) →  30064 docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
a890177aa357        bridge                                bridge              local
tn0op9fn91zi        converis-db-configs-master_converis   overlay             swarm
x5mjx7g61fb9        converis-db-configs-master_front      overlay             swarm
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
(swarm) →  30064 docker stack ps converis-db-configs-master
ID            NAME                                       IMAGE                                              NODE                     DESIRED STATE  CURRENT STATE                    ERROR                             PORTS
qeaqcuc3o63m  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode03.ucalgary.ca  Ready          Rejected less than a second ago  "No such image: docker.ucalgar…"  
sd76ekddyg0d  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode02.ucalgary.ca  Ready          Rejected less than a second ago  "No such image: docker.ucalgar…"  
4ury5apbpod6  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode03.ucalgary.ca  Ready          Rejected 1 second ago            "No such image: docker.ucalgar…"  
9k45sxwbr4yx  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode03.ucalgary.ca  Shutdown       Rejected 5 seconds ago           "No such image: docker.ucalgar…"  
pcr9hq682e7i  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode02.ucalgary.ca  Shutdown       Rejected 6 seconds ago           "No such image: docker.ucalgar…"  
ey30z9r0ubis  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode02.ucalgary.ca  Shutdown       Rejected 6 seconds ago           "No such image: docker.ucalgar…"  
juwd3o7fqfd2  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode02.ucalgary.ca  Shutdown       Rejected 10 seconds ago          "No such image: docker.ucalgar…"  
wttpw8k1ugud  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode02.ucalgary.ca  Shutdown       Rejected 10 seconds ago          "No such image: docker.ucalgar…"  
f6i1tioropi5  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode03.ucalgary.ca  Shutdown       Rejected 11 seconds ago          "No such image: docker.ucalgar…"  
poh5lg75cjz7  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode04.ucalgary.ca  Shutdown       Rejected 15 seconds ago          "No such image: docker.ucalgar…"  
46p5dc46tj65  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode03.ucalgary.ca  Shutdown       Rejected 15 seconds ago          "No such image: docker.ucalgar…"  
p1mv5g3251rf  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode03.ucalgary.ca  Shutdown       Rejected 15 seconds ago          "No such image: docker.ucalgar…"  
z7rp6uqj8ztr  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode04.ucalgary.ca  Shutdown       Rejected 20 seconds ago          "No such image: docker.ucalgar…"  
ocx9pkbiz64j  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode04.ucalgary.ca  Shutdown       Rejected 20 seconds ago          "No such image: docker.ucalgar…"  
rh7hsrvhyyxf  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode04.ucalgary.ca  Shutdown       Rejected 21 seconds ago          "No such image: docker.ucalgar…"  
m75zjlc9f4pc  converis-db-configs-master_converis-web.1  docker.ucalgary.ca/tr/converis-web:1.1.0           itpocnode04.ucalgary.ca  Shutdown       Rejected 26 seconds ago          "No such image: docker.ucalgar…"  
6my67hxug5b7  converis-db-configs-master_converis-db.1   docker.ucalgary.ca/rms/converis-db-configs:master  itpocnode04.ucalgary.ca  Shutdown       Rejected 25 seconds ago          "No such image: docker.ucalgar…"  
3zkcktfs9rnv  converis-db-configs-master_converis.1      docker.ucalgary.ca/tr/converis:5.9.8               itpocnode04.ucalgary.ca  Shutdown       Rejected 26 seconds ago          "No such image: docker.ucalgar…"  
(swarm) →  30064 docker stack rm converis-db-configs-master
Removing service converis-db-configs-master_converis-db
Removing service converis-db-configs-master_converis
Removing service converis-db-configs-master_converis-web
Removing network converis-db-configs-master_converis
Removing network converis-db-configs-master_front
(swarm) →  30064 docker network ls
NETWORK ID          NAME                                  DRIVER              SCOPE
a890177aa357        bridge                                bridge              local
tn0op9fn91zi        converis-db-configs-master_converis   overlay             local
x5mjx7g61fb9        converis-db-configs-master_front      overlay             local
45ac998dbf08        docker_gwbridge                       bridge              local
3c2e6ce7fecf        host                                  host                local
68i730xxf68a        ingress                               overlay             swarm
5430cf1700b3        none                                  null                local
vur2f7vb8eue        traefik_rms-dev                       overlay             swarm
(swarm) →  30064 docker stack deploy --compose-file converis-db-configs.yml converis-db-configs-master
Creating service converis-db-configs-master_converis-db
Error response from daemon: network converis-db-configs-master_converis not found
(swarm) →  30064 
```

**Comment by kinghuang** [comment]
```
(swarm) →  30064 docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 7.645 GB
 Data Space Total: 65.28 GB
 Data Space Available: 57.63 GB
 Metadata Space Used: 2.65 MB
 Metadata Space Total: 683.7 MB
 Metadata Space Available: 681 MB
 Thin Pool Minimum Free Space: 6.527 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 3vz5vqb96ab3yh6mrhhbnf5ki
 Is Manager: true
 ClusterID: 9p9qjvvrp991zitpixlm8dpm5
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.45.32.40
 Manager Addresses:
  10.45.32.40:2377
  10.45.32.41:2377
  10.45.32.42:2377
  10.45.32.43:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: itpocnode01.ucalgary.ca
ID: OM7K:NNN7:75VJ:I34C:W5ZS:TCYH:ZGPH:SRXP:HINS:7O2W:IZQ4:QIGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: kinghuang
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I tried to reproduce, but simplified the `docker-compose` file (as I don't have access to those images);

```yaml
networks:
  converis: {}
  front: {}
  traefik_rms-dev:
    external: true
services:
  converis:
    image: nginx:alpine
    networks:
      converis: null
      front: null
  converis-db:
    image: nginx:alpine
    networks:
      converis: null
  converis-web:
    image: nginx:alpine
    networks:
      front: null
      traefik_rms-dev: null
version: '3.0'
volumes: {}
```

However, the networks were successfully removed for me. I _did_ notice that your services were not running when you removed the stack;

```
Rejected less than a second ago  "No such image: docker.ucalgar…" 
```

Are you seeing the problem only if the services weren't deployed successfully, or also after they are successfully up (wondering if there's a relation)

**Comment by kinghuang** [comment]
@thaJeztah This issue only happens when services don't deploy successfully. For successful deployments, the networks get removed after a small wait.

**Comment by kinghuang** [comment]
@thaJeztah Based on the simplified Docker Compose file, I was able to reproduce the problem by changing the image tags to something that can't be pulled (doesn't exist).

```
networks:
  converis: {}
  front: {}
  traefik_rms-dev:
    external: true
services:
  converis:
    image: nginx:nonexistent-tag
    networks:
      converis: null
      front: null
  converis-db:
    image: nginx:nonexistent-tag
    networks:
      converis: null
  converis-web:
    image: nginx:nonexistent-tag
    networks:
      front: null
      traefik_rms-dev: null
version: '3.0'
volumes: {}
```

```
(swarm) →  30064 docker stack deploy --compose-file nginx-nonexistent-tag.yml 30064
Creating network 30064_converis
Creating network 30064_front
Creating service 30064_converis-db
Creating service 30064_converis-web
Creating service 30064_converis
(swarm) →  30064 docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
rrncra9e11zz        30064_converis      overlay             swarm
t94o8cfll21q        30064_front         overlay             swarm
a890177aa357        bridge              bridge              local
45ac998dbf08        docker_gwbridge     bridge              local
3c2e6ce7fecf        host                host                local
68i730xxf68a        ingress             overlay             swarm
5430cf1700b3        none                null                local
vur2f7vb8eue        traefik_rms-dev     overlay             swarm
(swarm) →  30064 docker stack rm 30064
Removing service 30064_converis-db
Removing service 30064_converis
Removing service 30064_converis-web
Removing network 30064_converis
Removing network 30064_front
(swarm) →  30064 docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
rrncra9e11zz        30064_converis      overlay             local
t94o8cfll21q        30064_front         overlay             local
a890177aa357        bridge              bridge              local
45ac998dbf08        docker_gwbridge     bridge              local
3c2e6ce7fecf        host                host                local
68i730xxf68a        ingress             overlay             swarm
5430cf1700b3        none                null                local
vur2f7vb8eue        traefik_rms-dev     overlay             swarm
```

**Comment by dnephin** [comment]
@thaJeztah if there is a bug here it's related to removing networks in swarm mode. It's not actually related to stacks, it just happens the bug is more noticeable when using stacks because of the sequence of API calls.

It seems like the `network rm` API call is not correctly removing the network.

**Comment by soumyadipDe** [comment]
Facing the same issue in docker 17.03.1-ce. Intermittently docker stack rm leaves stray overlay network with local scope. This actually results in subsequent containers of other apps also saying "Address already in use". Looks like docker assigns some ip which is still reserved in the stray network. To resolve this we need to manually disconnect endpoints of the stray network and then remove it. 
Should we be expecting any fix for this?

**Comment by mavenugo** [comment]
@soumyadipDe @kinghuang can you pls share the docker daemon logs on the nodes where you see the `overlay / local` networks ? That will give us an indication on why these networks are failed to be removed.

**Comment by mavenugo** [comment]
@kinghuang @thaJeztah @soumyadipDe I tried a bunch of times with the reproduction steps : https://github.com/moby/moby/issues/30064#issuecomment-281138532, but I dont see this issue with 17.03.1-ce. It will be great if you can help with a consistent reproduction or pass on the daemon logs (from the nodes where the stray networks are seen) when the issue is seen.

**Comment by kinghuang** [comment]
@mavenugo I am unable to reproduce this with `17.05.0-ce`. I believe this issue was resolved elsewhere sometime after 1.13.0, but I don't know which PR.

**Comment by soumyadipDe** [comment]
It used to happen in our CI when we would be doing stack deploy right after
stack rm causing some in-middle state for the network. Can we expect
synchronous stack rm/deploy anytime soon?

**Comment by vdemeester** [comment]
@soumyadipDe there is https://github.com/moby/moby/issues/32367 to track this down 😉

**Comment by kinghuang** [comment]
@soumyadipDe Yeah, that's a slightly different problem, covered in #30942 and #32367 as @vdemeester mentioned. I believe this specific issue has been resolved.

**Comment by mavenugo** [comment]
Thanks @kinghuang. I will close this issue since it is resolved in 17.05. I still dont know which fix solved the issue though .

**Comment by pratiksanglikar** [comment]
I can still reproduce this issue on 19.03.13.
Can you please reopen the issue?
