### ISSUE TITLE
Set-TimeZone Changing Host Machine TimeZone too

### ISSUE THREAD

**Issue by efaruk** [moby/moby#30587]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

When we use Set-TimeZone in windowscore based container its changing host machine timezone too.

**Steps to reproduce the issue:**

1. Create Dockerfile as following:
```
FROM microsoft/dotnet-framework:3.5
COPY assets/ assets/
ENTRYPOINT [ "powershell" ]
```
2. Build and run container with -it switch
3. Run `Set-TimeZone -Id "Pacific Standard Time"` (Different timezone from host machine)
4. Check Container's and Host Machine time zones with `Get-TimeZone` powershell command

**Describe the results you received:**

Set-TimeZone affecting both container and host machine

**Describe the results you expected:**

Use Set-TimeZone to set only container timezone

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 6 GiB
Name: wincon
ID: TRSR:EBZG:57NQ:VGAH:NTIE:WA4T:ZLAK:7JCX:2LMU:HFHF:UVLV:AZRC
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**
I'm running windows docker host machine inside of an Oracle VirtualBox

Thanks, regards...

**Comment by cpuguy83** [comment]
ping @jhowardmsft

**Comment by efaruk** [comment]
I have created same issue here https://github.com/docker/for-win/issues/451 but its closed for reason: Docker for Windows not currently supporting windows server 2016.

Actually i have tried with docker 1.13 too on windows server 2016, issue still exists. Windows 10 is not an option for us right now, because our docker host machine is windows server 2016 too...

I'm looking forward any news on this and i'm open to suggestions like some workarounds...

Thanks, regards...

**Comment by rneugeba** [comment]
Thanks for creating it and checking 1.13 as well. I couldn't repro it on Windows 10 Pro, so this might be related to native windows containers vs containers with Hyper-V isolation

**Comment by PatrickLang** [comment]
@rneugeba yes, agreed. I can repro with process isolation on Windows Server 2016 but not with Hyper-V isolation.

`docker run microsoft/windowsservercore powershell "Set-Timezone -Id 'Pacific Standard Time'"`

**Comment by efaruk** [comment]
So what is your suggestion?

**Comment by friism** [comment]
@efaruk as a temporary workaround, you can run with `--isolation hyperv`.

**Comment by PatrickLang** [comment]
I filed an internal bug with the windows team VSO#10745839. I'll post back when I have an update but this would require a Windows patch or new version to fix. @friism is right on the short term workaround, but it won't work in VirtualBox.

**Comment by efaruk** [comment]
if we are able to create a base image which is configured with desired time
zone, is it worth to try? Or could we use --isolation hyperv at build time?

Thank you very much @all

Regards...

**Comment by PatrickLang** [comment]
@efaruk you could try putting that in the Dockerfile, but I suspect that the last container started will force the setting to all running containers. If you try it can you let us know the results? `--isolation=hyperv` would be needed at build & run time

**Comment by efaruk** [comment]
Of course, i will try and let you now...

**Comment by efaruk** [comment]
Hi @PatrickLang, @friism, @rneugeba, i couldn't try --isolation=hyperv  because i don't have any bare metal with windows 10 installed. I did tried this: https://www.baswijdenes.com/portfolio/hyper-v-in-virtualbox-guide/ doesn't work either on VirtualBox nor AWS . 

Any way this is not an option on any cloud nor on any virtualization environment i guess...

I don't know who are hosting their own infrastructure for running containers, it seems this is kind a every ones problem which are who requires different time zones.

What can i do to make this one has more priority?

Thanks and regards...

**Comment by efaruk** [comment]
@GordonTheTurtle could you label this one also as 1.13 too, because this is valid for 1.12 and 1.13 versions?

**Comment by efaruk** [comment]
Hey @PatrickLang @friism and @rneugeba is it can be a possible hack using `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation`. I didn't tried yet, but what are your thoughts?

**Comment by georgyturevich** [comment]
Hello there,

`tzutill` also affects whole Docker Host. For example:

`docker exec gt_test_iis tzutil /s "Russian Standard time"`

@PatrickLang @friism Do we have any updates about internal issue  VSO#10745839 ?

We use AWS instances as Docker Hosts for our containers so we can not isolate containers by hyperv isolation level. So it is kind of critical for us.

**Comment by PatrickLang** [comment]
The issue is understood, but I don't have an ETA yet. I'll share when I know more.

**Comment by friism** [comment]
@PatrickLang I'm hearing rumors that a fix is on the way - do you have an ETA now?

**Comment by PatrickLang** [comment]
It should be in the Windows insider build - both 10 and server

Sent from a tiny keyboard

On Jul 24, 2017, at 11:35 AM, Michael Friis <notifications@github.com<mailto:notifications@github.com>> wrote:


@PatrickLang<https://github.com/patricklang> I'm hearing rumors that a fix is on the way - do you have an ETA now?

**Comment by georgyturevich** [comment]
@PatrickLang Hi Patrick,

It is good news. Do we have some rough dates when it will be included to official updates?

**Comment by thaJeztah** [comment]
Looks like this issue should be resolved (and part of the Windows 1709 update), so closing

**Comment by Labrat02** [comment]
"Should" is not helpful.  This has been fixed in the microsoft/windowservercore  image.. But what about microsoft/aspnet ?

**Comment by thaJeztah** [comment]
The fix was not in the image, but in Windows itself

**Comment by BogdanDamianC** [comment]
It is still happening to me, should I use a different win version ?
HOST:win10- Build 18362.295

docker file:
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019

RUN "Set-TimeZone  -Id 'Eastern Standard Time'"

result:
Set-TimeZone : Access is denied

**Comment by SlyNet** [comment]
This is still not fixed in windows 10 18362.356, is there any reference where original issue can be tracked?
