### ISSUE TITLE
Missing CLI reference Markdown files in docs/reference/commandline/

### ISSUE THREAD

**Issue by FrenchBen** [moby/moby#31024]
**Description**

While compile the latest YAML files for docs, the following CLI reference files were found to be missing:

* [ ] docs/reference/commandline/checkpoint/create.md
* [ ] docs/reference/commandline/checkpoint/ls.md
* [ ] docs/reference/commandline/checkpoint/rm.md
* [ ] docs/reference/commandline/checkpoint.md
* [ ] docs/reference/commandline/container/attach.md
* [ ] docs/reference/commandline/container/commit.md
* [ ] docs/reference/commandline/container/cp.md
* [ ] docs/reference/commandline/container/create.md
* [ ] docs/reference/commandline/container/diff.md
* [ ] docs/reference/commandline/container/exec.md
* [ ] docs/reference/commandline/container/export.md
* [ ] docs/reference/commandline/container/inspect.md
* [ ] docs/reference/commandline/container/kill.md
* [ ] docs/reference/commandline/container/logs.md
* [ ] docs/reference/commandline/container/ls.md
* [ ] docs/reference/commandline/container/pause.md
* [ ] docs/reference/commandline/container/port.md
* [ ] docs/reference/commandline/container/prune.md
* [ ] docs/reference/commandline/container/rename.md
* [ ] docs/reference/commandline/container/restart.md
* [ ] docs/reference/commandline/container/rm.md
* [ ] docs/reference/commandline/container/run.md
* [ ] docs/reference/commandline/container/start.md
* [ ] docs/reference/commandline/container/stats.md
* [ ] docs/reference/commandline/container/stop.md
* [ ] docs/reference/commandline/container/top.md
* [ ] docs/reference/commandline/container/unpause.md
* [ ] docs/reference/commandline/container/update.md
* [ ] docs/reference/commandline/container/wait.md
* [ ] docs/reference/commandline/container.md
* [ ] docs/reference/commandline/image/build.md
* [ ] docs/reference/commandline/image/history.md
* [ ] docs/reference/commandline/image/import.md
* [ ] docs/reference/commandline/image/inspect.md
* [ ] docs/reference/commandline/image/load.md
* [ ] docs/reference/commandline/image/ls.md
* [ ] docs/reference/commandline/image/prune.md
* [ ] docs/reference/commandline/image/pull.md
* [ ] docs/reference/commandline/image/push.md
* [ ] docs/reference/commandline/image/rm.md
* [ ] docs/reference/commandline/image/save.md
* [ ] docs/reference/commandline/image/tag.md
* [ ] docs/reference/commandline/image.md
* [ ] docs/reference/commandline/network/connect.md
* [ ] docs/reference/commandline/network/create.md
* [ ] docs/reference/commandline/network/disconnect.md
* [ ] docs/reference/commandline/network/inspect.md
* [ ] docs/reference/commandline/network/ls.md
* [ ] docs/reference/commandline/network/prune.md
* [ ] docs/reference/commandline/network/rm.md
* [ ] docs/reference/commandline/network.md
* [ ] docs/reference/commandline/node/demote.md
* [ ] docs/reference/commandline/node/inspect.md
* [ ] docs/reference/commandline/node/ls.md
* [ ] docs/reference/commandline/node/promote.md
* [ ] docs/reference/commandline/node/ps.md
* [ ] docs/reference/commandline/node/rm.md
* [ ] docs/reference/commandline/node/update.md
* [ ] docs/reference/commandline/node.md
* [ ] docs/reference/commandline/plugin/create.md
* [ ] docs/reference/commandline/plugin/disable.md
* [ ] docs/reference/commandline/plugin/enable.md
* [ ] docs/reference/commandline/plugin/inspect.md
* [ ] docs/reference/commandline/plugin/install.md
* [ ] docs/reference/commandline/plugin/ls.md
* [ ] docs/reference/commandline/plugin/push.md
* [ ] docs/reference/commandline/plugin/rm.md
* [ ] docs/reference/commandline/plugin/set.md
* [ ] docs/reference/commandline/plugin/upgrade.md
* [ ] docs/reference/commandline/plugin.md
* [ ] docs/reference/commandline/secret/create.md
* [ ] docs/reference/commandline/secret/inspect.md
* [ ] docs/reference/commandline/secret/ls.md
* [ ] docs/reference/commandline/secret/rm.md
* [ ] docs/reference/commandline/secret.md
* [ ] docs/reference/commandline/service/create.md
* [ ] docs/reference/commandline/service/inspect.md
* [ ] docs/reference/commandline/service/logs.md
* [ ] docs/reference/commandline/service/ls.md
* [ ] docs/reference/commandline/service/ps.md
* [ ] docs/reference/commandline/service/rm.md
* [ ] docs/reference/commandline/service/scale.md
* [ ] docs/reference/commandline/service/update.md
* [ ] docs/reference/commandline/service.md
* [ ] docs/reference/commandline/stack/deploy.md
* [ ] docs/reference/commandline/stack/ls.md
* [ ] docs/reference/commandline/stack/ps.md
* [ ] docs/reference/commandline/stack/rm.md
* [ ] docs/reference/commandline/stack/services.md
* [ ] docs/reference/commandline/stack.md
* [ ] docs/reference/commandline/swarm/init.md
* [ ] docs/reference/commandline/swarm/join.md
* [ ] docs/reference/commandline/swarm/join-token.md
* [ ] docs/reference/commandline/swarm/leave.md
* [ ] docs/reference/commandline/swarm/unlock.md
* [ ] docs/reference/commandline/swarm/unlock-key.md
* [ ] docs/reference/commandline/swarm/update.md
* [ ] docs/reference/commandline/swarm.md
* [ ] docs/reference/commandline/system/df.md
* [ ] docs/reference/commandline/system/events.md
* [ ] docs/reference/commandline/system/info.md
* [ ] docs/reference/commandline/system/prune.md
* [ ] docs/reference/commandline/system.md
* [ ] docs/reference/commandline/volume/create.md
* [ ] docs/reference/commandline/volume/inspect.md
* [ ] docs/reference/commandline/volume/ls.md
* [ ] docs/reference/commandline/volume/prune.md
* [ ] docs/reference/commandline/volume/rm.md
* [ ] docs/reference/commandline/volume.md

**Steps to reproduce the issue:**
1. In a terminal get the help for `docker volume --help`
2. Notice you get some help
3. try to find the matching CLI ref in the docs reference folder and you'll see that https://github.com/docker/docker/blob/master/docs/reference/commandline/volume.md is missing

**Describe the results you received:**
404 page not found

**Describe the results you expected:**
to find the matching Markdown file for the above command

**Comment by thaJeztah** [comment]
@FrenchBen is this still something to look into? I think this is addressed with the latest YAML generator version?

**Comment by FrenchBen** [comment]
@thaJeztah I believe this to still be valid as the above file descriptions for the commands are still missing. 
The latest YAML reads from this location, but will miss some of the possible extended examples/info

**Comment by thaJeztah** [comment]
But the files are not in subdirectories, but use underscores (`secret_create.md` instead of `secret/create.md`)

**Comment by FrenchBen** [comment]
I will edit the original post to reflect that - Still:
https://github.com/docker/docker/blob/master/docs/reference/commandline/volume.md (404)

**Comment by vdemeester** [comment]
ping @FrenchBen ? I believe "root command" (like `volume.md`, `network.md`) are still missing, but the other one, as @thaJeztah said, are there (just using `_` instead of `/`)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
