### ISSUE TITLE
 Debian wheezy repository issue  #30547

### ISSUE THREAD

**Issue by ksigjayt** [moby/moby#31495]
Please reference the thread on the below issue as it was marked closed, but the issue is not resolved.

I'm pretty sure that the repo has a bad Release file for the Docker package for Debian Wheezy.
 ==> Unable to find expected entry 'main/source/Sources' in Release file

https://github.com/docker/docker/issues/30547

**Comment by thaJeztah** [comment]
What architecture are you running on?

**Comment by ksigjayt** [comment]
I'm running on arch=armhf / armv7l 

# uname -m
armv7l

I see that the Debian Docker documentation has been updated in the past couple of days...
Will see if the new updates to the install procedure works for me here in a few mins.

https://docs.docker.com/engine/installation/linux/debian/#/install-using-the-repository

**Comment by ksigjayt** [comment]
Installing via apt using the above updated link didn't work either:

# apt-get update
...
W: Conflicting distribution: https://download.docker.com wheezy Release (expected wheezy but got )
W: Failed to fetch https://download.docker.com/linux/debian/dists/wheezy/Release  Unable to find expected entry 'stable/source/Sources' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.

# apt-get -y install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce

Since the apt install didn't work, I tried plan B of installing from a package... that process also fails because the link provided in the documentation gives an access denied error so I cannot download the .deb package(s) either.  I even tried going up one level from the below link to list what is available for arm architectures but the whole path gives access denied.

https://download.docker.com/linux/debian/pool/stable/amd64/

**Comment by hcguersoy** [comment]
Same here with Ubuntu 14.04 :-(

**Comment by thaJeztah** [comment]
Those packages are for amd64, you're trying to install on armhf, and there's no package for wheezy http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

<img width="665" alt="screen shot 2017-03-03 at 10 21 05" src="https://cloud.githubusercontent.com/assets/1804568/23548152/702a2998-0006-11e7-87ff-3ae55571b94f.png">


> I even tried going up one level from the below link to list what is available for arm architectures but the whole path gives access denied.

Yes, the download.docker.com repository does not have index files currently, so does not allow browsing at this moment.

**Comment by thaJeztah** [comment]
fwiw, I opened an issue for the documentation to better document the supported platforms/versions; https://github.com/docker/docker.github.io/issues/2085

**Comment by ksigjayt** [comment]
Thank you for the updates fellas.  I do think that better documentation around what is/is-not supported would have really helped me understand early on as to whether or not Docker is supported/available for this device/environment.  This is one thing that can be increasingly difficult to traverse if we aren't clear with the up front documentation for Linux in particular due to the high variety/variability of combinations available in the global community.

**Comment by Michi302** [comment]
I have a similar issue with the repository but I'm using Debian Jessie on amd64.
My sources.list contains this entry:
```
deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
```

But I'm getting this error when running apt-get update:
```
W: Conflicting distribution: https://download.docker.com jessie InRelease (expected jessie but got )
```

**Comment by ksigjayt** [comment]
Thanks, everyone.

Got this to work -- I reimaged as Debian Jessie (arch=armv7l) and installed via package at the link below:
https://docs.docker.com/engine/installation/linux/debian/#install-using-the-repository 

# lsb_release -a -cs
No LSB modules are available.
Debian
Debian GNU/Linux 8.6 (jessie)
8.6
Jessie

I grabbed the package from:
http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_17.03.0~ce-0~debian-jessie_armhf.deb

And then this did the trick to install:
# dpkg -i /root/docker-engine_17.03.0~ce-0~debian-jessie_armhf.deb
Selecting previously unselected package docker-engine.
(Reading database ... 69434 files and directories currently installed.)
Preparing to unpack .../docker-engine_17.03.0~ce-0~debian-jessie_armhf.deb ...
Unpacking docker-engine (17.03.0~ce-0~debian-jessie) ...
Setting up docker-engine (17.03.0~ce-0~debian-jessie) ...
Processing triggers for systemd (230-7~bpo8+2) ...
Processing triggers for man-db (2.7.0.2-5) ...

# sudo systemctl enable docker
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker

**Comment by andrewhsu** [comment]
Warning is known issue, it does not block the ability to proceed with install. Working on fix for it.

> `W: Conflicting distribution: https://download.docker.com jessie InRelease (expected jessie but got )`

**Comment by ksigjayt** [comment]
Andrew, you are incorrect.  See above.  The install did not proceed via the apt install.  Yall just orobabky need more time to learn how to properly package the apt installs as it seems like this is a very common problem that never seems to get resolved.  Many of the responses from the support folks just say its not a problem and move on.  Would strongly suggest that you actually following your own processes every once in a while to validate the apt install process because I don't think it has ever worked on any platform or architecture as far as I can tell.   Many people consider Docker to be unusable as a result.

**Comment by cpuguy83** [comment]
@ksigjayt The tone is not needed on this repo.

The person @andrewhsu was responding to has a warning that indeed does not affect install, and as he said he's working on a fix.

The packages provided on download.docker.com only support x86_64 for now which is why you are seeing an issue on non x86_64 hardware.

**Comment by hcguersoy** [comment]
@cpuguy83 Unfortunately I've observed this behaviour/warning on a fresh installed Ubuntu 14.04.5 @ Digital Ocean, too:

```
W: Conflicting distribution: https://download.docker.com jessie InRelease (expected trusty but got )
```

It's based on the AMD64  image:

```
# uname -a
Linux ubuntu-512mb-fra1-01 4.4.0-63-generic #84~14.04.2-Ubuntu SMP Mon Feb 13 11:04:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

To be really sure that I'm not writing any nonsense I'll test it on the weekend again and if it is reproducible open a new issue.

**Comment by andrewhsu** [comment]
@Michi302 @hcguersoy warning about conflicting distribution has been resolved:
```
$ docker run --rm debian:jessie bash -c 'apt-get -y update && apt-get -y install apt-transport-https curl && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && echo "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable" > /etc/apt/sources.list.d/docker.list && apt-get -y update'
...
Get:1 https://download.docker.com jessie InRelease [13.9 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [442 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 https://download.docker.com jessie/stable amd64 Packages [993 B]
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:4 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9049 kB]
Fetched 9523 kB in 5s (1856 kB/s)
Reading package lists...
```

And on trusty:
```
$ docker run --rm -it ubuntu:trusty bash -c 'apt -y update && apt -y install apt-transport-https curl && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && echo "deb [arch=amd64] https://s3.amazonaws.com/editions-stage-us-east-1-150610-005505/linux/ubuntu trusty stable" > /etc/apt/sources.list.d/docker.list && apt -y update'
...
Hit http://archive.ubuntu.com trusty/main Sources                                                                                        Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Fetched 15.0 kB in 5s (2733 B/s)
Reading package lists... Done
```

**Comment by hcguersoy** [comment]
@andrewhsu Yes, it's working now like a charm :-)

After running through the process (apt-add-repository, apt-get update) it looks like this now:

```
# apt-cache madison docker-ce
 docker-ce | 17.03.0~ce-0~ubuntu-trusty | https://download.docker.com/linux/ubuntu/ trusty/stable amd64 Packages
```

and installs now without problems.

**Comment by pbek** [comment]
I'm sorry to report that I still get a `W: Failed to fetch https://download.docker.com/linux/debian/dists/wheezy/Release  Unable to find expected entry 'stable/source/Sources' in Release file (Wrong sources.list entry or malformed file)` when doing an `apt-get update` on Debian GNU/Linux 7.11 (wheezy), amd64.

I was following the instructions from <https://docs.docker.com/engine/installation/linux/docker-ce/debian/> for Wheezy.

My `/etc/apt/sources.list`:

```
deb [arch=amd64] https://download.docker.com/linux/debian wheezy stable
deb-src [arch=amd64] https://download.docker.com/linux/debian wheezy stable
```

**Comment by pbek** [comment]
Trying to install the `docker-ce_17.03.2~ce-0~debian-wheezy_amd64.deb` directly gives me a

```
dpkg: dependency problems prevent configuration of docker-ce:
 docker-ce depends on init-system-helpers (>= 1.18~); however:
  Package init-system-helpers is not installed.
 docker-ce depends on libapparmor1 (>= 2.6~devel); however:
  Package libapparmor1 is not installed.

dpkg: error processing docker-ce (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 docker-ce
```

**Comment by thaJeztah** [comment]
@pbek the error about sources is because the apt repository does not have a source distribution; try commenting the `deb-src` line in your `/etc/apt/sources.list`.

> But it will not start because of time="2017-08-14T10:23:49.403946708+02:00" level=fatal msg="Your Linux kernel version 3.2.0-4-amd64 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer." :/

Yes, that's expected, and explained in the installation manual (see the [Extra steps for Wheezy 7.7](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#extra-steps-for-wheezy-77) section));

> ### Extra steps for Wheezy 7.7
> - You need at least version 3.10 of the Linux kernel. Debian Wheezy ships with version 3.2, so you may need to update the kernel. To check your kernel version:
>         $ uname -r
>  - Enable the backports repository. See the [Debian documentation](https://backports.debian.org/Instructions/).

Wheezy is getting pretty old though, so if possible I would highly recommend upgrading to a more recent Debian release (stretch is current stable now)

**Comment by pbek** [comment]
@thaJeztah thank you clearing things up for me!

**Comment by vdemeester** [comment]
@andrewhsu @thaJeztah should we close this issue (as it seem to be fixed), and if there is any problem in the future, these should be reported on `docker/for-linux` ?

**Comment by thaJeztah** [comment]
Yes, let's close here, because packaging is not done in this repository; also note that Wheezy is soon to be EOL'd
