### ISSUE TITLE
ndots:0

### ISSUE THREAD

**Issue by ylavoie** [moby/moby#32093]
Docker imposes ndots:0 in current resolv.conf
This conflicts with search option and prevent containers from finding nodes in an intranet using short names.
Removing the ndots:0 option fixes that, so there should be a way to override it. Providing a different ndots value currently results in:
```
cat /etc/resolv.conf
search mynetwork.net
nameserver 127.0.0.11
options ndots:15 ndots:0
```

**Comment by cpuguy83** [comment]
This is what I see on 17.03:
```
docker run -it --rm --dns-option ndots:15 busybox cat /etc/resolv.conf
nameserver 192.168.65.1
options ndots:15
```

**Comment by mavenugo** [comment]
@cpuguy83 the nameserver is `127.0.0.11` and that means @ylavoie is using a custom network (not docker0).

@ylavoie yes. that is the intended behavior. @sanimej can add more details to it.

**Comment by ylavoie** [comment]
I agree that resolving in the docker domain is a must. Whether it must happens first or last is still to debate, all dns offers the possibility.

I indeed use a private network, I wanted to integrate that docker project into my local network. It is a Selenium test grid, running Linux Alpine containers, and served on a small Ubuntu server, to minimize the memory requirements. I am using Docker 17.03.0-ce, build 60ccb22, docker-compose version is 1.11.2, build dfed245. The grid containers are based on alpine:edge.

Docker itself is started with systemd: `ExecStart=/usr/bin/docker daemon --dns=192.168.30.253 --dns-opt=ndots:15 -H fd://`

Here are the relevant parts of my docker-compose.yml:
```
version: '2.1'

services:

  hub:
    image: ylavoie/hub
    container_name: hub
    privileged: true
    mem_limit: 200m
    memswap_limit: 400m
    ports:
      - 4422:4444
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub

  firefox:
    image: ylavoie/node-firefox
    container_name: firefox
    privileged: true
    mem_limit: 500m
    memswap_limit: 1g
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

networks:
  default:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 192.168.34.0/24
```

The commands to restart the application are, to make sure that the network is created anew each time:
```
docker-compose kill
docker-compose rm -f
docker network rm selenium_default
docker-compose up -d
```

And, although it has been failing for the last week, it now works without obvious changes, except a restart of the docker daemon to include the -D switch, as you required. I have removed it now, still working.

I am lost and may have to put that on hold until I can make it fail again.

**Comment by bmitch3020** [comment]
I ran into this one today. Running a centos:7 container on MacOS and docker edge:

```
$ docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

In the centos:7 container, I see:

```
[root@045b53d302b7 /]# ping testdb2
ping: testdb2: Name or service not known
```

I attached to the container with netshoot and ran a tcpdump to see that docker's DNS is responding with the address, but it appears that centos doesn't like it:

```
/ # tcpdump -nvvS -i any
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
21:13:10.309179 IP (tos 0x0, ttl 64, id 32706, offset 0, flags [DF], proto UDP (17), length 53)
    127.0.0.1.60529 > 127.0.0.11.43759: [bad udp cksum 0xfe3e -> 0xa845!] UDP, length 25
21:13:10.309510 IP (tos 0x0, ttl 64, id 42177, offset 0, flags [DF], proto UDP (17), length 53)
    172.19.0.2.60752 > 192.168.65.1.53: [bad udp cksum 0xadf1 -> 0xa26e!] 31609+ A? testdb2. (25)
21:13:10.310522 IP (tos 0x0, ttl 37, id 59761, offset 0, flags [none], proto UDP (17), length 91)
    192.168.65.1.53 > 172.19.0.2.60752: [udp sum ok] 31609 q: A? testdb2. 1/0/0 testdb2.*****.corp. A 10.1.10.74 (63)
21:13:10.310733 IP (tos 0x0, ttl 64, id 44973, offset 0, flags [DF], proto UDP (17), length 91)
    127.0.0.11.53 > 127.0.0.1.60529: [bad udp cksum 0xfe64 -> 0x5577!] 31609 q: A? testdb2. 1/0/0 testdb2.*****.corp. A 10.1.10.74 (63)
```

Changing ndots to 1 in /etc/resolv.conf resolves this issue. I'm still scratching my head for why centos doesn't like it since other containers resolve the name just fine.

**Comment by miekg** [comment]
~~~
    192.168.65.1.53 > 172.19.0.2.60752: [udp sum ok] 31609 q: A? testdb2. 1/0/0 testdb2.*****.corp. A 10.1.10.74 (63)
~~~
You ask for `testdb2.` and the response contains `testdb2.....corp.` a good resolver should not use that answer which is probably what happens here (dunno if centos has hardening patches again glibc)

**Comment by justincormack** [comment]
Cc @djs55 as may be specific to osx resolution.

**Comment by djs55** [comment]
@bmitch3020 @miekg @justincormack thanks -- it looks like the Mac resolver is being a little over enthusiastic. I've filed https://github.com/moby/vpnkit/issues/221

**Comment by bmitch3020** [comment]
@djs55 Thanks, that explains why the RHEL host didn't have this issue.

For anyone that comes across this, I've temporarily worked around it with the following in Preferences -> Daemon -> Advanced:

```
{
  "debug" : true,
  "experimental" : true,
  "dns-opts": ["ndots:15"]
}
```

**Comment by ylavoie** [comment]
Thanks you all for the explanations and tries.
I simplified my setup, I have 1 `internal` network for communication between the hub and the browsers and I am using `default` for communication with the Linux host.
Using the following config:
```
{
    "dns":     [ "192.168.30.253" ],
    "dns-opts": [ "ndots:1" ]
}
```
Results in the following `/etc/resolv.conf`
```
search ylavoie.com
nameserver 127.0.0.11
options ndots:1 ndots:0
```
The 2nd ndods nullifies the first and I'm back to square one, no name resolution except if names are fully qualified.
```
www-data@4e7e9059ef06:/srv/ledgersmb$ nslookup nameserver
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
*** Can't find nameserver: No answer

www-data@4e7e9059ef06:/srv/ledgersmb$ nslookup nameserver.ylavoie.com
Server:         127.0.0.11
Address:        127.0.0.11#53

Name:   nameserver.ylavoie.com
Address: 192.168.30.253

www-data@4e7e9059ef06:/srv/ledgersmb$ nslookup nginx
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   nginx
Address: 172.19.0.3

```
So I see 2 problems here:

1. ndots provided by the user must be appended to the list, not prepended.
2. search path isn't tried.

Removing the ndots:0 or putting it first fixes the issue.

**Comment by japrogramer** [comment]
I recently updated to this version
Version         : 1:17.06.0-1
and now i have the same problem.

some of my entry point scripts rally on name resolution so this is a big problem for me.

**Comment by NavinF** [comment]
Note that OP uses Alpine (musl libc) which does not handle "ndots" the same way glibc does in other distros: http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Name_Resolver_.2F_DNS

(IMO the solution to these search path woes is to quit using "intranet names". Instead, use FQDNs everywhere and don't depend on the search path to fix up your queries.)

**Comment by balexx** [comment]
@NavinF that's not a valid solution for us. We rely on short names to ensure name resolution is datacenter agnostic, and resolves to the local DC's domain first.

**Comment by jstewart612** [comment]
@NavinF I have to agree with @balexx .  You say stop using "intranet names", yet it is a perfectly valid and the only strategy most know of to achieve a datacenter-agnostic ask while resolving to specific places in specific orders.

+1 for this.  I am the person configuring it.  I should get to decide what ndots is.  I should get to decide which name resolution source is authoritative, not docker.  Perhaps, instead of us ceasing to use "intranet names", Docker should stop relying on a DNS hack to refer to internal networks!

**Comment by fcrisciani** [comment]
This https://github.com/docker/libnetwork/pull/2065 fixes the behavior, setting the user options if specified, else the default behavior will remain to have ndots:0

**Comment by borisovano** [comment]
Is there any solution for a single container (not altering global docker settings) in Compose 3?

looks like dns-opts is not implemented :/ 
(https://github.com/docker/compose/issues/3184)

**Comment by fcrisciani** [comment]
@Richard-Mathie should be mainly esthetic, it would not create behavior issue AFAIK

**Comment by Richard-Mathie** [comment]
@fcrisciani I have no idea why i would be mainly esthetic about this, its left me scratching my head. Either I cant remember as it was so long ago I was playing with and having issues with docker networking (C2016) or I worry you mean somebody else?

**Comment by thaJeztah** [comment]
@Richard-Mathie I _think_ @fcrisciani accidentally `@` mentioned you, but wanted to mention @rickatnight11.

FWIW; the "aesthetic" was about having multiple `ndots:0` entries in `resolv.conf`. That case should be fixed by https://github.com/docker/libnetwork/pull/2212

**Comment by fcrisciani** [comment]
yep @thaJeztah, sorry @Richard-Mathie :)

**Comment by Inversus93** [comment]
Im facing exactly this problem, but setting ndots via --dns-opts or in docker daemon.json doesn't fix it.

Creating a alpine container, starting a shell on it and changing ndots:0 to :1 manually, works.
Having ndots set to 1 in the docker command or config still results in the resolution failure, even though the setting is in the /etc/resolv.conf.

Am I doing something wrong?
Im on ubuntu and using docker 20.10.21

**Comment by akerouanton** [comment]
@Inversus93 This issue has been closed as resolved more than 5 years ago. Could you please create a new issue and provide the following:

* The complete output of `docker info` ;
* The `docker network create` command you used ;
* Your current `daemon.json` ;
* The `docker run` command you used ;

Also note that 20.10.21 reached end-of-life. Can you try on the latest version released (ie. 24.0.2) please?
