### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/

### ISSUE THREAD

**Issue by c0nscience** [moby/moby#32270]
**Description**

I try to create a docker container from an image from docker hub.

**Steps to reproduce the issue:**
1. `docker run hello-world`

**Describe the results you received:**
I would expect docker to pull the image and create a container out of it.

**Describe the results you expected:**
I got an connection timeout:
```
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

or sometimes that
```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
78445dd45222: Pulling fs layer
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/48/48b5124b2768d2b917edcb640435044a97967015485e812545546cbed5cf0233/data?Expires=1490975964&Signature=OUmibCvoXIlDlmt-GF187GDtJySfLIHJdgfs~GTyzARgOPaVYLfU8kLKKFnS3NczD39-PtCdTxEMKmE0IigxpsmDQimidTyuqOIlac-wDGhrLPveHoKIUYZ9QP9hzzAvRyhci9wrsWJJkrsOz3ITUaNRDM3z9xHyyQi07WQGLiQ_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: read udp 192.168.65.2:55172->192.168.65.1:53: i/o timeout.
See 'docker run --help'.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: B4O5:BZWR:JRKQ:ANPW:4FK4:ZS3Z:D3PV:7HUE:DADF:N3TJ:64MM:U5KQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-03-31T15:40:24.66843988Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by anonymuse** [comment]
Hi there -- it seems that Docker is doing the intended behavior:

> I would expect docker to pull the image and create a container out of it.

but is failing due to network issues or other insufficient error handling. Am I reading that correctly?

**Comment by thaJeztah** [comment]
>  on 192.168.65.1:53: read udp 192.168.65.2:55172->192.168.65.1:53: i/o timeout

IIRC there were some cases where DNS resolution failed on Docker for Mac, depending on the DNS server that was configured on the host; 

Can you try if it works if you set `8.8.8.8` as DNS server in the daemon configuration? You can set this by providing a JSON configuration in the preference panel (under daemon -> advanced), e.g;

```JSON
{ "dns" : [ "8.8.8.8", "8.8.4.4" ]}
```

**Comment by c0nscience** [comment]
@thaJeztah I got still the same result. One time it has worked, I guess it was a bit faster so the timeout could not kick in, but each time I get the same errors:

```bash
~ » docker run hello-world                                                                                                                                                                       bherzig@Apollo
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
78445dd45222: Pulling fs layer
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/48/48b5124b2768d2b917edcb640435044a97967015485e812545546cbed5cf0233/data?Expires=1491041188&Signature=Jr3KMnmwQAa0yeVBYc8rUdmCIMKcnsEKEy7jdegVZszObtBGipfMes97yZXtiwH9Jgm6e9sWKljWxNbqw-4Z7ntyjLnVYfsXXq~dz-DVH1wyqChk3czgh5UFXecZAFje6zgH6XEo4SpZjQ37XLmE70enZmNDa1INZQSiwyeqhgQ_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 192.168.65.1:53: read udp 192.168.65.2:54870->192.168.65.1:53: i/o timeout.
See 'docker run --help'.
```

```bash
~ » docker run hello-world                                                                                                                                                                       bherzig@Apollo
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

**Comment by thaJeztah** [comment]
Hm, no direct suggestions, but does look like a networking error in your setup

ping @djs55 any suggestions, or known issues on our side?

**Comment by c0nscience** [comment]
@thaJeztah yeah you are right. I've tried to download the hello world image from a LTE connection and not from the internet connection in my flat and it worked.
Hmm that is strange, I have a quite good internet connection and it has worked in the past.
Do you know how to figure out why it is not working from my normal internet connection?

**Comment by Ciscoadmin** [comment]
Hi, 
Seems  like   network issue
Edit  /etc/default/docker and put your proxy on it.

export http_proxy="http://proxy_ip:proxy_port"
export https_proxy="http://proxy_ip:proxy_port"

Then, restart the service:

service docker restart

**Comment by c0nscience** [comment]
I'll close that one here, because I've created a new ticket in the correct project: https://github.com/docker/for-mac/issues/1601

**Comment by mscomnet** [comment]
I had same issue while setting up dockers for first time ever and 
tried on two Ubuntu Server (16.04.3 Xenial) VM's in home network with same problem with pulling HELLO-WORLD image after fresh installing
and after few days for digging in much promised post for setting proxy in home NETWORK and none of these works
# setup proxing in home network where no proxy has been setup :), linux or windows or mac, proxy is same accross everywhere like internet :)
#curl  https://registry-1.docker.io/v2/ to see can get respose and setup credentials...

ubuntu@ubuntuserver:~$ docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
ubuntu@ubuntuserver:~$ cat /etc/systemd/system/docker.service.d/http-proxy.conf
cat: /etc/systemd/system/docker.service.d/http-proxy.conf: No such file or directory
ubuntu@ubuntuserver:~$ sudo nano /etc/resolv.conf

#add these lines on top and above one for home router...
nameserver 8.8.8.8
nameserver 8.8.4.4

#following command is must after updating resolv.conf...
ubuntu@ubuntuserver:~$ sudo systemctl daemon-reload 
ubuntu@ubuntuserver:~$ sudo systemctl restart docker
ubuntu@ubuntuserver:~$ sudo systemctl status docker
ubuntu@ubuntuserver:~$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
5b0f327be733: Pull complete
Digest: sha256:07d5f7800dfe37b8c2196c7b1c524c33808ce2e0f74e7aa00e603295ca9a0972
Status: Downloaded newer image for hello-world:latest
ubuntu@ubuntuserver:~$ docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.

:) .....

**Comment by julianrosebury** [comment]
docker pull hello-world.

I got this...

Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: rea
d udp [::1]:41859->[::1]:53: read: connection refused

I fixed it by quitting Docker from the tray, then simply restarting it.

**Comment by 1605200517** [comment]
@mscomnet  confirm that this works in a home proxyless network! resolv.conf was there but adding those two lines works for me on all machines!

**Comment by souravpatnaik** [comment]
may be you are behind a firewall/proxy server
i was  also behind my office firewall so i tried below steps which resolved this issue.

For setting up proxy for docker, please do the following:
1.   Create a systemd drop-in directory for the docker service:
     $ mkdir -p /etc/systemd/system/docker.service.d
     $ vim /etc/systemd/system/docker.service.d/http-proxy.conf
     Then add below content with proxy settings with it

[Service]
Environment="HTTP_PROXY=http://<allowed_proxy_ipv4_address>:<proxy_port_num>/"

2.   For  HTTPS proxy server:
$ vim /etc/systemd/system/docker.service.d/https-proxy.conf
Then add below content with proxy settings with it

[Service]
Environment="HTTPS_PROXY=https://<allowed_proxy_ipv4_address>:<proxy_port_num>/"

3.	Flush changes execute: $ sudo systemctl daemon-reload

4.	Restart Docker: $ sudo systemctl restart docker

5.	Verify that the configuration has been loaded: $ systemctl show --property=Environment docker

**Comment by Rohit2387** [comment]
Hi,
I am geting below error while i am deploying image through kubectl .directly running in docker it is coming up.Can you please let me know the reason.
Failed to pull image "postgres": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error syncing pod

**Comment by souravpatnaik** [comment]
@Rohit2387 , your machine is not able to reach the docker repository or having connection issues, try with diff. proxy or without proxy..
#]kubectl run postgres-image --image=postgres:latest
deployment "postgres-image" created
#]kubectl describe pod postgres-image-769495274-8n3dd

Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----				-------------			--------	------		-------
  7m		7m		1	default-scheduler						Normal		Scheduled	Successfully assigned postgres-image-769495274-8n3dd to host-10-19-170-244
  7m		1m		6	kubelet, host-10-19-170-244	spec.containers{postgres-image}	Normal		Pulling		pulling image "postgres:latest"
  6m		1m		6	kubelet, host-10-19-170-244	spec.containers{postgres-image}	Normal		Pulled		**Successfully pulled image "postgres:latest"**
  6m		1m		6	kubelet, host-10-19-170-244	spec.containers{postgres-image}	Normal		Created		Created container
  6m		1m		6	kubelet, host-10-19-170-244	spec.containers{postgres-image}	Normal		Started		**Started container**


for Error syncing pod.. , if you able to pull postgres image in your machine successfully, then try to create postgres pod using a yaml file, you should be careful about liveness and readiness probe to avoid this syncing pod error ..

**Comment by tcbabu** [comment]
so many but not a single right one. people are answering without any understanding of the issue

**Comment by maa105** [comment]
any updates? im behind corporate proxy, I tried using proxifier wich works for nodejs connections but with no luck. I'm just trying the hello world container nothing fancy here:
` docker run microsoft/dotnet-samples:dotnetapp-nanoserver `
Unable to find image 'microsoft/dotnet-samples:dotnetapp-nanoserver' locally
C:\Program Files\Docker\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\docker.exe run --help'.

**Comment by veresh** [comment]
Steps told by @souravpatnaik worked for me.
You need to create http proxy file and add the proxy server.

**Comment by qiangli** [comment]
It could be a "red herring".  Tried all the "solutions" - reinstall/mess with dns  - still failing.  After some time, tried again and it magically started working again. 
I believe either docker service or my network was temporarily down. So wait it out is another solution.

**Comment by montao** [comment]
Tried all the "solutions". Nothing works. This software is not mature. It should be able to configure behind proxy or firewall but no. Nothing work.

**Comment by garnetb** [comment]
Started having this issue after upgrading the version.  Resolved for me by logging out of DockerHub
<img width="294" alt="screen shot 2018-04-28 at 12 02 53 pm" src="https://user-images.githubusercontent.com/18415374/39389399-331ca810-4adc-11e8-9c75-4e8321ebeb04.png">

**Comment by tiotsop01** [comment]
Had this issue on ubuntu 14.04. Running the command `sudo service docker restart` worked for me

**Comment by tjb7** [comment]
I fixed this issue this way (Windows 10). I did the following: 
(1) set the DNS server to 8.8.8.8 in the docker configuration menu 
(2) ensured I had no proxy enabled (Search: Configure Proxy Settings, click LAN settings)
(3) restarted my machine

It is worth noting that when I do enable a proxy, I must change the docker configuration to DNS Server-Automatic

**Comment by Eltayeb-Karrar** [comment]
if you use windows go to docker icon in taskbar and right click and switch to windows container

**Comment by sashasimkin** [comment]
Still happening on `18.03.1.ce-3.fc28`

```
$ uname -a
Linux 4.17.5-200.fc28.x86_64 #1 SMP Tue Jul 10 13:39:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I've changed DNS, played with network interfaces, re-installed docker with cleaning up directories(`/var/lib/docker`) and `docker0` network. All with no luck.

_However_, If I start it as `sudo dockerd` - networking works as expected, i.e. `docker run hello-world` completes with message from the container.

**Comment by thaJeztah** [comment]
@sashasimkin wondering if it's related to https://github.com/docker/libnetwork/issues/2187 / https://github.com/docker/libnetwork/pull/2232. Also, if manually starting dockerd (not through systemd) works; check your systemd unit-file / configuration to see if there's possibly an option set that may interfere with networking (e.g. `HTTP_PROXY` environment variables, or other options)

**Comment by trillianjose** [comment]
@mscomnet thank you your answer solve my problems on Ubuntu.

**Comment by amandalmia14** [comment]
@all
@souravpatnaik 
Just an info.
The proxy doesn't work for the latest version '18.06.0~ce~3-0~ubuntu', however its working seamlessly in older version.

**Comment by frankh** [comment]
I had this issue caused by a bad login being saved.

`docker logout` fixed it

**Comment by amandalmia14** [comment]
@frankh Could you please tell us how did you fixed it?
Thanks

**Comment by sashasimkin** [comment]
Re-installing docker-ce helped with my problem, tho I haven't found out what exactly was the cause :(

I wasn't logged into any registry, and DNS was 8.8.8.8/1.1.1.1 always.

**Comment by wagnermarques** [comment]
In my case It was a typo in /usr/lib/systemd/system/docker.service because I am behind a proxy

[Service]
Type=notify
Environment="HTTP_PRO**YX**=...
Environment="HTTPS_PRO**YX**=...
Environment="FTP_PRO**YX**=...
Environment="ALL_PRO**YX**=..

To fix it:
1) Fix the typo
2) systemctl daemon-reload
3) systemctl restart docker

**Comment by hitzhangjie** [comment]
I reinstall docker new version .... it works.

**Comment by Applicafroguy** [comment]
Restarting docker resolved issue

**Comment by haris-git-hub** [comment]
to resolve the issue just restart the docker machine
command 
docker-machine restart

**Comment by cpurtlebaugh** [comment]
> To resolve this issue just restart your docker machine
> 
> command:
> docker-machine restart
> 
> It worked for me.

Restarting docker worked for me as well

**Comment by carljdp** [comment]
On Windows: Uninstall / reinstall solved it for me (+ setting proxy settings if on corporate network)

**Comment by Gunmx** [comment]
Hello,I sometimes use “$docker search php"，
it will return 
"Error response from daemon: Get https://index.docker.io/v1/search?q=php&n=25: net/http: TLS handshake timeout."I have change the Registry Mirrors(aliyun).But sometimes it very fast when i use "docker pull ...". 
what should i do, please?

**Comment by thaJeztah** [comment]
The search API used is specific to Docker Hub, and (I don't think) registry-mirrors will be used for that. 

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

**Comment by mohammadmasoumi** [comment]
I think it's ``Environment="HTTP_PROXY=..`` not ``Environment="HTTP_PROYX=..``

**Comment by sujithmp** [comment]
> > on 192.168.65.1:53: read udp 192.168.65.2:55172->192.168.65.1:53: i/o timeout
> 
> IIRC there were some cases where DNS resolution failed on Docker for Mac, depending on the DNS server that was configured on the host;
> 
> Can you try if it works if you set `8.8.8.8` as DNS server in the daemon configuration? You can set this by providing a JSON configuration in the preference panel (under daemon -> advanced), e.g;
> 
> ```json
> { "dns" : [ "8.8.8.8", "8.8.4.4" ]}
> ```

How will  set this in linux system?

**Comment by chetanyachopra** [comment]
**Resolved by Restarting docker service** 

```systemctl restart docker```

not a full proof solution but works anyways :yum:

**Comment by sandeep007734** [comment]
> I had same issue while setting up dockers for first time ever and
> tried on two Ubuntu Server (16.04.3 Xenial) VM's in home network with same problem with pulling HELLO-WORLD image after fresh installing
> and after few days for digging in much promised post for setting proxy in home NETWORK and none of these works
> 
> # setup proxing in home network where no proxy has been setup :), linux or windows or mac, proxy is same accross everywhere like internet :)
> #curl https://registry-1.docker.io/v2/ to see can get respose and setup credentials...
> 
> ```
> ubuntu@ubuntuserver:~$ docker pull hello-world
> Using default tag: latest
> Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> ubuntu@ubuntuserver:~$ cat /etc/systemd/system/docker.service.d/http-proxy.conf
> cat: /etc/systemd/system/docker.service.d/http-proxy.conf: No such file or directory
> ubuntu@ubuntuserver:~$ sudo nano /etc/resolv.conf
> ```
> 
> #add these lines on top and above one for home router...
> nameserver 8.8.8.8
> nameserver 8.8.4.4
> 
> #following command is must after updating resolv.conf...
> 
> ```
> ubuntu@ubuntuserver:~$ sudo systemctl daemon-reload 
> ubuntu@ubuntuserver:~$ sudo systemctl restart docker
> ubuntu@ubuntuserver:~$ sudo systemctl status docker
> ubuntu@ubuntuserver:~$ docker pull hello-world
> Using default tag: latest
> latest: Pulling from library/hello-world
> 5b0f327be733: Pull complete
> Digest: sha256:07d5f7800dfe37b8c2196c7b1c524c33808ce2e0f74e7aa00e603295ca9a0972
> Status: Downloaded newer image for hello-world:latest
> ubuntu@ubuntuserver:~$ docker run hello-world
> Hello from Docker!
> This message shows that your installation appears to be working correctly.
> ```
> 
> :) .....

This worked like a charm. I was earlier using proxy and then removed to a direct connection.
> sudo rm /etc/systemd/system/docker.service.d/http-proxy.conf

This was all that was required.

**Comment by vinaymorkar** [comment]
> > on 192.168.65.1:53: read udp 192.168.65.2:55172->192.168.65.1:53: i/o timeout
> 
> IIRC there were some cases where DNS resolution failed on Docker for Mac, depending on the DNS server that was configured on the host;
> 
> Can you try if it works if you set `8.8.8.8` as DNS server in the daemon configuration? You can set this by providing a JSON configuration in the preference panel (under daemon -> advanced), e.g;
> 
> ```json
> { "dns" : [ "8.8.8.8", "8.8.4.4" ]}
> ```

This worked for me!!

**Comment by cdaria** [comment]
It works for me: https://docs.docker.com/config/daemon/systemd/

**Comment by 4devsecops** [comment]
For those who are using a Proxy server in between. This is working for me

Add this in your `/etc/systemd/system/docker.service.d/http-proxy.conf`

```
[Service]
Environment="HTTP_PROXY=http://IP:PORT"
```

If there is an existing file, remove or comment out **HTTPS_PROXY** 

Reload Docker daemon: `systemctl daemon-reload` 
Restart Docker: `systemctl restart docker`

and try again

**Comment by b0o** [comment]
In my case, I was running Docker [in a separate network namespace](https://wiki.archlinux.org/title/Nftables#Working_with_Docker), and I had forgotten to [enable kernel IP packet forwarding](https://wiki.archlinux.org/title/Internet_sharing#Enable_packet_forwarding).
