### ISSUE TITLE
`docker service logs` stops showing logs from containers on different nodes

### ISSUE THREAD

**Issue by benturner** [moby/moby#33183]
**Description**
Running `docker service logs foo` on a swarm master where `foo` is a service with multiple replicas across different nodes eventually stops merging the logs from those other nodes. It seems to always work just fine right after the service is created.

**Steps to reproduce the issue:**
1. Create a service `foo` with replicas across multiple nodes
2. Run `docker service logs --follow foo`
3. Initially observe logs from multiple containers across different nodes
4. Go away and do something else for a while
5. Run `docker service logs --follow foo`
6. Observe old logs from multiple containers across different nodes but new logs only contain logs from the node on which you're running the command

**Describe the results you received:**
Logs from containers on the current node only

**Describe the results you expected:**
Logs from all containers on all nodes

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems to work fine at first but then within some amount of time it stops working. I've tried with both `json-file` and `journald` log drivers.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: jbsbgj3on5coa7f996rle8bpk
 Is Manager: true
 ClusterID: 7uzbzxfjt8nf6p18wbzv8ek84
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.0.5
 Manager Addresses:
  172.16.0.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636GiB
Name: swarmm-master-94917428-0
ID: NNL7:YHDL:5ALU:4ZXF:J3BL:VAIV:UI2T:TV5U:UGQL:UCQC:WWCP:TQDO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 149
 Goroutines: 310
 System Time: 2017-05-12T22:02:26.629917059Z
 EventsListeners: 7
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on azure using an acs-engine template (https://github.com/Azure/acs-engine). Currently just testing this so I'm using one manager and one worker node. The replicas for my service get split over both nodes.

**Comment by thaJeztah** [comment]
ping @dperny PTAL

**Comment by dperny** [comment]
Definitely a bug. @benturner about how long does it take for the logs to fall off? Also, since it's a test cluster, would it be possible for you to post daemon logs from about the time when you start the logs to the time when they fall off? If not, NBD, I will try to reproduce locally.

**Comment by benturner** [comment]
@dperny Yes I will try to grab some logs today. Thanks for looking into this.

**Comment by benturner** [comment]
Apologies, but I have tried and failed for a few days to get this to reproduce. I'll reopen if I can ever catch it. Thanks.

**Comment by thaJeztah** [comment]
Thanks! Keep us posted 👍

**Comment by yunghoy** [comment]
This issue reproduced in 17.06.x-ce ~ 17.06.2-ce.
Containers: 49
 Running: 42
 Paused: 0
 Stopped: 7
Images: 153
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 769
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ciagobmjzqaup5typm21rcnzu
 Is Manager: true
 ClusterID: 86ntnntsfirsvrhwhhzjuy8tv
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 3
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.88.15.79
 Manager Addresses:
  10.88.15.79:2377
  10.88.15.80:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.67GiB
Name: APSEO-EG-LINUX10
ID: XNBD:OS6A:OXQ6:RF5F:KW5S:VIRI:QT7M:SKTC:IK3J:WGVI:4H3K:TP6M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by thaJeztah** [comment]
@dperny ^^

**Comment by dperny** [comment]
Might be a dupe of #33203. @yunghoy does that other issue look like your problem?

**Comment by dobe** [comment]
hi, we have the sample problem. when a service gets moved, doing service logs on the machine that ran the previous task shows the old logs of that task instead of the running one.

```sh
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Comment by bloo** [comment]
We're experiencing this as well. Not only are we missing logs from `docker service logs` but they're not being sent to our log aggregator as well. Not all the time and I'm not sure how to reproduce it, but we see this often enough.

**Comment by jpmermoz** [comment]
I'm getting the same issue here.

Docker version 18.02.0-ce, build fc4de44

**Comment by thaJeztah** [comment]
@bloo wondering if it could be related to https://github.com/moby/moby/issues/35865

**Comment by mpalmer** [comment]
@thaJeztah I'd be surprised if they were related; this bug's been around since at least 17.05, while I'm fairly confident #35865 is only since 17.11.  At any rate, it's easy enough to check -- do the containers have processes hung on `write` syscalls to stdout or stderr?  If not, this bug isn't related to #35865.

**Comment by jtyr** [comment]
We experience the same problem (Docker version 17.12.1-ce, build 7390fc6). But if we user the _Service ID_ instead of the _Service Name_, the logs go through:

```bash
docker service logs -f $(docker service ls --format "{{.ID}} {{.Name}}" | grep myservicename | awk '{print $1}')
```

**Comment by blaskovicz** [comment]
@jtyr thanks for that, that's an excellent work around.

I have only one node in my docker swarm yet the "node <nodeid> not available" message hit me as well.

```
$ docker service ps coupon-clipper-stopandshop_web 
ID                  NAME                                   IMAGE                                              NODE                DESIRED STATE       CURRENT STATE          ERROR                              PORTS
nw70b8tebo3p        coupon-clipper-stopandshop_web.1       127.0.0.1:5000/coupon-clipper-stopandshop:latest   ZachVirtualBox      Running             Running 8 days ago                                        
```

```
$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
75e271bvg2t57wusmqn0groyo *   ZachVirtualBox      Ready               Active              Leader
```

**Comment by kongslund** [comment]
I experience the same on a standalone swarm using Docker 18.06.1-ce.

I have one container running and one that was terminated:
```
sudo docker service ps local-apt_go-apt-mirror
ID                  NAME                            IMAGE                            NODE    DESIRED STATE       CURRENT STATE            ERROR               PORTS
9kq98iroy7df        local-apt_go-apt-mirror.1       corp.local/go-apt-mirror:latest  apt     Running             Running 11 minutes ago
ebeouczzc5ad         \_ local-apt_go-apt-mirror.1   corp.local/go-apt-mirror:latest  apt     Shutdown            Shutdown 24 hours ago
```

When running `sudo docker service logs -f local-apt_go-apt-mirror`, I got the log of the terminated container.

**Comment by mazubieta** [comment]
This is affecting us, as well, on `18.06.1-ce, build e68fc7a`.  I can tail the logs using the id which technically is good enough for us to limp along with.

**Comment by IzaGz** [comment]
Also lost logs on the latest docker  docker-compose, - inly sevaral first lines is shown

**Comment by IzaGz** [comment]
anyone fixed this issue? i have logs working on my mac - but no logs on remote server

**Comment by wayne-o** [comment]
This seems to be a problem for me now and none of the above seems to help :/

**Comment by wayne-o** [comment]
So just remove each manager and add them back one by one? Or remove each node one by one?

W

**Comment by mariotacke** [comment]
Just ran into the same in a 3 manager cluster. For me, it turned out that one of my managers became unresponsive. I tried to demote it (which was unsuccessful because it was unresponsive) then rebooted its host and then promoted it again. Now logs are fine.

**Comment by gerassimos** [comment]
> 
> 
> When I run `docker service logs -f foo_bar` it spits out the log until some days ago. But this one works for me: `docker service logs -f --since 24h foo_bar` and it is tailing along. May help you until bug is fixed. I am running 18.06.1-ce, build e68fc7a on Ubuntu 16.04. (For me using the ID of the active service container didn't help; it stopped at some point yesterday).

I have exactly the same  problem . When I run `docker service logs -f foo_bar` it spits out the log until some days ago.  An other workaround for me is to use `docker service logs --tail 1000 foo_bar`.  I am running 18.09.0-ce,  on CentOS 7.5. The size of the log file of the related container is ~450M, maybe the size of the log file is a factor for this bug

**Comment by greinacker** [comment]
> When I run `docker service logs -f foo_bar` it spits out the log until some days ago. But this one works for me: `docker service logs -f --since 24h foo_bar` and it is tailing along. May help you until bug is fixed. I am running 18.06.1-ce, build e68fc7a on Ubuntu 16.04. (For me using the ID of the active service container didn't help; it stopped at some point yesterday).

This works for me, on 18.09.1, with a caveat, which could potentially be a clue to what the issue is. If this is my current state (just a snippet, there are multiple instances of the service on multiple machines):

```
ID                  NAME                CURRENT STATE
h454joroxko6        tv_web.1            Running 20 minutes ago
xegys2ytn8hi         \_ tv_web.1        Shutdown 30 minutes ago
pq4n2mmxnxn8         \_ tv_web.1        Shutdown about an hour ago
```

Note the currently running service has only been up for 20 minutes.

If I do `docker service logs -f --since 24h tv_web`, I get stale logs from the old containers. Same if I even do `docker service logs -f --since 1h tv_web`. 

But if I make the the "since" doesn't go farther back then the start time of the running service, so in this case say 10m:

`docker service logs -f --since 10m tv_web`. 

Then all will be well, and the current logs will tail.

**Comment by cmsalmeida** [comment]
Same problem here, any solution?

Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by davidxianggao** [comment]
Same problem...

Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by atmosx** [comment]
Same with 18.09.2.

**Comment by steffen201706** [comment]
docker service logs stops complete on
~$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by steffen201706** [comment]
FYI: after a restart of my manager nodes (only the manager not the worker !!!) docker service logs is back   :-)

**Comment by mhs1** [comment]
Same problem. 
My `docker info`

```
Containers: 16
 Running: 5
 Paused: 0
 Stopped: 11
Images: 16
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: hpeqm6pd0u7nck36weq0m5hm9
 Is Manager: true
 ClusterID: j7219palyo2fc017qh6f1i3ex
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: *******
 Manager Addresses:
  *******:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683b971d9c3ef73f284f176672c44b448662
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.83-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65GiB
Name: docker-hosting-02
ID: KLIX:PHSI:DOL2:G52B:F2I2:O3XM:4DEZ:4ECY:XUXZ:PZSI:TWJO:73O2
Docker Root Dir: /mnt/data/docker-files
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by andersthorbeck** [comment]
I'm experiencing the same issue when attempting to retrieve the logs from a specific task.
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:42 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

```
$ docker service logs p7p1741pdwm7ack5g1i4ttxem
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node w5z7b2tpte79d01ugg4916imc is not available
```
But adding the `-f` flag yields logs
```
$ docker service logs -f p7p1741pdwm7ack5g1i4ttxem
…logs shown…
```

**Comment by Petthan** [comment]
Same problem here

`Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

**Comment by Petthan** [comment]
Same problem here

```Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by Cassianosricardo** [comment]
Same here in my production cluster.

5 managers and 2 workers.

All 18.09.6 docker engine
```shell
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
dtgr020ucboipsjo21s6260e4 *   prod-man-1          Ready               Active              Reachable           18.09.6
padmp7niinj826rk4fuc3ya8w     prod-man-2          Ready               Active              Leader              18.09.6
ijepgdgjsu7dw4vfpb7kepae1     prod-man-3          Ready               Active              Reachable           18.09.6
8cyo77y1ysvwet3afk1jobepe     prod-man-4          Ready               Active              Reachable           18.09.6
nmkosjwyj4ojr8z715cy4g7bh     prod-man-5          Ready               Active              Reachable           18.09.6
iczt34h39egwlxb964aomiy2b     prod-worker-1       Ready               Active                                  18.09.6
y7hm9iihad8w20se8q8566sd5     prod-worker-2       Ready               Active                                  18.09.6
```

docker service ps service

```shell
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE         ERROR               PORTS
dee00ioz34zc        dash_redis.1        redis:4.0-alpine    prod-worker-1       Running             Running 12 days ago                       
```
Service is running fine, but when i try to retrieve logs i get:

```shell
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node iczt34h39egwlxb964aomiy2b is not available
```
Node is active and running fine:

docker node inspect 

```shell
[
    {
        "ID": "iczt34h39egwlxb964aomiy2b",
        "Version": {
            "Index": 7891
        },
        "CreatedAt": "2019-05-17T14:58:12.554496664Z",
        "UpdatedAt": "2019-06-02T18:50:43.569971399Z",
        "Spec": {
            "Labels": {
                "redis_node": "1"
            },
            "Role": "worker",
            "Availability": "active"
        },
        "Description": {
            "Hostname": "prod-worker-1",
            "Platform": {
                "Architecture": "x86_64",
                "OS": "linux"
            },
            "Resources": {
                "NanoCPUs": 1000000000,
                "MemoryBytes": 3872567296
            },
            "Engine": {
                "EngineVersion": "18.09.6",
                "Plugins": [
                    {
                        "Type": "Log",
                        "Name": "awslogs"
                    },
                    {
                        "Type": "Log",
                        "Name": "fluentd"
                    },
                    {
                        "Type": "Log",
                        "Name": "gcplogs"
                    },
                    {
                        "Type": "Log",
                        "Name": "gelf"
                    },
                    {
                        "Type": "Log",
                        "Name": "journald"
                    },
                    {
                        "Type": "Log",
                        "Name": "json-file"
                    },
                    {
                        "Type": "Log",
                        "Name": "local"
                    },
                    {
                        "Type": "Log",
                        "Name": "logentries"
                    },
                    {
                        "Type": "Log",
                        "Name": "splunk"
                    },
                    {
                        "Type": "Log",
                        "Name": "syslog"
                    },
                    {
                        "Type": "Network",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Name": "host"
                    },
                    {
                        "Type": "Network",
                        "Name": "ipvlan"
                    },
                    {
                        "Type": "Network",
                        "Name": "macvlan"
                    },
                    {
                        "Type": "Network",
                        "Name": "null"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Volume",
                        "Name": "local"
                    }
                ]
            },
            "TLSInfo": {XXXXXX}
        },
        "Status": {
            "State": "ready",
            "Addr": "10.142.0.12"
        }
    }
]
```

Any workarounds?

I don't wanna restart this node unless is necessary.

Thanks.

**Comment by alegri90** [comment]
@Cassianosricardo -- Encountered this once in our staging cluster and once in production. 
I haven't found restarting the node to work either. The logging still was not reachable through `docker service logs`. I had to find the faulty manager node, disconnect it from the cluster (`docker swarm leave`), reboot and join again (and promoting to manager again). 

Luckily, logging didn't stop for logspout-logstash, so our ELK still got everything.

**Comment by Cassianosricardo** [comment]
> @Cassianosricardo -- Encountered this once in our staging cluster and once in production.
> I haven't found restarting the node to work either. The logging still was not reachable through `docker service logs`. I had to find the faulty manager node, disconnect it from the cluster (`docker swarm leave`), reboot and join again (and promoting to manager again).
> 
> Luckily, logging didn't stop for logspout-logstash, so our ELK still got everything.

Thanks for the answer. 

What do you mean by the faulty manager node? Do you think a manager is causing the issue, not the worker itself?

**Comment by apavlis** [comment]
I am encountering this issue as well.  When I run `docker service logs <service> -t -f` I see logs from about two weeks ago.  Using -f stops at that point and doesn't display anything past that date.

We are considering switching to syslog since it seems docker's logging is just far too unreliable to deal with, considering the age of the product.

There was server patching that occurred about two weeks ago via a rolling patch process that required rebalancing after the fact. It looks like it stopped at that time as the last service log entry is from 6/12.

I can run `docker logs <containerID>` on a mgr/worker node and see newer logs, as well as see updated logs in the individual container's `/var/lib/docker/containers/ID` dirs.  Initially I thought maybe the firewall got re-enabled, but it looks the same as before the patching.

While checking something for this writeup, I noticed if I run
`docker service logs -t -f <service> --since 24h`
it appears to display the latest logs.  So at least there's a kludgy workaround.

This is 18.09.6, build 481bc77156:

```
-bash-4.2$ docker info
Containers: 164
 Running: 20
 Paused: 0
 Stopped: 144
Images: 52
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: ...
 Is Manager: true
 ClusterID: ...
 Managers: 3
 Nodes: 7
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.x.a
 Manager Addresses:
  192.168.x.a:2377
  192.168.x.b:2377
  192.168.x.c:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.12.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: ...
ID: RJR7:F2FE:ZOBL:4GEB:URG6:IEDY:4EQA:64D7:2LKF:2X3Q:O6VM:WIRS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

-bash-4.2$ docker --version
Docker version 18.09.6, build 481bc77156
```

**Comment by iautom8things** [comment]
We ultimately decided to switch to kubernetes.  We're a small team, and really wanted to avoid the complexity of k8s.  But honestly, it's been quite a pleasure to work with.  I wish everyone luck that this gets addressed ... really frustrating to have this issue sit for so long

**Comment by PhilipGarnero** [comment]
Same issue here... Connectivity issues on one of our nodes causes the loss of our logs pretty often.

**Comment by ripper2hl** [comment]
so if you need see log for emergency you can use the classic

`docker log -f container-id`

obviously you need an session in the docker node where run the container

You find the node with the next command

`docker stack ps stackname`

same problem but i use suse package :cry: 

```log
Containers: 59
 Running: 22
 Paused: 0
 Stopped: 37
Images: 291
Server Version: 18.06.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.18.2+20150430
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: vk2j3y71fx51kk0njcpxjr0mo
 Is Manager: true
 ClusterID: qpih12g0fxuqqey42638fvvkb
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.17.1.108
 Manager Addresses:
  172.17.1.108:2377
  172.17.1.175:2377
Runtimes: oci runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: v0.1.3_catatonit (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.175-94.79-default
Operating System: SUSE Linux Enterprise Server 12 SP3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.585GiB
Name: srvdockerintra01
ID: 3MRA:H6E2:ZZ6O:5OYB:NYO2:2OZJ:KQ47:3D2O:LVH5:65JE:IOQ4:LMAZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false

 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support

```

**Comment by JavierPandu** [comment]
2 and a half years after, the problem persists. No workaround works for me.. Anyone has something that is not rebooting?

**Comment by Cassianosricardo** [comment]
> 2 and a half years after, the problem persists. No workaround works for me.. Anyone has something that is not rebooting?

@JavierPandu Unfortenetely not. Actually rebooting does not solve the problem. You could drain the node, so the services would boot in another node, then leave the faulty node from the swarm, restart docker service and then join it again.

It is really frustrating this is still happening often.

**Comment by ripper2hl** [comment]
> 2 and a half years after, the problem persists. No workaround works for me.. Anyone has something that is not rebooting?

try   `docker log -f container-id`

**Comment by PhilipGarnero** [comment]
We figured out kind of a solution for now but it basically means not relying on docker service for logs.

We're using **fluentd** to push all logs coming out from docker into **elasticsearch**. Then we can watch logs using `docker service logs` and fallback to elasticsearch when the logs are down.

**Comment by ripper2hl** [comment]
> We figured out kind of a solution for now but it basically means not relying on docker service for logs.
> 
> We're using **fluentd** to push all logs coming out from docker into **elasticsearch**. Then we can watch logs using `docker service logs` and fallback to elasticsearch when the logs are down.

I use ELKB without problems

https://www.elastic.co/blog/enrich-docker-logs-with-filebeat

**Comment by JavierPandu** [comment]
Guys, too early to be sure, but I think explicitly setting the logger config made it work for me.
`logging:
        driver: "json-file"
        options:
            max-file: 1
            max-size: 20m`

**Comment by javacspring** [comment]
same with 19.03.4 in centos7.4

**Comment by jaschaio** [comment]
Same here, Docker 19.03.04 on Ubuntu 18.04.

Logs work for a couple of hours but then stop. If I check the container logs manually they are all there. Only via `docker service logs` on a manger node I can't see anything after a certain point in time.

**Comment by alancnet** [comment]
Same here, Docker 19.03.5 on CentOS 7.

I have to connect to directly to worker nodes to get logs from the container directly. Using portainer for that now. Pity me.

**Comment by rdehouss** [comment]
Same here
All of a sudden, it stopped working while I was checking the logs of a service I'm trying to get working. So, I did multiple `docker service logs -f my_service` and it was working then not anymore...

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 12
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: eqj1bchzo0qpvfsgugfvwi414
  Is Manager: true
  ClusterID: y63ueh5wi9ontq2kpg3l05ngd
  Managers: 3
  Nodes: 7
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.16.0.136
  Manager Addresses:
   172.16.0.135:2377
   172.16.0.136:2377
   172.16.0.95:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-12-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.654GiB
 Name: swarm-manager-002
 ID: A7QD:SFIH:ZZCC:C5RG:3ZAB:F4B3:PLXA:65Z5:2OKQ:NPQO:BB2P:VCR2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by jaschaio** [comment]
Not sure if this is related to #35011 but rotating the swarm certificates via `docker swarm ca --rotate` does help in this case as well.

**Comment by ashabbir** [comment]
still happens alot
:(

**Comment by gentunian** [comment]
Same here: 

`Docker version 19.03.11, build 42e35e61f3`

> Not sure if this is related to #35011 but rotating the swarm certificates via `docker swarm ca --rotate` does help in this case as well.

Sadly this didn't solve the issue. Logs are not showing when `docker service logs ...`. I did disable firewall rules just in case but no, no logs output :(

**Comment by 357711589** [comment]
Same  here
```
Docker version 19.03.11 
APIVersion  1.40
```

**Comment by rdehouss** [comment]
Indeed, tried demoting / promoting and the logs "came back": https://github.com/moby/moby/issues/35932#issuecomment-517299052

The issue happened after (re-)deploying a stack/service multiple times (10+)

**Comment by drmrbrewer** [comment]
I have a single Manager node (on which my persistent volumes are and key services like postgres), and I scale up to create one more more Worker nodes.  At present `docker service logs` has stopped working.  I'm not 100% sure how I resolve this... can I promote a Worker to a Manager, then demote the original Manager to a Worker then back to a Manager?  I am not experienced enough to know how this will affect access to key persistent volumes on the current Manager node.

**Comment by patrickmglynn** [comment]
Same issue in `Docker version 19.03.14, build 5eb3275d40` on Ubuntu 18.04.

Re-balancing a Swarm service with the below command causes all logs to become available again via `docker container logs` and also via Loki:
`docker service update <service name> –force`

It looks like this may be a limitation of the Community Edition as per: https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers

**Comment by velychkovsky** [comment]
Hi, has anyone found how to fix this bug ?

`docker service logs my_service `  

Just hangs in the random moment on infinite time ( est. 3-4 days after service deploy). 

**docker version**
```Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:05 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:34 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**docker info**
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: *******
  Is Manager: true
  ClusterID: ******
  Managers: 3
  Nodes: 31
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 20
  Dispatcher:
   Heartbeat Period: Less than a second
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.1
  Manager Addresses:
   10.0.0.1:2377
   10.0.0.2:2377
   10.0.0.3:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-14-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.606GiB
 Name: worker-manager1
 ID: H4CQ:XA6H:6AQZ:VFJG:W4VC:ECXM:V6ND:SYK5:LWRR:7F67:NL7U:SNHA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
Docker debug log shows: 

> time="2021-04-22T11:20:14.812774419Z" level=debug msg="Calling GET /v1.40/services/my_service/logs?details=1&stderr=1&stdout=1&tail=all"

**Comment by tunstek** [comment]
Somehow this still seems to be an issue.

Adding the `--since` flag fixes it.

eg: `docker service logs -tf <service> --since 24h`

**Comment by muhammadsiddiqbe** [comment]
just remove the stack and redeploy

**Comment by bluepuma77** [comment]
Same here, service logs stopped working after heavy container rotation after network outage.

`docker service logs -tf --since 24h <service>` did not help

`docker swarm ca --rotate` did not help

`docker service update --force <service>` did not help

All bare metal servers running Debian, currently 115 Docker Swarm services, 475 containers
```
ID    HOSTNAME       STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
1     server11       Ready     Active                          20.10.17
2     server12       Ready     Active                          20.10.17
3     server13       Ready     Active                          20.10.17
4     server50       Ready     Active                          20.10.8
5 *   server51       Ready     Active         Reachable        20.10.7
6     server52       Ready     Active         Reachable        20.10.7
7     server53       Ready     Active         Leader           20.10.7
8     server54       Ready     Active                          20.10.6
9     server55       Ready     Active                          20.10.6
```

**Comment by clay-moss** [comment]
@bluepuma77 Are you still experiencing this issue? Can you share a daemon stack trace from your managers if so please:

- https://docs.docker.com/config/daemon/#force-a-stack-trace-to-be-logged

Thanks

**Comment by fiftin** [comment]
I have same problem with `docker service logs -f xxx`.

But `docker logs -f xyz` for same container works file.

**Comment by RensTillmann** [comment]
I am no docker expert by any means, so don't ask me anything about it.
But it is a very anoying problem and I want to share what I do when it happens.

I sometimes use the below command, which does work sometimes, but not always, perhaps it might work for you.
```
watch -t docker logs --tail 500 process_name.1.xxxxxxxxxxxxx
```

For me to make the `docker service logs` work on my swarm cluster (3 nodes) I have to demote the `Leader`.
Then restart docker service on that node. Wait till it is ready and reachable.
Then promote to master again. 

So the commands are along the lines of:

```
docker node demote managerX
systemctl restart docker
docker node promote managerX
```

I run the below to make sure all the 3 nodes run the service
```
docker service scale my_service=4
docker service scale my_service=3
```

Perhaps it helps someone 👍

**Comment by keltakmaster** [comment]
> I am no docker expert by any means, so don't ask me anything about it. But it is a very anoying problem and I want to share what I do when it happens.
> 
> I sometimes use the below command, which does work, but it's anoying because on a cluster (3 nodes in my case) I have to log thre processes. Since the service is load balanced, but it does work.
> 
> ```
> watch -t docker logs --tail 500 process_name.1.xxxxxxxxxxxxx
> ```
> 
> For me to make the `docker service logs` work on my swarm cluster (3 nodes) I have to demote the `Leader`. Then restart docker service on that node. Wait till it is ready and reachable. Then promote to master again.
> 
> So the commands are along the lines of:
> 
> ```
> docker node demote managerX
> systemctl restart docker
> docker node promote managerX
> ```
> 
> I run the below to make sure all the 3 nodes run the service
> 
> ```
> docker service scale my_service=4
> docker service scale my_service=3
> ```
> 
> Perhaps it helps someone 👍

This did the job for me! Thanks

**Comment by Radiergummi** [comment]
Has anyone since looked into this problem?

**Comment by clay-moss** [comment]
@Radiergummi  I believe this should be fixed by https://github.com/moby/moby/pull/42537

Available in Docker CE 20.10.8 and later: https://docs.docker.com/engine/release-notes/20.10/#20108

**Comment by PhilippeNoel1** [comment]
This does not fix the problem. I use v24.0.6 and still have the issue.

**Comment by raymondsryang** [comment]
24.0.7, still have the issue

**Comment by pharapeti** [comment]
24.0.5 same issue

**Comment by minakolta** [comment]
Any news about this issue ? It is happening as well in v24.0.6

**Comment by mr-moon** [comment]
v27.2.0 - same issue. Loosing logs.

**Comment by spiccrix** [comment]
Version 24.0.7: Same issue

The old task logs are only visible on the node where the shutdown task was running when executing docker service logs <service>. If I demote the node and then re-promote it, I lose access to the logs, even when attempting to retrieve them from that same node.

**Comment by drleon** [comment]
Same here:
```
ID                            HOSTNAME                STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
8guhyzo2unemlsso7tr2v1d3x *   server-01.localdomain   Ready     Active         Leader           27.3.1
50qd9cgitn5tfxx3wcdksalmi     server-02.localdomain   Ready     Active                          27.3.1

```

**Comment by mahnunchik** [comment]
Any news?
