### ISSUE TITLE
devicemapper:  When docker service run a long time, could not restart docker service.

### ISSUE THREAD

**Issue by moypray** [moby/moby#33603]
**Description**
We use `devicemapper` as graph driver and run stable test as below:
1.  create/delete containers continuously.
2.  restart docker service randomly.

After one night, the docker could not startup.

The error is
```
messages:2017-06-07T10:41:43.932549+00:00 V2R1C00B052-GUESTOS-FS-KVM-X64 docker: time="2017-06-07T10:41:43.747631527Z" level=debug msg="devmapper: Error device setupBaseImage: devmapper: Base Device UUID and Filesystem verification failed: devicemapper: Can't set cookie dm_task_set_cookie failed"
messages:2017-06-07T10:41:43.932765+00:00 V2R1C00B052-GUESTOS-FS-KVM-X64 docker: time="2017-06-07T10:41:43.747827726Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devmapper: Base Device UUID and Filesystem verification failed: devicemapper: Can't set cookie dm_task_set_cookie failed"
```

And more, I tried to use `dmsetup remove ` to remove some device:
```
V2R1C00B052-GUESTOS-FS-KVM-X64:~ # dmsetup remove docker-8:2-402190-9623ed2972fa4f700eec99e1404959a5b7e64eac65d3ff541b22f6271c2ee38a
Limit for the maximum number of semaphores reached. You can check and set the limits in /proc/sys/kernel/sem.
Command failed
V2R1C00B052-GUESTOS-FS-KVM-X64:~ # 
```

So I use `ipcs` to check the ipcs:
```
V2R1C00B052-GUESTOS-FS-KVM-X64:~ # ipcs

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status

------ Semaphore Arrays --------
key        semid      owner      perms      nsems
0x0d4d3358 238977024  root       600        1
0x0d4d0ec9 270172161  root       600        1
0x0d4dc02e 281640962  root       600        1
0x0d4db8d2 291045379  root       600        1
0x0d4d4e76 291864580  root       600        1
0x0d4d825a 292388869  root       600        1
0x0d4d93ee 294256646  root       600        1
0x0d4da4a1 294879239  root       600        1
0x0d4d4125 295305224  root       600        1
.......
-->  128 cookie leaks, not list here.
......
```

And  use `dmsetup udevcookies` to see the same as ipcs.  `cat /proc/sys/kernel/sem`
```
V2R1C00B052-GUESTOS-FS-KVM-X64:~ # cat /proc/sys/kernel/sem
250     32000   32      128
V2R1C00B052-GUESTOS-FS-KVM-X64:~ # 
```

It is `128`, so I echo an larger number of sem, it works:
```
echo 250 32000  32  1024 > /proc/sys/kernel/sem
```

And then Docker could startup.

So I supposed that there are `semaphore leaks` in DM. But I am not sure how does it happen..

And BTW, I could use `dmsetup udevcomplete_all` to cleanup all the leaks to recover the environment.
But I think we should work out an solution against this situation.

**Steps to reproduce the issue:**

1.   create/delete containers continuously.
2.  kill docker randomly.

After some time, use  `dmsetup udevcookies` to check if there is `semaphore leak` exists.

On other environment, We found leaks too. but very small (less than 10). 

**Describe the results you received:**
`semaphore leak` was found  and reached the limit number, docker could startup.

**Describe the results you expected:**
No `semaphore leak`, or cleanup it at docker startup.
docker could works fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@localhost:~/workspace/huawei/docker# docker version
Client:
 Version:        1.11.2
 API version:    1.23
 Go version:     go1.7.1
 Git commit:     ff25c8a
 Built:          Thu Jun  8 15:37:09 2017
 OS/Arch:        linux/amd64

Server:
 Version:        1.11.2
 API version:    1.23
 Go version:     go1.7.1
 Git commit:     3515a27-unsupported
 Built:          Thu Jun  8 16:28:37 2017
 OS/Arch:        linux/amd64
```

**Output of `docker info`:**

```
root@localhost:~/workspace/huawei/docker# docker info
Containers: 210
 Running: 0
 Paused: 0
 Stopped: 210
Images: 11
Server Version: 1.11.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Hugetlb Pagesize: 2MB
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.0
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: localhost
ID: LB2C:RVJO:DK5F:GVNI:QFYC:DTII:C3UB:6QHS:754W:LE3G:BKPP:EUIY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 25
 System Time: 2017-06-09T01:43:24.994823746+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by moypray** [comment]
I have read a little the `lvm2` code. The sem is created by `set cookie`,  release in `udev_wait`,

If docker was killed during set cookie and udev wait,  there maybe sem leak. But how to fix it ?

**Comment by thaJeztah** [comment]
I think there's an open pull request for some change in device mapper, but not sure if that's related; https://github.com/moby/moby/pull/32151

What version of docker are those servers running on? It looks like you reported information about a different host (one that is not running device mapper) Can you update the information to prevent confusion?

**Comment by thaJeztah** [comment]
(In case other changes were merged in this area; a naive search https://github.com/moby/moby/pulls?utf8=✓&q=is%3Apr%20cookie%20devicemapper%20)

**Comment by moypray** [comment]
@thaJeztah  Thanks for your reply. 
 #32151 is not the same issue. the PR is to fix the dm operation took a long time, and add a timeout.

My issue is between the operation and udev_wait, the docker got killed. 
The semaphore could not been deleted (created in lvm2, when Dm operation with a cookie, will create a semaphore)

I used 1.11.2 version ,but we have cherry-pick all the DM patches from master branch.

**Comment by thaJeztah** [comment]
It was just a "wild shot"; I've not educated myself enough in the device mapper internals. Let me copy Brian and Vivek, who are better suited to think along 👍 

/cc @cpuguy83 @rhvgoyal PTAL

**Comment by rhvgoyal** [comment]
No idea how a cookie/semaphore is leaking. I think you will have to narrow it down a bit for me.

**Comment by moypray** [comment]
Hi @rhcarvalho  I think the semaphore is allocated when an operation is with cookie:
https://github.com/steven676/lvm2/blob/android-lvm-mod/libdm/libdm-common.c#L2216
https://github.com/steven676/lvm2/blob/android-lvm-mod/libdm/libdm-common.c#L2078

Take deactivate as example:
https://github.com/steven676/lvm2/blob/android-lvm-mod/libdm/libdm-deptree.c#L961


And the cookie is released in `udev_wait`,
https://github.com/steven676/lvm2/blob/android-lvm-mod/libdm/libdm-common.c#L2283
https://github.com/steven676/lvm2/blob/android-lvm-mod/libdm/libdm-common.c#L2039


We emulate the docker got crashed or OOM, (so randomly killed docker daemon). 
If docker was killed when it was executing an DM operation(like deactivate with a cookie) and before udev_wait was called. An semaphore will be leaking.

**Comment by rhcarvalho** [comment]
@moypray I think you meant @rhvgoyal ;)

**Comment by rhvgoyal** [comment]
@moypray But in real life, I don't think docker is crashing? So real root cause of leaking semaphores is probably something else. 

Try going through journal logs and see something fishy is there. Like systemd killed a udev rule and it never completed.

**Comment by moypray** [comment]
@rhvgoyal   For my case, our IV team engineer runs robust test, they start container continuously and `kill docker` randomly( for example every 5 mins to kill docker, and restart docker).

I do not have much useful logs as the test run for one night and if docker begin to fail to startup. It would be restarted continuously by systemd and generate GB logs.

**Comment by rhvgoyal** [comment]
@moypray If you kill docker daemon, it can leak semaphore and dm tables that will require manual cleanup. So frequently killing docker daemon is not a good idea. Expect resource leak and will require manual intervention to clean it up.

I am more concerned about leak if it happens even if process is not terminated abruptly.

**Comment by moypray** [comment]
@rhvgoyal  I think if the operation is blocking in kernel/udev, it won't have chance to finish `udev_wait` (only wait the semaphore).  Maybe we could leak. So I think https://github.com/moby/moby/pull/32151 is helpful for docker not blocking in DM operation (Do not solve leak issue).

But I am not sure about this, not familiar with DM in kernel space.

**Comment by hqhq** [comment]
@moypray You reported a devicemapper issue but the docker version you printed was using overlay2, that's the confusion @thaJeztah mentioned.

**Comment by pouicr** [comment]
Hi,

I encountered the same problem on docker-ce 17.06/centos 7.3 after setting up devicemapper on a separate disk.
After some containers it starts appearing. 
I managed to restart some containers after using `echo 'y' | sudo dmsetup udevcomplete_all`.
But it now failed each time I want to start a new container (sad for a gitlab runner!).

Is there a long time work around or should I switch to another FS? 
The docker doc explain that docekr-ce on CentOS should use DM: [https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce) 

Thanks for your help

**Comment by pboos** [comment]
Having the same problem on centos 7.3.1611. Really annoying. Can't start new containers anymore. always have to run that command sudo ```echo 'y' | sudo dmsetup udevcomplete_all``` to get them up. So a solution would help us greatly as well.

**Comment by rhvgoyal** [comment]
We had found out one issue with cookies leaking and fixed it. Do you know if this fix is present in docker you are using.

https://github.com/moby/moby/pull/33732

**Comment by ericparton** [comment]
@rhvgoyal Do you know which versions contain the fix? I'm running 17.06.0-ce and I still see the issue.

**Comment by gtirloni** [comment]
It's hard to say how Docker CE gets built nowadays. The release tags for github.com/moby/moby don't list any v17.06.0 there. The specific commit from PR#33732 doesn't seem to be in any tag so far.

The fix is available in package docker-1.12.6-32 from RHEL/CentOS.

**Comment by cpuguy83** [comment]
Looks like that one got missed.
https://github.com/docker/docker-ce/commits/17.06/components/engine/pkg/devicemapper

**Comment by mkobit** [comment]
We see it in 17.06.0-ce as well.

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-50535400-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 386.5MB
 Data Space Total: 107.4GB
 Data Space Available: 27.86GB
 Metadata Space Used: 847.9kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26GiB
Name: ip-10-0-6-172
ID: FVV3:HC2U:WJYM:3MUJ:QUAO:7QB2:IB37:A46F:ZDGM:7LUX:6KF5:J2RK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

```
docker run alpine:3.6
Unable to find image 'alpine:3.6' locally
3.6: Pulling from library/alpine
88286f41530e: Extracting [==================================================>]   1.99MB/1.99MB
docker: failed to register layer: devmapper: Error activating devmapper device for '44c920b0f7b9007935f246ccf446991f877613a7478d90da652b9a13c14023b3': devicemapper: Can't set cookie dm_task_set_cookie failed.
```

**Comment by thomas-oo** [comment]
Almost identical setup as above, docker v17.06.0-ce and on RHEL 7.2, I'd like to add that this problem has occurred recently when using docker stack and repeatedly starting and stopping stacks. In fact, the problem occurs on my manager and worker nodes.

**Comment by svscorp** [comment]
Same here, RHEL 7.3

**Comment by hatdropper1977** [comment]
# Suggested permanent fix?
I fixed this issue by simply upgrading my Linux kernel from 3.10.0 to 4.4.83 (Current LT).

Background info:
- I faced this very issue when I upgraded from **_Docker version 1.13.1-cs4, build e46aec0_** to _**Docker version 17.06.1-ce, build 874a737**_ 
- Unmounting all docker volumes and then restarting the daemon provided a short lived fix
 - It worked for one run of _**docker-compose**_ and then broke on the second
- Running the following command provided a temporary fix as well, I needed to run it before each **__docker_compose__** build.
```bash
$ echo 'y' | sudo dmsetup udevcomplete_all
```
 - I initially upgraded the kernel from 3.10.0 to 3.10.107.  This _**did not**_ fix the issue.

**Comment by VuokkoVuorinnen** [comment]
@hatdropper1977 are you sure that upgrading docker-ce to 17.06.1 didn't fix the issue?

I was facing this issue with centos7.3 and docker-ce 17.06.0. Did a yum update (which also updated my kernel to 3.10.0-514.26.2.el7) and can't seem to reproduce it now (might need to wait until some more docker containers have been spawned)

**Comment by hatdropper1977** [comment]
@VuokkoVuorinnen Yes.  Upgrading to docker 17.06.0 alone did not fix the issue.  I needed to run the _**dmsetup udevcomplete_all**_ command every time I ran a _**docker-compose**_ or it would error out.  When I upgraded the kernel, I no longer faced that issue.

**Comment by ericparton** [comment]
It looks like the backported fix for the semaphore leak issue just missed the cutoff for 17.06.1 and was moved to the 17.06.2, based on [this](https://github.com/docker/docker-ce/pull/200) pull request. 

@thaJeztah @vieux @cpuguy83 would it be possible to get a release of 17.06.2 or some other kind of patch with the pull request so this issue can finally be put to bed? This is a real pain to deal with on a daily basis and it looks like its starting to affect more and more people, based on the duplicate issues that keep getting created.

**Comment by svscorp** [comment]
@ericparton hmm, let's see will 17.06.2 bring the fix. Thanks for sharing this info.

**Comment by hatdropper1977** [comment]
@ericparton Thanks!  Any idea when the release data will be?  It appears the kernel I use (3.10.0) is the latest kernel that the most recent version of Centos 7 (7.3.1611) allows.  Anything higher, you need to go to Elrepo.

I would expect more people to hit this issue as they upgrade to 17.06.  The reason I upgraded is to use the  ARG before FROM feature in the Dockerfile.

**Comment by ericparton** [comment]
@hatdropper1977 Unfortunately not, but judging from [this](https://github.com/docker/docker-ce/milestone/4) it looks like they're in the process of creating a release candidate for it. One of the maintainers would probably have more information

**Comment by thaJeztah** [comment]
17.06.2 was released and includes a cherry-pick of https://github.com/moby/moby/pull/33732 (through https://github.com/docker/docker-ce/pull/200)

**Comment by svscorp** [comment]
@thaJeztah yeah, I don't face issues with device-mapper in 17.06.2 either

**Comment by xjewer** [comment]
Anyone, who can't upgrade docker now,  just increase a semaphores limit to postpone your problem to a close future 😀

e.g. like this
`printf '250\t32000\t32\t200' >/proc/sys/kernel/sem`

Docker:
```
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-8:1-2752513-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 31 GB
 Data Space Total: 322.1 GB
 Data Space Available: 291.1 GB
 Metadata Space Used: 28.52 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.119 GB
 Thin Pool Minimum Free Space: 32.21 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
```

Issue:
```
failed to register layer: devmapper: Error activating devmapper device for '5e86a0c5bb41f1e3b565adecefe6ca9fef4ae4dc21fb7e1fabbf59adc23c9ab4': devicemapper: Can't set cookie dm_task_set_cookie failed.
```

**Comment by thaJeztah** [comment]
With the fix in master, and Docker 17.06.2 and up, I'm closing this issue.

**Comment by gyliu513** [comment]
@thaJeztah we found that the issue still exist even in Docker 17.09, can you help check? 

/cc @hchenxa

**Comment by thaJeztah** [comment]
@gyliu513 do you have specific steps to reproduce the issue? (Reading this thread, there may be multiple issues at hand here)

**Comment by gyliu513** [comment]
It was found in my kubernetes 1.7.3 cluster with Docker 17.09-ce. There are not stable steps to reproduce this, but happens randomly, will try to do more test to see if there are stable steps to reproduce this and have you updated, thanks @thaJeztah 

```
[root@ib17b06 ~]# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Can you post the output of `docker info` as well? It contains more information about the platform/distro you're running on etc

**Comment by hchenxa** [comment]
@thaJeztah 

here is the `docker info`
```
[root@ib17b06 ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 102
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-5768874-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 37.82GB
 Data Space Total: 107.4GB
 Data Space Available: 69.55GB
 Metadata Space Used: 62.22MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.085GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.7GiB
Name: ib17b06
ID: YB4Z:T7G3:P3GI:V7XL:7Q2A:2MQR:PHVY:4PMK:EPFQ:V4HA:L4BY:QE73
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
@hchenxa only Docker EE (enterprise edition) is currently supported on RHEL. The CentOS packages may work, but are built for the latest (7.4) version of CentOS; the SELinux profiles in older versions may be incompatible (at least, not tested on Docker CE)

**Comment by squarebracket** [comment]
If I'm upgrading from 17.06.2, do I need to do anything special to wipe away the old devicemapper garbage?
