### ISSUE TITLE
docker ps hang with docker 17.03

### ISSUE THREAD

**Issue by jieerliansan** [moby/moby#34380]
**Description**

This issue occured when I used docker 1.13 and then I update to 17.03.But now it happen again.

By means of use commond "docker inspect <containerid>",I can find the container who is no response.
and I check the process ,there is no process with this contain's pid.

There is the daemon log when the issue happened:
```
time="2017-08-02T14:16:21.842203609+08:00" level=warning msg="Your kernel does not support swap limit capabilities,or the cgroup is n
ot mounted. Memory limited without swap." 
time="2017-08-02T14:17:25.531402263+08:00" level=info msg="Container 2d26c4e094adf2792c2be03dcb90e53c2a0c293a1dba5b5f2225dfb25b5b3207
 failed to exit within 10 seconds of signal 15 - using the force" 
time="2017-08-02T14:17:25.677374672+08:00" level=error msg="Error closing logger: invalid argument" 
time="2017-08-02T14:48:50.584461558+08:00" level=info msg="Container 47c8347410adbf0ef0ba60fcb2190a6a8ffe4ba6c50e37591e1d54e0934ce040
 failed to exit within 10 seconds of signal 15 - using the force" 
time="2017-08-02T14:49:00.813019800+08:00" level=warning msg="Logger didn't exit in time: logs may be truncated"
```
The OS is Ubuntu 14.04 LTS.

**Describe the results you received:**
when I use docker ps commond,there is no response.

**Describe the results you expected:**

I want to know how it happened and how to resolve it.
**Additional information you deem important (e.g. issue happens only occasionally):**
With 17.03 version the issue happens only occasionally,I cant not reproduce it.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 21
 Running: 10
 Paused: 0
 Stopped: 11
Images: 975
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6266
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: xvwpn7ffstoh3y54gelxb9qv8
 Is Manager: true
 ClusterID: 3e1qui9c09xuae5k5atfkr5ij
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.138.50.1
 Manager Addresses:
  10.138.50.1:2377
  10.138.51.1:2377
  10.138.60.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.81 GiB
Name: hrfw005
ID: PRML:ZH4N:HPPL:HRH6:X7XC:6ZMC:TTFS:JJAJ:GEUY:GVTS:CWHP:ED57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: true
Insecure Registries:
 10.135.6.146:5000
 10.138.23.225:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Can you put the daemon in debug mode (easiest way is to add `"debug": true` to your `daemon.json` and reload the daemon); for example (if you don't have a `daemon.json` yet;

```bash
mkdir -p /etc/docker/

echo '{"debug":true}' > /etc/docker/daemon.json

service docker reload
```

Then send a `SIGURS1` signal to the daemon;

```bash
kill -s USR1 $(pidof dockerd)
```

After that, view the daemon logs;

```
tail -n 500 /var/log/upstart/docker.log
```

Which should either contain a "dump", or on newer versions of docker, reference a file where the dump is written to;

```
time="2017-08-03T09:07:52.105742228-04:00" level=debug msg="Calling GET /_ping"
time="2017-08-03T09:08:02.108401851-04:00" level=debug msg="Calling GET /_ping"
time="2017-08-03T09:08:11.180591985-04:00" level=info msg="goroutine stacks written to /var/run/docker/goroutine-stacks-2017-08-03T090811-0400.log"
```

**Comment by MikeSchroll** [comment]
I had the same issue with:

```
docker info
Containers: 234
 Running: 10
 Paused: 0
 Stopped: 224
Images: 43
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 665
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 47.14GiB
Name: dal10.dnsfilter.com
ID: IUYB:CI7U:ZO5E:SOBY:33KT:JHOJ:LQTI:JHWR:4QD6:CGOC:JSQH:WCO3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Here's my gorountine stacks:
https://transfer.sh/kTNFu/goroutine-stacks-2017-08-19T032628+0200.log

**Comment by cpuguy83** [comment]
@MikeSchroll Your issue seems to be a race in the log tailer.
I recall that this is fixed in newer versions.

**Comment by jieerliansan** [comment]
@thaJeztah  The issue still happens.
Here's my gorounttime stacks:
https://transfer.sh/dApVr/goroutine-stacks-2017-11-22T155454+0800.LOG

**Comment by cpuguy83** [comment]
@jieerliansan  you are running docker 1.13 which is a very old version of Docker.
Can you upgrade to a supported version? This issue is resolved.
