### ISSUE TITLE
cannot exec a container that has run and stopped

### ISSUE THREAD

**Issue by carlory** [moby/moby#34516]
**Description**

Hi,

I installed docker-ce-17.03.2 on Centos 7.2. I couldn't occasionally enter the container to exec cmd after run a container on the background using the image named carlory/ssl-etcd:v2.

```shell
[root@VM_201_72_centos ~]# docker exec -it 28955ebe284a ls
rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
```

And the container status is not the same.

```shell
[root@VM_201_72_centos ~]# docker ps
CONTAINER ID        IMAGE              			 COMMAND                  CREATED             STATUS              PORTS               NAMES
28955ebe284a        carlory/ssl-etcd:v2        "/usr/local/bin/dc..."   About an hour ago  Up About an hour    2379-2380/tcp       priceless_brahmagupta
6f9536716859        carlory/ssl-etcd:v2        "/usr/local/bin/dc..."   About an hour ago   Up About an hour    2379-2380/tcp       happy_ptolemy
25785568de62        carlory/ssl-etcd:v2        "/usr/local/bin/dc..."   About an hour ago   Up About an hour    2379-2380/tcp       stoic_bartik
3bb5f5f8e79d        carlory/ssl-etcd:v2        "/usr/local/bin/dc..."   About an hour ago   Up About an hour    2379-2380/tcp       sad_blackwell

[root@VM_201_72_centos ~]# docker-runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                       CREATED
25785568de62613467b67fe5dbd8654566bff56a5564e90bf9cfa983144fe363   23227       running     /run/docker/libcontainerd/25785568de62613467b67fe5dbd8654566bff56a5564e90bf9cfa983144fe363   2017-08-15T02:30:09.383244275Z
28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b   0           stopped     /run/docker/libcontainerd/28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b   2017-08-15T02:30:15.104398413Z
3bb5f5f8e79d8a310d1bb1757b6f273623c64e630378d2047e3655b55f0d2f29   23012       running     /run/docker/libcontainerd/3bb5f5f8e79d8a310d1bb1757b6f273623c64e630378d2047e3655b55f0d2f29   2017-08-15T02:30:06.674225494Z
6f95367168596d66dad4d824fa10285124fde8a99000d43d06ec98817c100822   23441       running     /run/docker/libcontainerd/6f95367168596d66dad4d824fa10285124fde8a99000d43d06ec98817c100822   2017-08-15T02:30:12.190323374Z
```

And the starttime of the init process is not the same as the initial one. 

```
[root@VM_201_72_centos ~]# docker-runc ps 28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b
UID        PID  PPID  C STIME TTY          TIME CMD
root     23662 23645  0 10:30 ?        00:00:14 /usr/local/bin/etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth --peer-trusted-ca-file /etc/ssl/private/etcd/ca.pem --peer-cert-file /etc/ssl/private/etcd/peer-cert.pem --peer-key-file /etc/ssl/private/etcd/peer-key.pem

[root@VM_201_72_centos ~]# cat /proc/23662/stat
23662 (etcd) S 23645 23662 23662 0 -1 1077944320 4939 2268 7 3 661 840 26 1 20 0 9 0 5189807 10764365824 2853 18446744073709551615 4194304 12718443 140727796761488 140727796760904 4583075 0 0 0 2143420159 18446744073709551615 0 0 17 3 0 0 3 0 0 19734528 19958592 42577920 140727796768081 140727796768461 140727796768461 140727796768740 0

[root@VM_201_72_centos ~]# cat /run/runc/28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b/state.json
{"id":"28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b","init_process_pid":23662,"init_process_start":"5189796","created":"2017-08-15T02:30:15.104398413Z", ...}
```

The process tree of the docker 

```shell
dockerd --storage-driver=devicemapper
  |-docker-containe -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
  |   |-docker-containe 3bb5f5f8e79d8a310d1bb1757b6f273623c64e630378d2047e3655b55f0d2f29 /var/run/docker/libcontainerd/3bb5f5f8e79d8a310d1bb1757b6f273623c64e630378d2047e3655b55f0d2f29 docker-runc
  |   |   |-etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth--peer-trusted
  |   |   |   `-9*[{etcd}]
  |   |   `-9*[{docker-containe}]
  |   |-docker-containe 25785568de62613467b67fe5dbd8654566bff56a5564e90bf9cfa983144fe363 /var/run/docker/libcontainerd/25785568de62613467b67fe5dbd8654566bff56a5564e90bf9cfa983144fe363 docker-runc
  |   |   |-etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth--peer-trusted
  |   |   |   `-8*[{etcd}]
  |   |   `-9*[{docker-containe}]
  |   |-docker-containe 6f95367168596d66dad4d824fa10285124fde8a99000d43d06ec98817c100822 /var/run/docker/libcontainerd/6f95367168596d66dad4d824fa10285124fde8a99000d43d06ec98817c100822 docker-runc
  |   |   |-etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth--peer-trusted
  |   |   |   `-10*[{etcd}]
  |   |   `-9*[{docker-containe}]
  |   |-docker-containe 28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b /var/run/docker/libcontainerd/28955ebe284a0f0b9f45106df638d453e38bf796dac3b42fe20c0b1d96a2920b docker-runc
  |   |   |-etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth--peer-trusted
  |   |   |   `-8*[{etcd}]
  |   |   `-9*[{docker-containe}]
  |   `-35*[{docker-containe}]
  `-63*[{dockerd}]
```

And I have tried to find a better solution, but I couldn't find it. Could you help me?

   @yongtang 

- [opencontainers/runc#1136](https://github.com/opencontainers/runc/pull/1136)

  ​

**Steps to reproduce the issue:**

1. ​
```shell
# shell 1
watch docker-runc list
# shell 2
for i in  `seq 1 20`; do
	docker run -d carlory/ssl-etcd:v2 /usr/local/bin/dce-ssl-helper /usr/local/bin/etcd --name carlory-etcd-0 --data-dir /data/etcd --trusted-ca-file /etc/ssl/private/etcd/ca.pem --cert-file /etc/ssl/private/etcd/peer-cert.pem --key-file /etc/ssl/private/etcd/peer-key.pem --client-cert-auth --peer-trusted-ca-file /etc/ssl/private/etcd/ca.pem --peer-cert-file /etc/ssl/private/etcd/peer-cert.pem --peer-key-file /etc/ssl/private/etcd/peer-key.pem
done
```
2. find the stopped status container in shell 1 and enter the container to exec cmd

**Describe the results you received:**

```shell
rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Dockerfile content of the carlory/ssl-etcd:v2

```shell
[root@VM_201_72_centos ~]# cat Dockerfile
FROM quay.io/coreos/etcd:latest

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV CERT_DIRECTORY=/etc/ssl/private/etcd/
ENV CSR_TEMPLATE=/etc/ssl/private/etcd/spec-template.json
ENV CSR_FILE=/etc/ssl/private/etcd/spec.json
ENV CFSSL=/usr/local/bin/cfssl
ENV CERT_SANS=localhost

ADD /t/ /usr/local/bin/
ADD /t1/ /etc/ssl/private/etcd/


[root@VM_201_72_centos ~]# ls t/
cfssl  dce-ssl-helper  etcd  etcdctl  etcd-ssl
[root@VM_201_72_centos ~]# ls t1/
ca-config.json  ca-key.pem  ca.pem  spec.json  spec-template.json
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.2-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-42572-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 252 MB
 Data Space Total: 107.4 GB
 Data Space Available: 50.35 GB
 Metadata Space Used: 1.032 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.64 GiB
Name: VM_201_72_centos
ID: HREV:DFOJ:NJGE:GZBZ:IEGP:C2YS:255R:IFGP:3EC4:FIIR:Z3FZ:UHGB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: carlory
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Centos 7.2

**Comment by yongtang** [comment]
I am not able to reproduce it on Ubuntu 16.04 or Amazon Linux. Wondering if it is only relevant to CentOS?

**Comment by carlory** [comment]
@yongtang yes

**Comment by yongtang** [comment]
The PR opencontainers/runc#1136 you referenced is just one scenario that causes `cannot exec a container that has run and stopped`. As this PR has already been part of runc in `docker-ce-17.03.2`, it is likely the issue you encountered is caused by other means. Will need some investigation on docker in CentOS.

**Comment by carlory** [comment]
thanks a lot!

**Comment by cpuguy83** [comment]
You should upgrade your kernel to the latest RHEL kernel. This should be fixed there.

> And the starttime of the init process is not the same as the initial one.

This is fundamentally the problem.
runc does not consider a container to be running if the start time in /proc is different than the start time it recorded (since PIDs can be re-used).
THis is a bug in the RHEL kernel that should be fixed in the `-514` patch level.

**Comment by cpuguy83** [comment]
Closing since there isn't really anything we can do here as the kernel is recording the incorrect starttime and is fixed already.
Thanks for the detailed report! Feel free to continue to discuss.

**Comment by zoobab** [comment]
I still have the same problem with the following kernel on Redhat 7.2:

$ cat /proc/version
Linux version 3.10.0-514.26.1.el7.x86_64 (mockbuild@x86-038.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jun 20 01:16:02 EDT 2017

$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
