### ISSUE TITLE
overlay2 + linux v4.13: error creating overlay mount to /var/lib/docker/overlay2/ID/merged: device or resource busy

### ISSUE THREAD

**Issue by euank** [moby/moby#34672]
**Description**

The overlay driver in the kernel, starting with 4.13, will return an error for overlay mounts that re-use the upper dir. This error was introduced in [this](https://patchwork.kernel.org/patch/9760547/) patch.

Using docker `17.06.1-ce` on the `4.13-rc6` kernel I can unreliably reproduce this error message.
I've only ever observed it on the first container run, and only infrequently. I assume that there are two mounts that race and sometimes clash.

**Steps to reproduce the issue:**

1. Install the 4.13 kernel
2. Boot the machine with an empty `/var/lib/docker` directory. Start dockerd, and as soon as possible, run a few dozen containers in parallel.
3. Occasionally, (perhaps 1 out of 30 runs), get the error "error creating overlay mount to /var/lib/docker/overlay2/ID/merged: device or resource busy"
4. Note that the dmesg output includes "overlayfs: upperdir is in-use by another mount"

Note that this only impacts running multiple containers at once. Serializing all container runs avoids it.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.2
 Git commit:   874a737
 Built:        Sat Aug 26 01:07:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.2
 Git commit:   874a737
 Built:        Fri Aug 25 18:06:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.13.0-rc6-coreos
Operating System: Container Linux by CoreOS 1506.0.0+2017-08-25-1813 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.3MiB
Name: localhost
ID: ZBQY:PD55:UTX2:K2N4:CPQJ:HWIY:SOIQ:IC6P:NNXT:YKUZ:XFNP:ESWJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I've seen it on AWS and Qemu, presumably happens on all.

I've also reported this issue over [here](https://github.com/coreos/bugs/issues/2127) on the CoreOS bug tracker.

**Comment by euank** [comment]
I can still reproduce this with the 4.13.2 kernel, so it wasn't just the rc.

The below has reproduced it for me fairly reliably. The number 100 is rather arbitrary. 2 was too few, 100 is probably more than is strictly needed.

```bash
==> make_sleep_container.sh <==
#!/bin/bash

tmpdir=$(mktemp -d)
cd $tmpdir

echo -e "FROM scratch\nCOPY . /" > Dockerfile
b=$(which sleep)
libs=$(sudo ldd $b | grep -o /lib'[^ ]*' | sort -u)
sudo rsync -av --relative --copy-links $b $libs ./
sudo docker build -t sleep .




==> repro.sh <==
#!/bin/bash

set -ex

sudo systemctl stop docker
sudo rm -rf /var/lib/docker
systemctl restart docker

./make_sleep_container.sh

pids=""

for i in $(seq 1 100); do
  docker run --rm sleep sleep 0.2 &
  pids="$pids $!"
done

wait $pids
```

Running `repro.sh` on the 4.13 kernel with `17.06.2-ce` gives me:

```
/run/torcx/bin/docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/cca2481a00020458e95d589fca23192c1addc1dfeab6793d503e1749a2acbef6/merged: device or resource busy.
ERRO[0008] error waiting for container: context canceled 
/run/torcx/bin/docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/14464288a0c06dfead5dcbec623037ab0e29dbd3b35cf4bc439865af475c44d7/merged: device or resource busy.
ERRO[0008] error waiting for container: context canceled 
/run/torcx/bin/docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/f0fa08260045a14087761dc2bd7bd6b3c82c656814630f0d996b67849cca9e41/merged: device or resource busy.
ERRO[0008] error waiting for container: context canceled 
```

For me, this happens within the first couple runs.

**Comment by euank** [comment]
These errors always follow a 'Failed to unmount' message. From the daemon's debug logs:

```
$ sudo journalctl -u docker -o cat | grep -E "level=error|Failed" 
....

time="2017-09-19T22:29:07.223235635Z" level=debug msg="Failed to unmount 62676b62ee42ac87c68d82092051e683037dfaa4dfb016fb4a30273d1e12e4ae overlay: /var/lib/docker/overlay2/62676b62ee42ac87c68d82092051e683037dfaa4dfb016fb4a30273d1e12e4ae/merged - invalid argument"
time="2017-09-19T22:29:08.277011559Z" level=error msg="Handler for POST /v1.30/containers/2cfb5c61a0713b6b163e3a2abfb4572dfcf6a167c7837b58ad217870bdc7b661/start returned error: error creating overlay mount to /var/lib/docker/overlay2/62676b62ee42ac87c68d82092051e683037dfaa4dfb016fb4a30273d1e12e4ae/merged: device or resource busy"
time="2017-09-19T22:29:08.331422149Z" level=debug msg="Failed to unmount e5df5519f398a1c1f43969662c7872f75cc2432f02c67f7a3164babd21ada536 overlay: /var/lib/docker/overlay2/e5df5519f398a1c1f43969662c7872f75cc2432f02c67f7a3164babd21ada536/merged - invalid argument"
time="2017-09-19T22:29:08.364760182Z" level=error msg="Handler for POST /v1.30/containers/dffd9bcd3a7da4716fd445b40d48f87ee04c6361d079e71750e9d66795ca2f7e/start returned error: error creating overlay mount to /var/lib/docker/overlay2/e5df5519f398a1c1f43969662c7872f75cc2432f02c67f7a3164babd21ada536/merged: device or resource busy"
```

**Comment by thaJeztah** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
@euank thanks for reporting, I haven't seen these `Failed to unmount 62676b62ee42ac87c68d82092051e683037dfaa4dfb016fb4a30273d1e12e4ae overlay: /var/lib/docker/overlay2/62676b62ee42ac87c68d82092051e683037dfaa4dfb016fb4a30273d1e12e4ae/merged - invalid argument` yet, but the combination of the kernel change and this failure makes sense.

**Comment by euank** [comment]
I've dug into it more and I think the `invalid argument` messages are actually red herrings.

The `EBUSY` is what actually matters. With some stracing and added logging, it appears to me that the overlay2 driver's locking mechanism is working just fine.
I see the `EBUSY` on a `mount` call for a given directory even though a `umount` call to it had returned 0.

On a hunch, I removed the `MNT_DETACH` flag, but that didn't make a difference.

At this point I suspect that this is a kernel bug. My next step is to try and write a reproduction that doesn't involve dockerd.

**Comment by thaJeztah** [comment]
Thanks for the update @euank

**Comment by euank** [comment]
After more investigation:

Using perf probes, we get that the kernel `ovl_inuse_unlock` happens after this chain:
```
task_work_run
__cleanup_mnt
cleanup_mnt
deactivate_super
deactivate_locked_super
kill_anon_super
generic_shutdown_super
ovl_inuse_unlock
```

The important detail to notice here is that `ovl_inuse_unlock` is coming from a task queue (`task_work_run`).

Because of that, umount returning isn't enough for us to be sure the upperdir is unlocked from overlayfs' view.
Furthermore, there doesn't appear to be any way to actually check whether the upperdir is unlocked since the mountpoint has already been cleaned up.

The easiest fix would be to retry a few times on `EBUSY` in the overlay2 mount code.

The most confusing thing to me right now is that I'm still unable to figure out a simple reproduction without docker. I'm not sure what I'm missing there.

**Comment by euank** [comment]
Retrying on ebusy shows me that it takes from around 200ms to 1200ms for the `mount` to actually succeed.

That seems like an excessively long amount of time for the explanation I've currently got.
That makes me suspect there's something more at play.

**Comment by euank** [comment]
After a bit more adventuring, I believe I've tracked this down to two distinct problems which both cause this issue identically!


First, a helpful trick for reproducing this -- add a 1-3 second sleep before pivoting root:
https://github.com/opencontainers/runc/blob/593914b8bd5448a93f7c3e4902a03408b6d5c0ce/libcontainer/rootfs_linux.go#L98-L103

And a few hundred ms in the `Put` code here:
https://github.com/moby/moby/blob/ba317637de9b9918cdc2139466dd51c6200bd158/daemon/graphdriver/overlay2/overlay.go#L610


After those changes, it reliably reproduces running just two containers at once, which made it much easier to continue investigating.

Anyways, it turns out that if you look through every mount namespace for references to the overlayfs mount, you'll find that the `runc init` process for another container sometimes has a copy of it still mounted, despite it being unmounted and gone from the host mount namespace.

This copy is a *private* copy of the mount meaning our host umount won't get it, and we're at the mercy of `runc inti` to eventually clean it up.

I've created a fairly well commented reproduction of what's happening to lead up to this ebusy:

```bash
#!/bin/bash
set -x

# c1 and c2 represent two different docker containers starting at once
c1=1
c2=2

function ovlOpts() {
	echo -n "lowerdir=$tmpdir/lower,upperdir=$tmpdir/$1/diff,workdir=$tmpdir/$1/work"
}

tmpdir=$(mktemp -d) # 'overlay2' graphdriver dir

mkdir -p $tmpdir/{$c1,$c2}/{diff,merged,work}
mkdir -p $tmpdir/lower

# overlay2 driver in its setup code does this
# https://github.com/moby/moby/blob/ba317637de9b9918cdc2139466dd51c6200bd158/daemon/graphdriver/overlay2/overlay.go#L178
mount --bind $tmpdir $tmpdir
mount --make-private $tmpdir

# Container 2 sets up 
# https://github.com/moby/moby/blob/ba317637de9b9918cdc2139466dd51c6200bd158/daemon/graphdriver/overlay2/overlay.go#L589
mount -t overlay overlay -o "$(ovlOpts $c2)" $tmpdir/$c2/merged 

# Container 1 starts setting up
mount -t overlay overlay -o "$(ovlOpts $c1)" $tmpdir/$c1/merged 

# Container 2 runs 'runc init' code in parallel
(
  # https://github.com/opencontainers/runc/blob/8b47a242a9aebdfe1c0c2b6513368f736d505bf0/libcontainer/nsenter/nsexec.c#L823
  unshare -m --propagation unchanged -- bash <<EOF
  # Now runc init remounts /
  # https://github.com/opencontainers/runc/blob/e385f67a0e45fa1d8ef8154e2aea5128ea1d331b/libcontainer/rootfs_linux.go#L599-L605
  # Due to how the config conversion works, config.RootPropagation is never 0,
  # and defaults instead to MS_PRIVATE | MS_REC. I'll PR a fix
  mount --make-rslave /
  # Now a bunch of init stuff happens, including premount cmds and hooks
  sleep 1
  # .. and then pivot root happens which cleans up our old root
  # It's hard to do in shell, so we'll just pretend an umount of / is close enough
  # https://github.com/opencontainers/runc/blob/e385f67a0e45fa1d8ef8154e2aea5128ea1d331b/libcontainer/rootfs_linux.go#L676
  cd /
  umount -l .
EOF
) &
   
sleep 0.5

# While container2 is doing its init, container 1 unmounts and remounts its overlay
umount $tmpdir/$c1/merged
mount -t overlay overlay -o "$(ovlOpts $c1)" $tmpdir/$c1/merged 
# Boom, EBUSY on 4.13+ because `unshare -m` above has a private copy of the mount

sleep 1
# Now that the runc init code has pivoted and umounted its old root, we're able to mount without EBUSY
mount -t overlay overlay -o "$(ovlOpts $c1)" $tmpdir/$c1/merged 
umount $tmpdir/$c1/merged

# Cleanup
umount $tmpdir/$c2/merged
umount $tmpdir
rm -rf $tmpdir
```

Changing the runc-init mount to be `rslave` (as I think it was meant to be) and removing the `MakePrivate` call for the `overlay2` graphdriver directory fixes the race. Even with the addition of the above-mentioned sleeps, I no longer am able to get EBUSY with those changes.

I'll PR each of those changes shortly with suitable commit messages.

**Comment by thaJeztah** [comment]
Thanks for the extensive analysis @euank

**Comment by euank** [comment]
In my testing, this is fixed by applying both https://github.com/moby/moby/pull/34948 and https://github.com/opencontainers/runc/pull/1598

One or the other isn't enough since both result in a private copy of the mount off in runc's init mountns, but both of them together ensure it doesn't happen.

**Comment by euank** [comment]
I think it's still possible to hit the race in theory without also applying https://github.com/opencontainers/runc/pull/1500, but in practice I can't hit that one.

**Comment by cyphar** [comment]
This looks like another variant of #34573 (effectively mount leaks are causing `EBUSY` in a variety of places). Honestly we should re-architect Docker/containerd so that it spawns runC in different mount namespaces (with the rootfs mount only done privately in each mount namespace) so that the mounts won't be leakable to other runcs.

**Comment by maltris** [comment]
Hi, I think I can confirm this behaviour as of kernel 4.13.3 and docker-ce 17.09!

docker version:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

dmesg:
```
overlayfs: upperdir is in-use by another mount
```

docker info:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 109
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.3-041303-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.669GiB
Name: hostname
ID: something
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by sulliwane** [comment]
I probably encounter the aforementioned bug, with Ubuntu 17.04:
```
#uname -r
4.13.0-041300-generic
```
and :
```
#docker-compose -f mongo.docker-compose.yml up -d
Starting compose_app ... 
Starting compose_app ... error

ERROR: for compose_app  Cannot start service explorer-mongo: error creating overlay mount to /var/lib/docker/overlay2/486d9b9195be51fd3ddef6582006b7ac30dbbc3a308b4f517528e5a687bdbe62/merged: device or resource busy

ERROR: for explorer-mongo  Cannot start service explorer-mongo: error creating overlay mount to /var/lib/docker/overlay2/486d9b9195be51fd3ddef6582006b7ac30dbbc3a308b4f517528e5a687bdbe62/merged: device or resource busy
ERROR: Encountered errors while bringing up the project.
```
Any quick-fix ? even temporary ? Reverting to lower kernel, like 4.12 ?
Many Thanks!

**Comment by jcamiloradamesa** [comment]
@sulliwane were you able to solve problem, having same problem here with Ubuntu 17.10

**Comment by sulliwane** [comment]
I reboot computer when this is happening :)

**Comment by firedoar** [comment]
...

**Comment by maltris** [comment]
Its weird but it seems that after upgrading the kernel to something even more recent (e. g. 4.13.8) it worked again. Can anyone confirm that?

Running Ubuntu 17.10 and 4.13.8 now.

**Comment by jcamiloradamesa** [comment]
I can confirm that is working for me with Ubuntu 17.10 and Kernel 4.13.9.

**Comment by ep4eg** [comment]
I've got the same behavior on:

Docker: 17.10.0-ce
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
Kernel Version: 4.13.4-1.el7.centos.x86_64

**Comment by banuchka** [comment]
Fixed in kernel-4.13.6

https://lwn.net/Articles/736185/

Amir Goldstein (5):
ovl: fix error value printed in ovl_lookup_index()
ovl: fix dput() of ERR_PTR in ovl_cleanup_index()
ovl: fix dentry leak in ovl_indexdir_cleanup()
ovl: fix missing unlock_rename() in ovl_do_copy_up()
ovl: fix regression caused by exclusive upper/work dir protection

On 26 October 2017 at 10:31:32, ep4eg (notifications@github.com) wrote:

I've got the same behavior on:

Docker: 17.10.0-ce
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
Kernel Version: 4.13.4-1.el7.centos.x86_64

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

-- 
banuchka

**Comment by adambro** [comment]
I still experience this (or similar issue). Error message is the same:
```
Cannot start service parks_test: b'error creating overlay mount to /var/lib/docker/overlay2/ID/merged: device or resource busy'
```

My system:
Docker version 17.10.0-ce, build f4ffd2511c
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
Kernel Version: 4.13.7-1-ARCH

So it does not seem to be solved in kernel 4.13.7 as @banuchka suggested.

**Comment by euank** [comment]
@adambro Can you check your kernel options for the `OVERLAY_FS_INDEX` config option (e.g. with `zgrep OVERLAY_FS_INDEX /proc/config.gz`)?

If that option is set to yes, it's expected that the kernel will still exhibit the same behaviour.

As @banuchka indicates, this error shouldn't occur on newer kernels so long as they don't have that option set.
That being said, there's still a mount being leaked and `dmesg` will still show warnings.

**Comment by adambro** [comment]
Indeed I have it set to yes: `CONFIG_OVERLAY_FS_INDEX=y` so the issue persists. Thanks for help @euank and @banuchka.

**Comment by jpalczewski** [comment]
I met that error(/merged busy) on 4.13.11-1-ARCH - recent version of kernel on Arch with `CONFIG_OVERLAY_FS_INDEX` set with two containers(database with volume drive and one client).

So, in other words: default kernel settings on Arch makes Docker with >2 container unreliable s? Can be `CONFIG_OVERLAY_FS_INDEX` passed by kernel parameter in bootloader, or should I recompile it on my own/choose another driver?

**Comment by euank** [comment]
@jpalczewski the index option can be turned off as a module option, as described in the [kconfig entry](https://github.com/torvalds/linux/blob/v4.13/fs/overlayfs/Kconfig#L27-L45) for it.

**Comment by thypon** [comment]
@euank could you verify if your patch fixes also the problem with the `devicemapper` driver?

The issue https://github.com/moby/moby/issues/34283 was closed by @dnephin , but I am not sure it is related to this issue with `overlay{,2}`.

**Comment by huegelc** [comment]
So, did the patch made it into the kernel?

**Comment by euank** [comment]
@huegelc Yes, as of 4.13.6. There are two possible scenarios which will result in this specific issue (based on  my understanding):

1. Kernel between 4.13.0 and 4.13.6 &mdash; update your kernel *or* wait for docker to include  #34948 
2. Kernel >= 4.13.6, but with `CONFIG_OVERLAY_FS_INDEX=y` &mdash; [disable](https://github.com/torvalds/linux/blob/v4.13/fs/overlayfs/Kconfig#L27-L45) that feature (either at module load time or by setting it to n) *or* wait for docker to include #34948 

Without #34948, there will still be warnings in `dmesg` in those two scenarios, but they can be safely ignored.

Because this is not a harmful issue on an up-to-date kernel and because the moby codebase (if not docker) has been updated to handle this issue better, I'm closing this bug.

**Comment by vojtechkral** [comment]
Hi. I ran into what seems to be the same issue just now. Unlike others, I was only running one container. The issue started when I exited a shell of a running container. I can't do anything with the container now, it cannot be started and the changes cannot be commited, which is annoying, because it seems I'll lose them. I'll have to salvage them from the `diff` dir I suppose.

```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 17.10.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.3-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.35GiB
Name: nathalia
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

dmesg:

    [101868.898938] overlayfs: upperdir is in-use by another mount, mount with '-o index=off' to override exclusive upperdir protection.

```
$ docker start -ai ae8dce2afd44         
Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/a55e246177566c639071ed94f0821ba95ca436aa6bb16058889b645628764a3f/merged: device or resource busy
```

```
$ sudo LC_ALL=C journalctl -r -u docker | head
-- Logs begin at Sun 2017-04-02 22:46:02 CEST, end at Thu 2017-12-07 16:54:18 CET. --
Dec 07 16:52:12 nathalia dockerd[17567]: time="2017-12-07T16:52:12.656450433+01:00" level=error msg="Handler for POST /v1.33/containers/ae8dce2afd440a27434ee31f58ad2f0e966618dfd05e18956db450fa27dcb32c/start returned error: error creating overlay mount to /var/lib/docker/overlay2/a55e246177566c639071ed94f0821ba95ca436aa6bb16058889b645628764a3f/merged: device or resource busy"
Dec 07 16:52:12 nathalia dockerd[17567]: time="2017-12-07T16:52:12.655807745+01:00" level=warning msg="error locating sandbox id 7f3b3bc2eb934b9fe1e269a32fd56d97cfaf80dac27f912518c05d6862db8321: sandbox 7f3b3bc2eb934b9fe1e269a32fd56d97cfaf80dac27f912518c05d6862db8321 not found"
Dec 07 16:52:12 nathalia dockerd[17567]: time="2017-12-07T16:52:12.634585031+01:00" level=error msg="error unmounting /var/lib/docker/overlay2/a55e246177566c639071ed94f0821ba95ca436aa6bb16058889b645628764a3f/merged: invalid argument"
```

**Comment by l0b0** [comment]
@euank Is it possible to disable `CONFIG_OVERLAY_FS_INDEX` without recompiling the kernel?

**Comment by euank** [comment]
@l0b0 Per [comments above](https://github.com/moby/moby/issues/34672#issuecomment-343785403) the default can be set without recompiling via a module option. That's sufficient to work around this until the patch lands in docker.

**Comment by pedantic-git** [comment]
I just experienced this myself on Arch - thanks for your help resolving it!

For other Arch users looking for the tl;dr version of what people above are suggesting, create a file `/etc/modprobe.d/overlay.conf` with the following contents:

```
options overlay index=off
```

and reboot (or `rmmod overlay && modprobe overlay`). That resolved the issue for me.

**Comment by josenava** [comment]
@pedantic-git Thanks for the TL;DR version, it solved the issue (in my case running kernel 4.14.4-1-macbook on Arch)

**Comment by dlq84** [comment]
> Note, that the inodes index feature is read-only backward compatible.
	  That is, mounting an overlay which has an index dir on a kernel that
	  doesn't support this feature read-only, will not have any negative
	  outcomes.  However, **mounting the same overlay with an old kernel
	  read-write and then mounting it again with a new kernel, will have
	  unexpected results.**

https://github.com/torvalds/linux/blob/v4.13/fs/overlayfs/Kconfig#L27-L45

This may be why people have been running images for a while and the suddenly aren't working correctly. So rebuilding containers should fix it? I've rebuilt all my containers now and I don't have the problem anymore.

**Comment by peterver** [comment]
I've encountered this issue everytime I do a system upgrade ( Arch - Linux Kernel 4.14.6-1 ). A way to fix this without rebooting your machine is the following chain of commands ( restarting your docker and regenerating the dependencies for system configuration services )

```
systemctl stop docker.service && systemctl start docker.service && systemctl daemon-reload
```

**Comment by 1arrow** [comment]
Will upgrade the kernel version and check

**Comment by AbhinayGupta741** [comment]
`$ vim /etc/docker/daemon.json
{
  "max-concurrent-uploads": 1
}
$ service docker restart`

I had the same issue with the docker. It was not able to push images to gcr . The above will able to solve my issue.
