### ISSUE TITLE
docker service logs RPC error after network failure in swarm mode from 2/12 nodes

### ISSUE THREAD

**Issue by SvenAbels** [moby/moby#35011]
**Description**
We got a docker swarm mode cluster with 12 servers - all using docker 17.06.
Tonight our data center had some network probelms and some servers have been offline for a few minutes. They are all back online and healthy now.

docker node ls shows them all as ready and active and they also received some tasks, which are running. We can also start new tasks on them without problems. 

However, we cannot receive logs anymore from 2 of the 12 nodes.
`docker service logs --tail=1000 testservice`

Shows:
`error from daemon in stream: Error grabbing logs: rpc error: code = 2 desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node 1yjkb8d3oh2tc8hrup7641mau is not available`

What can we do?

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 LTS

**Comment by jdivine-spok** [comment]
We encountered the same error yesterday.  3 manager nodes, 3 worker nodes.  

We were load testing our swarm stack and ran into some glitches - attempting to troubleshoot the glitches, we discovered we were unable to retrieve logs from one of the worker nodes with the same error as above.  The node shows as ready, services are running and reachable on the machine, just no ability to retrieve logs with `docker service logs` from any of the services on that node.

Output of `docker version` is identical to above.

Ubuntu 16.04 in AWS on m4.large instances

**Comment by cpuguy83** [comment]
ping @dperny

**Comment by dperny** [comment]
do you know if restarting the worker causes the logs to start working again? i'm not suggesting this as a workaround because restarting workers in prod is nontrivial, but if you've tried it and it does or does not work, that would be useful information.

**Comment by jdivine-spok** [comment]
@dperny we will find out if and when it happens again.  I don't remember precisely what we did last week.  We are on 17.09 now.

**Comment by SvenAbels** [comment]
We haven't tested this because unfortunately, both servers are productive systems so I don't want to restart them unless absolutely necessary.

**Comment by thaJeztah** [comment]
This may be a duplicate of https://github.com/moby/moby/issues/33203 (is that what you were suspecting as well, @dperny ?)

**Comment by phillipoertel** [comment]
Same issue here:

```
root@yello:~# docker service logs staging_core_web
error from daemon in stream: Error grabbing logs: rpc error: code = 2 desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node fp39nbonqsdijfeuhhur9ouqr is not available
```
Logs don't come back even after worker restart. We're running Docker version 17.06.0-ce, build 02c1d87 on Ubuntu.

**Comment by phillipoertel** [comment]
Still have this issue with docker version 17.10.0-ce, build f4ffd25, with a little different output:
```
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: illegal wireType 6
```

**Comment by osidorkin** [comment]
Same issue on 10 nodes swarm 17.09.0-ce. Errors varies by service and is combination of `illegal wireType X` and `received message length X exceeding the max size 134217728` so it looks like protocol issue or data corruption.

**Comment by jbscare** [comment]
We're seeing an issue that seems similar, where a `docker service logs prod-swarm_helloworld` command returns some logs, but ends with an error about two nodes:
```
prod-swarm_helloworld.2.eqvltu7tn2fu@omni-prod-defaultworker-b4.prod.omni.carezen.net    | > node_helloworld@1.0.0 start /usr/src/app
prod-swarm_helloworld.2.eqvltu7tn2fu@omni-prod-defaultworker-b4.prod.omni.carezen.net    | > node server.js
prod-swarm_helloworld.2.eqvltu7tn2fu@omni-prod-defaultworker-b4.prod.omni.carezen.net    |
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node qsemjduuwxrl5yawc1ofgfinj is not available, node n5srg4wxoyqexvp1yazbicrlg is not available
```
This service only has one replica now, although it might have had more (and been updated down to 1) in the past. (Not 100% sure about that -- it might have been removed and re-created since then.) 

Another curious thing: Node n5srg4wxoyqexvp1yazbicrlg is one of our other nodes; but qsemjduuwxrl5yawc1ofgfinj isn't, at least not currently. We have added nodes to this Swarm, and removed them, in the past, so it's possible that this is a node that used to exist.

Anything else we can do to gather more information here? In particular, why does Swarm think that this service with one replica should have logs on three nodes, one of which doesn't even exist any more?)

**Comment by jbscare** [comment]
> This may be a duplicate of #33203 (is that what you were suspecting as well, @dperny ?)

#33203 is still open, but there's a comment there saying that it looks like a duplicate of #33222, which is closed. Sounds from the previous comment like this is still an issue, though?

**Comment by Jeskz0rd** [comment]
I did fix it, I don't know what really happened, but for me sounded like "iptables" rules problem. I flush the rules on the host and it started working again. Hope to help. Thanks at all!

**Comment by mlinsky** [comment]
I am still getting this issue, has there been a fix or workaround for it. I know of one where you just use the -f/--follow option but other than that?

**Comment by cristhianbicca** [comment]
I'm having the same problem.
`
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:11:05 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:09:37 2018
  OS/Arch:      linux/amd64
  Experimental: false
`

Docker error:

`error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node wre79765gdccialsnwxjiy4eh is not available`

**Comment by maxim-ge** [comment]
Same thing.  3 nodes, 1 manager. `sudo docker service logs kafka3` fails, kafka3 works fine.

Workarounds
- use `-f` option
- reboot node3

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by Vad1mo** [comment]
We also see the same issue with `17.12.0-ce` We have plain Vanilla setup on ubuntu 16.04 nothing fancy, after a few hours or days the error starts to appear.

We restart the node and for a few hours/days it works then it starts again.

```
Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = Canceled desc = context canceled
```

**Comment by DmitriyProkhorov** [comment]
Same issue, Docker version 17.09.1-ce, 3 managers 2 workers, Debian 8, Azure

**Comment by Vad1mo** [comment]
Updated to 18.02 and we still see this error. However we did not scale down or up any service. At appears after some time by itself.

**Comment by goncalo-oliveira** [comment]
Similar issue here, though there's something interesting that I don't think anyone has mentioned. Maybe it's useful, maybe it's not. When I try to get the logs for the service, I get the same as others

```
| dbug: gateway.connection    error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: rpc error: code = Canceled desc = context canceled
```

This is a service with only one task. So I listed the tasks for the service

```
$ docker service ps gateway_teltonika
ID                  NAME                      CURRENT STATE
1p5k253l5ogc        gateway_teltonika.1       Running
```

And tried retrieving the logs for the task itself.

```
$ docker service logs 1p5k
```

This works, the logs are there and they're updated.

I'm using version 17.12.0-ce.

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by alexmnt** [comment]
I think the certificates have changed and are out of sync between the manager and the worker. Experienced this with multiple Docker versions. My initial workaround switch fixed the problem was create a new swarm (if it was on the master node) / leave and rejoin (if it was on the worker node).

The fix witch seam more of a solution and worked for me was to execute on the manager node:

docker swarm ca --rotate on 
This resented the certificates between the nodes and then I could retrieved the logs from the services.
Also I could redeploy new services.

**Comment by Voovode** [comment]
@alexmnt 
Even after
`docker swarm ca --rotate`
I still receive this error. 
I'm on new install running for 48h.

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by dperny** [comment]
i think it's likely that the CA rotation is only making logs work again as a side effect. probably something about updating the node. if other things work and logs don't, this is probably an issue in the log broker component on the manager. i haven't had time to look at it yet, for which i sincerely apologize, but i'll try to block out some time to fix it.

the bright side is i've become a much better programmer compared to when we first shipped logs, so when i finally do get around to fixing it it'll likely be much more stable 😄

**Comment by olljanat** [comment]
FYI. We had this issue today with 17.09.1. After couple of hours troubleshooting cloned one manager and one worker VMs to sandbox network and there they was working fine immediately after start.

So then I rebooted all the manager nodes on production and leaved worker nodes running and that fixed the issue (one more good reason to have dedicated manager nodes).

**Comment by kevb** [comment]
Same issue in my prod swarm, tracking this issue.

**Comment by olljanat** [comment]
@kevb Which docker version you are running?

I can see that there is plenty of fixes included to 18.03.0-ce version so it would be interesting to here if anyone have seen this issue with that one?

**Comment by Shookit** [comment]
I'm seeing this with 18.03

**Comment by mrpatrick** [comment]
I'm seeing same issue with 18.03

**Comment by olljanat** [comment]
FYI. I created [stress testing tool](https://github.com/olljanat/swarmkit-stress-tester) for Swarmkit which builds latest version of it from puts it to env where network failures can be generated on purpose.

I was able to reproduce this issue with it. Here is some logs: https://pastebin.com/raw/8RW5AE4w and https://pastebin.com/raw/2tgz57nH

@dperny / @thaJeztah I can also see that there is now more information than earlier because of docker/swarmkit#2541

I hope that this helps you find and fix the root cause of issue.

**Comment by kevb** [comment]
@olljanat using 18.03.0-ce : (

**Comment by raarts** [comment]
@nmarjanovic is that possible with docker stack as well?

**Comment by nmarjanovic** [comment]
@raarts Short answer is yes, we use it as well ;). But you need to update service by service, kind long, but working without errors.

**Comment by BaliStarDUT** [comment]
Who can tell me whether this feature use some ports like 111? I blocked all out port 1-65535 only 22 open.And find this problem on a woker node.my version is 17.12.1-ce.

**Comment by olljanat** [comment]
@BaliStarDUT ports which need to be open between hosts are listed on here: https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts

If you see this issue immediately after restart your computer(s) then some port opening is most probably missing. If that starts randomly then it is same as we are troublestooting here.

**Comment by kingname** [comment]
Same problem.

**Comment by olljanat** [comment]
@dperny I did some tuning to my https://github.com/olljanat/swarmkit-stress-tester and now I'm able to reproduce this issue every time I run it. 

Key things to get that state was:
- Have test services which are printing huge amount of random data to console all the time.
- Take network connection from workers down for one minute.

Here you can see how it look when swarm is on that state:
```
$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/swarmkit-stress-tester:/tmp/swarmkit-stress-tester --rm --name debug swarmkit-stress-tester bash

root@87d35c5ae29f:/# swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock node ls
ID                         Name      Membership  Status  Availability  Manager Status
--                         ----      ----------  ------  ------------  --------------
4akj54xwh8msyldmbppr8scw1  manager1  ACCEPTED    READY   ACTIVE        REACHABLE *
6w5dojd5vy9y1phadzngllzto  manager3  ACCEPTED    READY   ACTIVE        REACHABLE
cxlvr2wb37g7pqh6ix1r2i4zk  worker1   ACCEPTED    READY   ACTIVE
e4sc5h8mu30kmzc3wo2g7gt46  manager2  ACCEPTED    READY   ACTIVE        REACHABLE
gcn1uwjublun7a254lnjaz1dc  worker2   ACCEPTED    READY   ACTIVE

root@87d35c5ae29f:/# swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock service ls
ID                         Name  Image         Replicas
--                         ----  -----         --------
i0r653gvx14q4ke4jy4vzfwh6  foo   test-service  global
teblcawm1zelrnn210tlaiius  bar   test-service  2/2

root@87d35c5ae29f:/# swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock service logs bar
Error: failed receiving stream message: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node cxlvr2wb37g7pqh6ix1r2i4zk is not available, node gcn1uwjublun7a254lnjaz1dc is not available

root@87d35c5ae29f:/# swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock service logs foo
Error: failed receiving stream message: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node gcn1uwjublun7a254lnjaz1dc is not available, node cxlvr2wb37g7pqh6ix1r2i4zk is not available
```

Force update for services does **not** fix the issue.
```bash
swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock service update --image test-service --force bar
swarmctl -s /tmp/swarmkit-stress-tester/manager1.sock service update --image test-service --force foo
```

But restating managers one by one does.
```bash
./workaround.sh
```

Important note also is that when swarm is on this state you can still read logs using **--follow** switch.

My theory is that problem is reach the state where log actually starts and that why restarting managers actually fixes it.

**Comment by ediri** [comment]
Same problem here with version 18.03.1-ce. @nmarjanovic Can i put your workaround in the compose file too?

**Comment by olljanat** [comment]
@ediri actually can you try my version on workaround and restart manager servers one by one without touching workers or doing service updates? 

That is situation which I'm now able reproduce and it is important information that is that same or is there two similar.

**Comment by nmarjanovic** [comment]
@ediri this is not related to docker-compose, it's only how you update your services after last docker pull. If you have CI system, you can use simple bash script to run this command for you. If you have your own docker registry, then use options --force --with-registry-auth --image, that's all what I can add.

**Comment by ediri** [comment]
@olljanat Restart of services works to bring the logs back. Without touching the workers. Actually that was my manual workaround in Portainer.

**Comment by ediri** [comment]
@nmarjanovic Thanks for the hint. will try it in my stack deploy with --force

**Comment by davidgibbons** [comment]
@olljanat I've tried the requested steps and it did not remove the error message/behavior.

`error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node ymom7wdza0vf40rjabypg8ks2 is not available, node x9y7x0vc8o1jf863jxopsvfo2 is not available, node 5qliewb6axa12m6h1zorphzxg is not available, node sp7mbc191vradycld4e11mhqk is not available`


This is with dedicated manager nodes. It seems to happen after we do upgrades pretty consistently. 

Upgrades are done by bringing up a new autoscale group and connecting it to the existing swarm, setting all existing nodes to drain, demoting the managers, removing the previous autoscale group and then deleting the down nodes from the swarm. 

After this process we start to get the error messages reported and logging becomes impacted.

**Comment by madisonleavo** [comment]
My issue was far more mundane, but I made it to this thread with the error `Error response from daemon: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field InitValue` similar to the error @phillipoertel posted a while back.

And I only needed to run `docker node ls` as suggested by olljanat to see my now-obvious error. I couldn't find any google hits for my exact error, so I'm posting here for any others who might need.
```
STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
Ready               Active              Reachable           18.06.0-ce
Ready               Active              Reachable           18.06.0-ce
Ready               Active              Leader              17.09.0-ce
```

**Comment by meatfly** [comment]
faster way to fix this issue 
- drain all your managers
- reboot managers
- active all your managers

**Comment by staranto** [comment]
Tried to @olljanat directions, but my single manager node was already availability=pause and had no service containers on it.  `docker service logs mysvc` fails, `docker services logs -f mysvc` works.  I've tried all combinations of restarts, affinity, etc.  Results always hold true.

18.03.1-ce on 5 worker nodes, 18.06-1-ce on manager node.  Pi cluster.  Debian 9 stretch.

**Comment by frejonb** [comment]
Workaround: `docker service logs -tf <service_name>`

**Comment by zx1986** [comment]
T___T

same problem with Docker version 18.06.1-ce, build e68fc7a in Ubuntu 18.04 server.

**Comment by PhilipGarnero** [comment]
Same issue here with docker 18.09.3. The certificate rotation worked but the issue came back the next day...

**Comment by olljanat** [comment]
I noticed that it is not yet mentioned here that simplest solution to this issue is configure `max-size` option for log driver small enough. Something like `100k`. More info about those you can find from:
https://docs.docker.com/config/containers/logging/json-file/#usage
or use some other logging driver.

**Comment by joseluisq** [comment]
> I think the certificates have changed and are out of sync between the manager and the worker. Experienced this with multiple Docker versions. My initial workaround to fix the problem was create a new swarm (if it was on the master node) / leave and rejoin (if it was on the worker node).
> 
> The fix witch seam more of a solution and worked for me was to execute on the manager node:
> 
> docker swarm ca --rotate
> 
> This resented the certificates between the nodes and then I could retrieved the logs from the services.
> Also I could redeploy new services.

@alexmnt solution's worked for me.

**Comment by MichaelErmer** [comment]
Can confirm `docker swarm ca --rotate` resolved the issue on our cluster of 10 nodes running 19.03.4

**Comment by ProteanCode** [comment]
It's 2020 and this still happens.

`docker swarm ca --rotate` helped me, but i remember that I also could use the `docker stack rm` and `docker stack deploy` (but this is only good for non production envs).

Should we autorotate the ca cert?

**Comment by ProteanCode** [comment]
> I think the certificates have changed and are out of sync between the manager and the worker. Experienced this with multiple Docker versions. My initial workaround to fix the problem was create a new swarm (if it was on the master node) / leave and rejoin (if it was on the worker node).
> 
> The fix witch seam more of a solution and worked for me was to execute on the manager node:
> 
> docker swarm ca --rotate
> 
> This resented the certificates between the nodes and then I could retrieved the logs from the services.
> Also I could redeploy new services.

The CA rotation works, but I have this problem on a single node server so it shows that you may be wrong about 

> are out of sync between the manager and the worker

Since single node cannot be out of sync with itself.

**Comment by jaschaio** [comment]
Encountered the same issue on `19.03.8`. Resolved via `docker swarm ca --rotate`.

Same as @ProteanCode, is there anything that should discourage me from just executing `docker swarm ca --rotate` once a day to prevent this from happening?

**Comment by darkl0rd** [comment]
Can confirm this still occurs on a regular basis on docker 19.03.9. I just noticed it has been open for 2.5 years, what’s blocking this issue from moving forward?

**Comment by cpuguy83** [comment]
> what’s blocking this issue from moving forward?

Someone stepping up to troubleshoot and resolve the issue.

**Comment by Nielio** [comment]
Had the issue after experimenting with some `networks` and `ports` settings on a service within a stack.

```bash
docker service logs SERVICE # not working
docker service logs -f SERVICE # working
docker logs CONTAINER # working
docker logs -f CONTAINER # working
docker service update --force SERVICE # stuck, but service was restarted
```

This resolves my issue. Thanks @alexmnt !
```bash
docker swarm ca --rotate
```

> Since single node cannot be out of sync with itself.

This is true. But i think rotating the certs, resolves some invalid state inside docker. But this is just a presumption.

**Comment by consiahras** [comment]
I had this issue as well.
One of the nodes seems to had a communication problem with manager.

docker service logs SERVICE # not working for 1 container from problematic node
docker service logs -f SERVICE # working normally but i had some errors in docker daemon

I tried restarting docker on the problematic node and this worked for me.

**Comment by cconstab** [comment]
This issue lives on! Rotating fixes/nudges for sure... 19.03.13

**Comment by rkrn** [comment]
Encountered this on 19.03.12.

**Comment by miko** [comment]
Hello, I have encountered it (for the first time ever) on my development laptop, using ArchLinux.
```$ docker node ls
ID                            HOSTNAME   STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
kmd1jpjoshqyqroulbekzj2di *   mikodell   Ready     Active         Leader           20.10.2
```
Using `docker swarm ca --rotate` helped. Removing whole stack and all containers / images did not help.

**Comment by VijayStroup** [comment]
Had the same issue as well running docker swarm on a single manager node with docker v19.03.13

I tried `docker swarm ca --rotate` which also did not work for me.

In the end I stumbled across this comment on a [similar issue](https://github.com/caprover/caprover/issues/636#issuecomment-603996316), and it worked just like a charm.

This bug was very odd as I was just taking down and putting up the same stack and it randomly gave me this error.

**Comment by WiMetrixDev** [comment]
any help how to fix this issue

**Comment by chrisbecke** [comment]
God I wish.

I just have a script that I have to run every 2 or so months when its apparent that vxlans are broken and not self healing :-

```
ansible node-1 -m systemd -a "name=docker state=restarted" -b
sleep 5
ansible node-2 -m systemd -a "name=docker state=restarted" -b
...
```

fun. not.

**Comment by Olegt0rr** [comment]
Still actual.

Also can't use `docker swarm ca --rotate` cause it's freezes on 0/12
```
desired root digest: sha256:<hidden>
  rotated TLS certificates:  [>                                                  ] 0/12 nodes
  rotated CA certificates:   [>                                                  ] 0/12 nodes
```

**Comment by mehdibenhamouche** [comment]
docker swarm ca --rotate for renew links between nodes works for me.

**Comment by webhive** [comment]
Holy cow - it saved my life

```
docker swarm ca --rotate
```

Just restarted server with 918 days uptime and single node cluster stuck. After this command everything becomes working well.

**Comment by az-z** [comment]
I have a single node setup on fedora 39 x64 (Fedora Linux 39 (Thirty Nine)).
```
docker --version
Docker version 25.0.0, build e758fe5
```
I have been playing for the past 2 days with the swarm mode. Before that I occasionally (once in a few months) would test/build a container or two.

I was getting the same error as described while trying to pull a log (docker service logs <service> ) after a container failed. The container was missing mounts and was constantly restarting.
After I rotated the ca, I was able to get logs.
Here are the systemd logs:
```
Feb 22 16:27:47 dell5000 audit[110681]: NETFILTER_CFG table=mangle family=2 entries=8 op=xt_replace pid=110681 subj=kernel comm="iptables"
Feb 22 16:27:48 dell5000 avahi-daemon[1049]: Joining mDNS multicast group on interface vethf5ccb2e.IPv6 with address fe80::cc2c:6ff:fe91:916a.
Feb 22 16:27:48 dell5000 avahi-daemon[1049]: New relevant interface vethf5ccb2e.IPv6 for mDNS.
Feb 22 16:27:48 dell5000 avahi-daemon[1049]: Registering new address record for fe80::cc2c:6ff:fe91:916a on vethf5ccb2e.*.
Feb 22 16:29:36 dell5000 dockerd[37416]: 2024/02/22 16:29:36 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
Feb 22 16:30:03 dell5000 dockerd[37416]: time="2024-02-22T16:30:03.325912923-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:vy1d7vhwyalbpecbgxj5opkdm leaving:false netPeers:1 entries:5 Queue qLen:0 netMsg/s:0"
Feb 22 16:30:03 dell5000 dockerd[37416]: time="2024-02-22T16:30:03.326140788-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:9m3vby6ic0v4vk4aeo45jv88o leaving:false netPeers:1 entries:11 Queue qLen:0 netMsg/s:0"
Feb 22 16:30:05 dell5000 systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
Feb 22 16:30:05 dell5000 systemd[1]: sysstat-collect.service: Deactivated successfully.
Feb 22 16:30:05 dell5000 systemd[1]: Finished sysstat-collect.service - system activity accounting tool.
Feb 22 16:30:05 dell5000 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=sysstat-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 16:30:05 dell5000 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=sysstat-collect comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 16:35:03 dell5000 dockerd[37416]: time="2024-02-22T16:35:03.525771288-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:vy1d7vhwyalbpecbgxj5opkdm leaving:false netPeers:1 entries:5 Queue qLen:0 netMsg/s:0"
Feb 22 16:35:03 dell5000 dockerd[37416]: time="2024-02-22T16:35:03.525915961-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:9m3vby6ic0v4vk4aeo45jv88o leaving:false netPeers:1 entries:11 Queue qLen:0 netMsg/s:0"
Feb 22 16:35:10 dell5000 dockerd[37416]: time="2024-02-22T16:35:10.797244113-05:00" level=info msg="cluster update event" module=dispatcher node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:10 dell5000 dockerd[37416]: time="2024-02-22T16:35:10.799709984-05:00" level=info msg="initialized VXLAN UDP port to 4789 " module=node node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:10 dell5000 dockerd[37416]: time="2024-02-22T16:35:10.800051469-05:00" level=info msg="forced certificate renewal" module=node/tls node.id=rik4ransx9ffpdtp9lq3k7c84 node.role=swarm-manager
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.345859929-05:00" level=info msg="initialized VXLAN UDP port to 4789 " module=node node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.351309163-05:00" level=info msg="initialized VXLAN UDP port to 4789 " module=node node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.373503653-05:00" level=info msg="agent: found node update" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.373566607-05:00" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.373617791-05:00" level=info msg="waiting 0s before registering session" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:11 dell5000 dockerd[37416]: time="2024-02-22T16:35:11.499259070-05:00" level=info msg="initialized VXLAN UDP port to 4789 " module=node node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.840682664-05:00" level=info msg="completed root rotation" method="(*Server).rootRotationReconciler" module=ca node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.840725738-05:00" level=info msg="cluster update event" module=dispatcher node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.854327184-05:00" level=info msg="agent: found node update" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.854390799-05:00" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.854444193-05:00" level=info msg="waiting 0s before registering session" module=node/agent node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:13 dell5000 dockerd[37416]: time="2024-02-22T16:35:13.859651004-05:00" level=info msg="initialized VXLAN UDP port to 4789 " module=node node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:18 dell5000 dockerd[37416]: time="2024-02-22T16:35:18.771249194-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.kw8rranuiwk9borxuseduyati" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:18 dell5000 dockerd[37416]: time="2024-02-22T16:35:18.771394494-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.7nhlmp5fpe2yydxslu42al1uc" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:18 dell5000 dockerd[37416]: time="2024-02-22T16:35:18.771486646-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.sgvvadjflz0x9l17uvraf233v" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:35:18 dell5000 dockerd[37416]: 2024/02/22 16:35:18 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
Feb 22 16:40:03 dell5000 dockerd[37416]: time="2024-02-22T16:40:03.725557530-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:vy1d7vhwyalbpecbgxj5opkdm leaving:false netPeers:1 entries:5 Queue qLen:0 netMsg/s:0"
Feb 22 16:40:03 dell5000 dockerd[37416]: time="2024-02-22T16:40:03.725658951-05:00" level=info msg="NetworkDB stats dell5000(b289219e8ea6) - netID:9m3vby6ic0v4vk4aeo45jv88o leaving:false netPeers:1 entries:11 Queue qLen:0 netMsg/s:0"
Feb 22 16:40:05 dell5000 systemd[1]: Starting sysstat-collect.service - system activity accounting tool...

```

around 16:27, the container was able to start and thus the service became functional.
at 16:29:36 i tried to pull logs.

Interestingly, now, for every call to logs (docker service logs .. ) I get:
```
Feb 22 16:53:07 dell5000 dockerd[37416]: time="2024-02-22T16:53:07.466525771-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.kw8rranuiwk9borxuseduyati" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:53:07 dell5000 dockerd[37416]: time="2024-02-22T16:53:07.468302459-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.sgvvadjflz0x9l17uvraf233v" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:53:07 dell5000 dockerd[37416]: time="2024-02-22T16:53:07.468462728-05:00" level=error msg="logs call failed" error="failed getting container logs: No such container: sms_jasmin.1.7nhlmp5fpe2yydxslu42al1uc" module=node/agent/taskmanager node.id=rik4ransx9ffpdtp9lq3k7c84
Feb 22 16:53:07 dell5000 dockerd[37416]: 2024/02/22 16:53:07 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
```

from the container(service) logs it is clear that the container was stopped. But the service is up:
```
docker service ls
ID             NAME            MODE         REPLICAS   IMAGE                           PORTS
hw9hpsy22x7q   sms_BLAH      replicated   1/1        blah/blah:93_3153476   *:1401->......
```

**Comment by DennisNgrox** [comment]
docker swarm ca --rotate

Funcionou para mim
