### ISSUE TITLE
Why I cannot stop, kill, rm a zombie container in swarm mode?

### ISSUE THREAD

**Issue by alirezastack** [moby/moby#35908]
`docker info` output:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 9heif6mx9x609849g3696qmjr
 Is Manager: true
 ClusterID: 1hh2h6q4yrietvr2c5vtnfxv5
 Managers: 1
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.16.132.20
 Manager Addresses:
  172.16.132.20:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.3GiB
Name: infra.fax.ir
ID: CSUK:HD34:DJUN:BLCL:DCRI:GAXK:G4IU:PAEG:ZWXC:G2F6:VUWO:SVA6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

And `docker version` output is as follow:
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

And `uname -a` outputs:
`Linux infra.fax.ir 4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.65-3+deb9u1~bpo8+1 (2017-12-23) x86_64 GNU/Linux`

We have specified `2 replica` for the service, after restarting the service there are 4 instance up! The other 2 has not been stopped. When I try to `kill`, `rm -f` or try to `stop` a container which does not responding it hangs forever.

I'm stuck here! Any help would be appreciated.

**Comment by thaJeztah** [comment]
There's two things at hand here;

- apparently you have a container that hangs; without more information, that's gonna be hard to help you with (what's running in the container? why does it hang? are there any logs that may reveal what's happening there?)
- you end up with more containers than specified in your service

The second issue is because Docker reconciles actual state with desired state; you specify that you want _two_ instances to be up. However, for some reason, those containers do not report healthy (or, docker is not able to get their state; again more information would be needed for that); as a result, it kills the old containers, and spins up new instances to replace the old ones.

Are the old containers actually still running, or have their processes already been killed? (i.e. if you inspect those containers, do they show a process-id, and is that process still running?)

Note that manually `docker stop`-ing, `docker restart`-ing, or `docker kill`-ing a container that's part of a service will make the container you manually stopped no longer be monitored by docker (i.e., it's no longer managed as part of the service); once you've done so, you _will_ end up with more containers running than specified in the service, because new containers have replaced them.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

If you think there's a bug, please make sure to provide more information (as mentioned above); without more information and exact steps to reproduce, it won't be possible for anyone to resolve the issue.

**Comment by alirezastack** [comment]
Thank you for the time and response.
Modules are written in `Python`, if by `Hang` you mean the app itself, I should note that it has not been hung for 2 years (from the beginning) when it was outside of docker.

Inside of container there is `gRPC` server that serves rpc requests, when it receives `SIGKILL` it gets terminated and in the container logs it is reported that it has been shut down gracefully.

They are not actually running, when I try to log into the container it hangs forever. When I try to inspect the culprit container, this command hangs forever too! What I did was to `ps -ef | grep CONTAINER_ID` and then kill that process in host OS.

I do not restart containers this way what I do is to use something similar to:

`docker service update --stop-grace-period=20s --update-order=stop-first SERVICE_NAME`

I assume that this is a bug and I have reported here because of that. What information is exactly needed? Service log? Docker daemon log?

I appreciate for the help.

**Comment by alirezastack** [comment]
These are the error in `syslog`:

```
Jan  3 10:54:40 host2 dockerd[6405]: time="2018-01-03T10:54:40.644697742Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jan  3 10:54:40 host2 dockerd[6405]: time="2018-01-03T10:54:40.644896769Z" level=warning msg="Your kernel does not support swap memory limit"
Jan  3 10:54:40 host2 dockerd[6405]: time="2018-01-03T10:54:40.644938354Z" level=warning msg="Your kernel does not support cgroup rt period"
Jan  3 10:54:40 host2 dockerd[6405]: time="2018-01-03T10:54:40.644947973Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Jan  3 10:54:40 host2 dockerd[6405]: time="2018-01-03T10:54:40.645424396Z" level=info msg="Loading containers: start."

```

I could not stop the docker service, but when I killed the below process, docker started normally and I could easily stop it:

`root       671     1  0  2017 ?        00:01:43 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/9470dd56456a78facfc6bd906301ef27029213e08d5baf7f912ef924b3affc07 -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/bin/docker-containerd -runtime-root /var/run/docker/runtime-runc
`

@thaJeztah I think the above logs would help to address the issue.

**Comment by thaJeztah** [comment]
Those syslog messages are quite standard, they basically mention that the daemon started successfully, and that your kernel does not have support for some features (limiting memory for containers being one of them, so that's something that would be recommended to enable).


The `docker-containerd-shim` process is a wrapper process for the container (it's used for the "live restore" feature to allow shutting down docker and containerd, but keeping the container running).

One thing that's possible is that the container's process already exited, but for some reason, the "shim" kept running; docker trying to start/stop/kill the container process would then probably fail.

If this is a new installation, it may be good to update to the latest (17.12) stable version of Docker, which switched to containerd 1.0.

**Comment by alirezastack** [comment]
After upgrading to stable version `17.12`, problem has been solved and those pesky issue gone away.

**Comment by genki** [comment]
I am still facing same problem even on 17.12.
It may be same issue with #35594.
