### ISSUE TITLE
Files deleted via rm command in a separate Dockerfile instruction are still present in the resulting Docker image.

### ISSUE THREAD

**Issue by blueimp** [moby/moby#37176]
**Description**

Files deleted via `rm` command in a separate `Dockerfile` instruction are still present in the resulting Docker image.

This is not reproducible on all tested machines (e.g. not on Docker for Mac), so seems to be specific to the environment.

**Steps to reproduce the issue:**
1. Create the following `Dockerfile`:
```Dockerfile
FROM busybox
RUN echo BANANA > /banana
RUN rm -f /banana
CMD ["cat", "/banana"]
```
2. Build the docker image:
```sh
docker build -t banana .
```
3. Run the docker image:
```sh
docker run --rm banana
```

**Describe the results you received:**

The container prints `BANANA` to `stdout`.

**Describe the results you expected:**

The container should print the following to `stderr`:
```
cat: can't open '/test': No such file or directory
```

**Environment information**

**Output of `docker version`:**

```
Client:
 Version:	17.12.1-ce-rc2
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	b0992d2
 Built:	Wed Feb 21 23:29:41 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce-rc2
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	b0992d2
  Built:	Wed Feb 21 23:36:45 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 60
Server Version: 17.12.1-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 userns
Kernel Version: 4.9.81-35.56.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2MiB
Name: ip-172-31-54-202
ID: 2F2C:4CVR:2RSF:LQUU:CXX4:SOVG:PKQ3:DFMA:FDFY:IEUY:WPU6:YUN3
Docker Root Dir: /var/lib/docker/501.501
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 33
 System Time: 2018-05-30T12:59:55.34921733Z
 EventsListeners: 0
Username: allthingsbot
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is a build server deployed via [Buildkite's Elastic CI Stack for AWS](https://github.com/buildkite/elastic-ci-stack-for-aws).

I found some related issues, e.g. #9093 and #25731, but they seem to be related to the `aufs` storage driver, not `overlay2`.

**Comment by cpuguy83** [comment]
>  17.12.1-ce-rc2

This version is not supported.
I'm pretty sure this issue is fixed in later versions.

ping @thaJeztah

**Comment by thaJeztah** [comment]
Yes, this is fixed in current versions;

```bash
docker build --no-cache -<<'EOF'
FROM busybox
RUN echo BANANA > /banana
RUN rm -f /banana
CMD ["cat", "/banana"]
EOF
```
```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM busybox
 ---> 8c811b4aec35
Step 2/4 : RUN echo BANANA > /banana
 ---> Running in 36f329e13be6
Removing intermediate container 36f329e13be6
 ---> 915e57d1a75c
Step 3/4 : RUN rm -f /banana
 ---> Running in d95e2f863675
Removing intermediate container d95e2f863675
 ---> e0f04af5ed4d
Step 4/4 : CMD ["cat", "/banana"]
 ---> Running in 1d9bc489d3f3
Removing intermediate container 1d9bc489d3f3
 ---> 17519f32b536
Successfully built 17519f32b536

docker run --rm 17519f32b536
cat: can't open '/banana': No such file or directory
```


I'd have to dig for the fix, but current versions should have it.

Note that (as @cpuguy83 mentioned), Docker 17.12 has reached end of life, so I highly recommend updating to a current version; I'll close this issue because this should be fixed, but feel free to comment if you're still able to reproduce on an updated version

**Comment by ddelbondio** [comment]
@thaJeztah I can still reproduce this behaviour, although not with your example.

### Reproduce steps
```
docker build --no-cache -<<'EOF'
FROM datadog/agent:6.10.1-jmx
RUN rm /etc/datadog-agent/conf.d/kubernetes_state.d/auto_conf.yaml
CMD ["ls", "/etc/datadog-agent/conf.d/kubernetes_state.d/"]
EOF

docker run --rm b38dcf642eb9
auto_conf.yaml
conf.yaml.example
```

### Docker Version
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

### Docker Info
```
Containers: 131
 Running: 3
 Paused: 0
 Stopped: 128
Images: 279
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 6YRL:NQVB:7ZVF:XCXA:STQD:FDVS:XC6X:Z7ID:NXOD:ESKK:2NOE:L2UE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 50
 Goroutines: 100
 System Time: 2019-03-08T12:24:30.2062274Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by thaJeztah** [comment]
Hm, I can reproduce that with the classic builder;

```bash
DOCKER_BUILDKIT=0 docker build --no-cache -<<'EOF'
FROM datadog/agent:6.10.1-jmx
RUN rm /etc/datadog-agent/conf.d/kubernetes_state.d/auto_conf.yaml
CMD ["ls", "/etc/datadog-agent/conf.d/kubernetes_state.d/"]
EOF

# ...
# 
# Successfully built 42ceb3095758

docker run --rm 42ceb3095758
auto_conf.yaml
conf.yaml.example
```


Looks to work correctly with BuildKit enabled;


```bash
DOCKER_BUILDKIT=1 docker build --no-cache -<<'EOF'
FROM datadog/agent:6.10.1-jmx
RUN rm /etc/datadog-agent/conf.d/kubernetes_state.d/auto_conf.yaml
CMD ["ls", "/etc/datadog-agent/conf.d/kubernetes_state.d/"]
EOF

# ...
# => exporting to image                                                                                                                                                                             # 0.0s
#  => => exporting layers                                                                                                                                                                            # 0.0s
# => => writing image sha256:d5334154574405e4335f046a29189c284b0a6fcedeb585f8340277f05560e880

docker run --rm sha256:d5334154574405e4335f046a29189c284b0a6fcedeb585f8340277f05560e880
conf.yaml.example
```

I also tried using a different storage driver (`vfs`) to check if it's related to `overlay`, but that produced the same result.

**Comment by thaJeztah** [comment]
Oh! I see what's the issue;

```bash
docker inspect datadog/agent:6.10.1-jmx --format '{{json .Config.Volumes}}'
```

Which shows that `/etc/datadog-agent` is defined as a _volume_:

```json
{
  "/etc/datadog-agent": {},
  "/tmp": {},
  "/var/log/datadog": {},
  "/var/run/s6": {}
}
```

That means that any changes to those files are made in a _volume_ during build, and are not saved in the container's filesystem.

BuildKit has a slightly different behaviour, where `VOLUME` statements are not applied _during_ build, so it will actually modify the files that were originally in the given location, and only attach a volume when the container is run.

**Comment by thaJeztah** [comment]
So, it's not a _bug_, but we may need to discuss (or call out) the change in behavior with BuildKit; there was a pull-request/proposal once to make a similar change in the classic builder (see https://github.com/moby/moby/pull/7133), but that did not get merged (in fear of breaking people that _relied_ on the behavior of volumes being applied during build).

**Comment by ddelbondio** [comment]
@thaJeztah, thank you so much for the analysis. Is there any workaround to still be able to do this?
After checking the docs of the builder it is quite clearly mentioned that what i was trying to do is unsupported. 
What I am wondering is if it is possible (if that change is not going to be applied) to at print a warning during build that a modification of a volume happened which will be dropped.
