### ISSUE TITLE
Incorrect time in containers

### ISSUE THREAD

**Issue by cmeeren** [moby/moby#37283]
**Description**

I experience incorrect time in containers based on various images. Put shortly, it seems that for many images, the container time always start at the same time regardless of host time.

Here are CMD commands/output that demonstrate the problem and can be used for reproduction:

```
C:\Users\Christer>time
The current time is:  9.32.03,72
Enter the new time: <Ctrl-C>
C:\Users\Christer>docker run -it microsoft/nanoserver:1803 cmd
Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>time
The current time is: 18:23:46.36
Enter the new time: <Ctrl-C>
C:\>exit

C:\Users\Christer>time
The current time is:  9.32.30,37
Enter the new time: <Ctrl-C>
C:\Users\Christer>docker run -it microsoft/nanoserver:1803 cmd
Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>time
The current time is: 18:23:46.12
Enter the new time:
```

As you can see, the container's time always seem to start at the same time regardless of host time. This means it does not not seem related to timezones.

I experience this consistently e.g. with `microsoft/nanoserver:1803` as well as `microsoft/nanoserver:1709`, but `microsoft/nanoserver:sac2016` works fine.

However, when I posted the steps in [this MSDN thread](https://social.msdn.microsoft.com/Forums/en-US/6b13bf8e-d3fb-450a-b0f3-db1aed4fb041/some-windows-server-core-docker-images-report-incorrect-times?referrer=http://social.msdn.microsoft.com/Forums/en-US/6b13bf8e-d3fb-450a-b0f3-db1aed4fb041/some-windows-server-core-docker-images-report-incorrect-times?forum=windowscontainers), another poster was unable to reproduce it. This makes me think it's not related to the images themselves. And since the closing comment of the seemingly similar issue https://github.com/docker/for-win/issues/1288 made it clear that moby was the right place for such a bug report, here I am, quite lost and unable to figure out how to proceed.

As mentioned in the MSDN thread I linked to, I tried running the images with process isolation, but it seems that's not possible:

```
C:\Users\Christer>docker run --isolation process -it microsoft/nanoserver:1803 cmd
docker: Error response from daemon: Windows client operating systems only support
Hyper-V containers.
See 'docker run --help'.
```

I'll happily provide more info and do more testing, just tell me what's necessary.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 54
 Running: 0
 Paused: 0
 Stopped: 54
Images: 28
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.89GiB
Name: Navi
ID: VUXH:PMCX:6USB:3B7W:QTEP:WQT3:BV42:6VJN:XOYG:RQRO:QW4K:SZER
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2018-06-14T15:14:57.4023897+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Hammatt** [comment]
Just to add to this. I'm also experiencing this issue and it's completely stopping Application Insights from working.

**Comment by cmeeren** [comment]
Area you experiencing it in production or only locally during development? (I haven't deployed any containers yet.)

**Comment by Hammatt** [comment]
We're seeing this in development and in our "production like" test environment.  
(the system will be going into production at the end of month ish)

**Comment by TylerReid** [comment]
@cmeeren I am also experiencing this in local dev running microsoft/aspnet:4.7.1-windowsservercore-1709 . Haven't deployed anything yet.

> 
> PS C:\Users\treid> [DateTime]::UtcNow
> Wednesday, June 20, 2018 3:37:59 PM
> 
> PS C:\Users\treid> docker exec ecb42475501e powershell [DateTime]::UtcNow
> Wednesday, June 20, 2018 6:39:03 PM
> 
> PS C:\Users\treid> docker info
> Containers: 14
>  Running: 14
>  Paused: 0
>  Stopped: 0
> Images: 72
> Server Version: 18.03.1-ce
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: ics l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
> Swarm: inactive
> Default Isolation: hyperv
> Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
> Operating System: Windows 10 Pro
> OSType: windows
> Architecture: x86_64
> CPUs: 8
> Total Memory: 31.86GiB
> Name: ATL-1988-win
> ID: SJDR:EK5G:QO6K:5PWL:ABHG:7V5L:6ZRU:WWIV:FTYE:IELJ:YQM2:3GSL
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: -1
>  Goroutines: 166
>  System Time: 2018-06-20T11:39:16.9492402-04:00
>  EventsListeners: 1
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by rogersillito** [comment]
I'm seeing this too - container time is a few hours different when I use an image [based upon](https://hub.docker.com/r/jetbrains/teamcity-minimal-agent/) windowsservercore-1709.   This is a blocking issue as we are using this to run time-sensitive tests.   Switching to the alternative that uses windowsservercore-ltsc2016 does not show the problem (but I have other stability problems with this image).  The environment we're running in:


**docker version:**
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```
**docker info:**
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.71GiB
Name: KKD-BLD
ID: UMMJ:CZMV:RVL4:WHNJ:VSIB:YSIM:GDQE:3O27:3RJV:2KV4:Q7S2:DGNQ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2018-06-29T12:15:41.8518753+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by nzav** [comment]
Can confirm this behaviour. Highly frustrating :/

**Comment by Stannieman** [comment]
I can confirm somewhat similar behavior. 2 images based on windowsservercore 1803, both run about 7 hours ahead of the host. The host has never been suspended, only running or completely shut down (but shut down only for maybe 1 hour in total). Removing and recreating the containers doesn't help.
The containers are used as guild agents and they timestamp the builds, so this is very inconvenient.

**Comment by olljanat** [comment]
I can confirm information what is said on MSDN thread. This issue only happens if you are using Hyper-V isolation mode. And based on my experience I do **not recommend** that for anyone.

To be able to use process isolation mode you need use **same OS version** on **host** and **containers** so:
- Window Server 2016 can run microsoft/windowsservercore:**ltsc2016** and microsoft/nanoserver:**sac2016**
- Windows Server, version 1709 can run microsoft/windowsservercore:**1709** and microsoft/nanoserver:**1709**
- Windows Server, version 1803 can run microsoft/windowsservercore:**1803** and microsoft/nanoserver:**1803**
on process isolation mode.

If you are new with Windows containers I highly recommend to check my git repo where I have been keep track what works and what not https://github.com/olljanat/docker-issue-tracking

**Comment by rogersillito** [comment]
@olljanat thanks - really useful information.  Can you point me towards the _MSDN thread_ you refer to?

**Comment by olljanat** [comment]
@rogersillito I was meaning that original message on this issue which links to MSDN thread but looks that they actually just suggested to try process isolation mode.

Anyway, I can tell that we have multiple Win 2016 and 1803 hosts and containers running on production using process isolation mode and there is not any issues with incorrect time (we even OAuth with apps so time much be correct to make authentication working).

**Comment by thaJeztah** [comment]
ping @patricklang @jstarks PTAL

**Comment by Stannieman** [comment]
Isolation mode can be very useful when:
- You don't want to restrict your container windows versions to match the host. If you have 1 host then there is no way to start using newer container versions already, and if you upgrade the host this would force you to rebuild all your images. This is not always feasible.
- You can use Windows 10 Pro as host instead of Windows Server. Especially when you're using containers in a home/hobby environment the additional price for a Server license is a no go.

**Comment by olljanat** [comment]
@Stannieman Yea. That is most probably reason why they are developing these things.

I just belong to that rare group of people who are crazy enough to run Windows containers on production and that I have pent huge amount for time to figure out what is actually production ready. 
Hyper-V isolation mode is it not.

**Comment by MPapst** [comment]
Any idea, when this will be adressed?
This is really an issue for Azure IoT Edge under Windows

**Comment by olljanat** [comment]
@MPapst unfortunately it looks to be that only way to get support for Windows Containers issues is create premier support case for Microsoft. 
You can also try create issue to Azure IoT Edge repo like it is described in this page: https://docs.microsoft.com/en-us/azure/iot-edge/support and link to this issue. 

That page is btw talking about "Windows 10 Server 1803", if that means [semi-annual channel](https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview) version of Win Server you can (and I also recommend) use it. That version can run Windows Containers using process isolation mode which does not have this issue and which also offers much better performance.

**Comment by MPapst** [comment]
@olljanat, I just created an issue in the IoTEdge project.

Windows Server edition is unfortunately not an option for embedded devices as IoTEdge devices should be.

**Comment by jhowardmsft** [comment]
Myself and @johnstep have tried to repro this to no avail. I'd like to understand what is going on here though as it seems there are a number of people hitting it. It's clear from above, it's specific to Hyper-V containers, which makes sense due to how they are instantiated relative to process-isolated Windows Server containers.

If someone is hitting this consistently, can they try the following from an elevated powershell  prompt to clear up:


First: Capture the environment. Run `hcsdiag list` and `Get-ComputeProcess` and save the output. Also save everything in `C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM`.

Then `Get-ComputeProcess | Stop-ComputeProcess -Force` and retry. Did that fix it?

If not, same command as above. Then delete everything in `C:\ProgramData\Microsoft\Windows\Hyper-V\Container Utility VM`. Then net stop vmcompute and net start vmcompute and retry. Did that fix it?

**Comment by olljanat** [comment]
@jhowardmsft you are not able to repro? 😮
That issue happens all the time on all the machines.

Just take Win 10, version 1803 machine, put latest Docker CE to it.
Then run start container with command: ```docker run -it --isolation hyperv microsoft/windowsservercore:1803 powershell```
and run command ```[System.DateTime]::UtcNow``` on host and inside of container.


I also just tested that I can repro this issue using "Windows Server, version 1803 with Containers" template from Azure. Just make sure that you deploy it to some of the [Dv3](https://azure.microsoft.com/en-us/blog/introducing-the-new-dv3-and-ev3-vm-sizes/) supported location (D2s_v3 on West Europe).

On there you can also try start another container with command ```docker run -it --isolation process microsoft/windowsservercore:1803 powershell``` and see difference.

Here is also screenshot fro you from that one:
![image](https://user-images.githubusercontent.com/6213926/43490585-f9b0c046-9529-11e8-809f-580b7256e84d.png)

**Comment by Stannieman** [comment]
For me the Hyper-V containers are running 6h58m36s ahead of local time, for @olljanat this is 6h58m21s. Some difference in seconds due to when we run the command probably. Much more important is that this is almost exactly 7 hours. And Redmond's local time is currently... yep, 7 hours behind UTC.

From how on are only speculations but:
I don't think this is really a bug in the images, but rather something wrong with the build process. The build machine might have it's time set equal to UTC but it's time zone still set to Redmond time or visa versa, and then somehow this causes a constant offset in the base images. If the build machine does never sync time with the internet this won't get automatically corrected. This would also explain why the offset is 1m24s different from the 7 hours: due to the lack of time syncing the time of the build machine drifted over time. If this scenario is true then this is quite worrying though: the time in containers can then only be as correct as the time on the build machine. IMO the containers should sync with the host they are running on without any offset caused by the build.

I will try the suggestion of @jhowardmsft later tonight. BTW maybe the reason you cannot repro is because you are actually in Redmond.

**Comment by olljanat** [comment]
@Stannieman note that I got both correct and wrong time from same image by just changing isolation mode. So it cannot be issue on build process. 

But you can easily test your theory by deploying VMs to different Azure sites.

**Comment by jhowardmsft** [comment]
It looks like it's a combination of a race condition, and if your host is set to a TZ east of PST. An RS4 backport is in the works. I'm chasing RS1 and RS3 backports but have/cannot promise any ETA yet. Note the fix is to the utility VM image, not the host, so will require images built from updated base images.

**Comment by Stannieman** [comment]
@cmeeren I can't repro it on my machine (due to race condition?), but  it happens all the time on a VM at work. Container time does never start at the same time, but always with the same offset from real time. So that's a different from what the OP experiences.

**Comment by cmeeren** [comment]
In any case, as I understand it, updated images are coming with a possible fix for the problem. Perhaps we should just wait until they're released and see if the problem goes away entirely.

**Comment by jhowardmsft** [comment]
The current ETA for updated RS3/RS4 base-image-backports is 2018/8B which means container images release on patch-Tuesday of August 2018. There's no guarantee though - it may slip to Sept 2018 updates. (I have no control over backports, just relaying on information from internal sources).

**Comment by blakeja** [comment]
Thanks for the update @jhowardmsft!  Having any kind of timeframe for a potential fix is better than none at all.

**Comment by ylhyh** [comment]
Found a rule:

- **hyperv** mode
1. if container time later than host time, container time will synchorized with host time immediately
2. if container time earlier than host time, container time will not synchorize with host time

- **process** mode
container time will synchorized with host time at any time

**Comment by blakeja** [comment]
@jhowardmsft Any updates?

**Comment by jhowardmsft** [comment]
As far as I can tell from internal info, it went out in the patch-Tuesday container images updates in August. You need to use images built on those base images.

**Comment by alexanderch** [comment]
This issue still exists on both containers microsoft/nanoserver:1709 and microsoft/windowsservercore:1709

**Comment by olljanat** [comment]
@alexanderch are you sure that you have pull latest version (try re-run ```docker pull``` command)?

Other thing is that I'm not fully sure that fix was included to that over one year old 1709 version. Try use 1803 instead of.

**Comment by alexanderch** [comment]
Yes, I did pull the latest images. As you can see it was created in 2018-09-11.

We can't use 1803 because not all our developers have the latest Windows 10.

`PS C:\WINDOWS\system32> docker image inspect microsoft/windowsservercore:1709
[
    {
        "Id": "sha256:bf0f869ed4b979469712438d6741f0ca2e442ee86e038a94363ddc852d2f5d16",
        "RepoTags": [
            "microsoft/windowsservercore:1709"
        ],
        "RepoDigests": [
            "microsoft/windowsservercore@sha256:1bd535b56b751a434bb7d70c488567674553d5c2ee53cfec3550cdde3add3073"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-09-11T11:01:47.6028802-07:00",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "c:\\windows\\system32\\cmd.exe"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.16299.665",
        "Size": 6438733843,
        "VirtualSize": 6438733843,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\c34499d98f4e6fb3360c7dc5d96ab46b366b8c6f9f07b928573a51a1f87973ce"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4bfe49d7bc33014df317149be23a71dfe176f2ddd6a78977068a37973dde89d8",
                "sha256:877f50cb107aefb09aa63951b7c250d146f1d95c9f111f337a66034e440e5302"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]`

When I run it
 It shows time almost 17 hours ahead
`PS C:\WINDOWS\system32> get-date

Monday, 24 September 2018 3:45:47 PM

PS C:\WINDOWS\system32> docker run microsoft/windowsservercore:1709 powershell get-date

Tuesday, September 25, 2018 8:45:32 AM
`

**Comment by Stannieman** [comment]
> We can't use 1803 because not all our developers have the latest Windows 10.
You are aware that on Windows 10 Pro version they don't need to match OS version?

**Comment by MPapst** [comment]
Does not work in 1803 either.

```
λ  get-date

Tuesday, September 25, 2018 4:11:04 PM

λ  docker run --rm microsoft/windowsservercore:1803 powershell get-date

Wednesday, September 26, 2018 1:08:34 AM
```

**Comment by alexanderch** [comment]
I can confirm that 1803 doesn't work also 
`PS C:\WINDOWS\system32> get-date

Wednesday, 26 September 2018 9:24:31 AM

PS C:\WINDOWS\system32> docker run --rm microsoft/windowsservercore:1803 powershell get-date

Thursday, September 27, 2018 2:24:21 AM`

> Edit:
> latest tag works!

the latest tag is the same image as ltsc2016(not 1803) which is almost not possible to use because of size and architecture. it only runs in Hyper-V isolation on the server.

**Comment by ylhyh** [comment]
It is confirmed that the issue has been fixed in latest image tag:

- Docker

 Image Tag:
microsoft/windowsservercore:1803 sha256:2500cd452a6649fad8bb530407a825fe032b3b2abfcec57757ca06849e189c17
- Host OS: Windows 10 1803 (Build 17134.285)
- Isolation: hyperv

**Comment by BenParks32** [comment]
Still seeing this is in:
-- microsoft/windowsservercore:1803
-- sha256:2500cd452a6649fad8bb530407a825fe032b3b2abfcec57757ca06849e189c17

**Comment by Stannieman** [comment]
> > You are aware that on Windows 10 Pro version they don't need to match OS version?
> 
> For 1803 you still need to install Windows 10 April 2018 Update.

Ok wow, seems you are right because the insider RS5 images also won't run on a 1803 host. Stange... I always believed this was one of the key differences why you'd choose Hyper-V containers over native ones. Did I understand this wrong and is it related to patch level instead of actual semi-annual version?

@jhowardmsft thanks for the heads up!

**Comment by aphil** [comment]
I also have the issue with the dotnet images. You guys have found any workarounds?

**Comment by andrew-morgalla** [comment]
Same here with the dotnet images and getting access denied if i try to change the timezone with Set-Timezone in PowerShell.

**Comment by mrfrankbell** [comment]
1803 Docker images have been updated in the last few hours, taking the version of Nano Server to 10.0.17134.345. Running docker history shows the update was installed 8 days ago, which is when @jhowardmsft said that there were issues getting the fix out.

@jhowardmsft Could you confirm whether the fix is included in this build or still forthcoming please?

PS - does anything special perhaps need to be done to carry the time zone of the host through when running Windows Server containers with Hyper-V isolation?

**Comment by davemedvitz** [comment]
Time issue still exists in windowsservercore:1803

`PS>docker run microsoft/windowsservercore:1803 powershell get-date

Wednesday, October 17, 2018 1:24:21 PM

PS>get-date

Wednesday, October 17, 2018 10:31:43 AM`

microsoft/windowsservercore    1803                1a4a9d0fd8af        7 days ago          4.93GB

**Comment by ChrisEvansUM** [comment]
Still here for me too, although ltsc2016 seems to work, along with nanoserver:

PS C:\Users\notth> Get-Date

17 October 2018 21:03:36


PS C:\Users\notth> docker run microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803 powershell Get-Date

Thursday, October 18, 2018 5:04:00 AM


PS C:\Users\notth> docker run microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1709 powershell Get-Date

Thursday, October 18, 2018 5:04:22 AM


PS C:\Users\notth> docker run microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016 powershell Get-Date

Wednesday, October 17, 2018 9:05:17 PM


PS C:\Users\notth> docker run microsoft/nanoserver powershell Get-Date

Wednesday, October 17, 2018 9:05:58 PM

**Comment by ChrisEvansUM** [comment]
@jhowardmsft - can you reopen please?

**Comment by ChrisEvansUM** [comment]
@jhowardmsft any news on this please?

**Comment by ai2admin** [comment]
My 1709 containers are about 50 minutes ahead of the local system time. Restarting the machine doesn't work. Restarting the docker doesn't work. This is a showstopper for our business.

**Comment by olljanat** [comment]
Just to reminder for those who have missed information.

[I said](https://github.com/moby/moby/issues/37283#issuecomment-403751973) earlier that:
> This issue only happens if you are using Hyper-V isolation mode.

So easiest what to handle this issue for production envs is use Windows Server, version 1803 with process isolation mode.


[jhowardmsft said](https://github.com/moby/moby/issues/37283#issuecomment-409631712) earlier that:
> It looks like it's a combination of a race condition, and if your host is set to a TZ east of PST. An RS4 backport is in the works.

So that one can be used to be able to debug these images on Win 10.


Combination of Windows 10 1809 + Docker CE 18.09 [will support to use process isolation mode](https://github.com/docker/engine/pull/81).

What comes to get time sync working with Hyper-V isolation mode, I have no new information.

**Comment by ai2admin** [comment]
"use Windows 10 1809" suggestion might work for a small shop but not for an enterprise where engineering dept might have little say in the timeline for OS upgrades.

**Comment by olljanat** [comment]
@ai2admin true but IMO correct way to fix it would be still add backward compatibility to process isolation mode instead of use Hyper-V isolation which ruins of whole idea of tiny high performance containers. I added question about it to https://github.com/moby/moby/issues/35247#issuecomment-436386396

**Comment by ai2admin** [comment]
@olljanat that I fully agree with - yet I'd expect that a workaround for fixing the timer issue is less of a scope to implement

**Comment by andyfisher100** [comment]
My base image i'm using is "microsoft/dotnet-framework:4.7.2-runtime-20181113-windowsservercore-1803" and has been for weeks. Every time i have created an image it has been fine until today when the time is currently 14:44 (i'm in the UK) and the docker image reports 19:37.

i'm trying to create an Azure DevOps build machine in docker but can register the build agent with the server with the current time difference. Ant more updates on this?

**Comment by willemodendaal** [comment]
> Just to reminder for those who have missed information.
> 
> [I said](https://github.com/moby/moby/issues/37283#issuecomment-403751973) earlier that:
> 
> > This issue only happens if you are using Hyper-V isolation mode.
> 
> So easiest what to handle this issue for production is use Windows Server, version 1803 with process isolation mode.
> 
> [jhowardmsft said](https://github.com/moby/moby/issues/37283#issuecomment-409631712) earlier that:
> 
> > It looks like it's a combination of a race condition, and if your host is set to a TZ east of PST. An RS4 backport is in the works.
> 
> So that workaround can be used to be able to debug these images on Win 10.
> 
> Combination of Windows 10 1809 + Docker CE 18.09 [will support to use process isolation mode](https://github.com/docker/engine/pull/81).
> 
> What comes to get time sync working with Hyper-V isolation mode, I have no new information.

What does this mean practically speaking? Do I need to use a different base image, or a different version of Docker-for-Windows? Or change Hyper-V configuration somewhere?

**Comment by olljanat** [comment]
@willemodendaal those versions are first ones where you can use process isolation mode on Win 10.
General requirement for process isolation mode is that host version must match with containers base image version.

=> Windows 10, version 1809 can only run Windows Server 2019 (version 1809) on process isolation mode.

Anyway this is incorrect place to talk more about it so if you have more questions about it plz create new issue or ping me on Slack.

**Comment by mcandre** [comment]
What's the status of timezones for Windows images?

Does env var `TZ=UTC` work for configuring Windows images, or just Linux images?

**Comment by srinathck** [comment]
I have the same issue on WindowsServerCore:ltsc2019, 1709, 1803 images. TimeZone is off. It is frustrating considering there isn't any tzutil. And You can't really have wrong time in containers.

**Comment by hongaar** [comment]
Still running into this problem with current 1803 builds of both `servercore` and `nanoserver` on a resumed system, 1803 is wrong and 1903 gets it right:

```
$ docker run --rm mcr.microsoft.com/windows/servercore:1803 powershell get-date
Friday, August 16, 2019 6:29:27 PM

$ docker run --rm mcr.microsoft.com/windows/servercore:1903 powershell get-date
Friday, August 16, 2019 2:13:01 PM

$ docker run -it --rm mcr.microsoft.com/windows/nanoserver:1803
> time /t
11:12 PM 

$ docker run -it --rm mcr.microsoft.com/windows/nanoserver:1903
> time /t 
02:11 PM
```

@jhowardmsft do you know whether there's an open issue for this still, and if not, what would be the best way to report this behaviour?

--- 

Tested with current images (build date 08/13/2019) at the time of writing. Debug info:

```
$ docker image ls
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/windows/servercore   1903                55b4d18a7eea        2 days ago          4.89GB
mcr.microsoft.com/windows/nanoserver   1903                0f2627371859        2 days ago          256MB
mcr.microsoft.com/windows/nanoserver   1803                36ce77ed4519        2 days ago          371MB
mcr.microsoft.com/windows/servercore   1803                bde829e93918        2 days ago          5.12GB

$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 19.03.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.295)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.89GiB
 Name: JORAM
 ID: UXRG:JZHE:LJYR:BJAX:GK4Q:ENBU:7Q6G:NWHN:5UTZ:V2BA:KQCN:SCNU
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 34
  System Time: 2019-08-16T14:16:35.2768223+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by liberdis** [comment]
Adding this here even though it's closed because it's the most exhaustive thread i've found about this issue. @olljanat or @lowenna can you offer any insight? 

Similar to what @hongaar reports above I still see this on some w10 1903 docker hosts' containers (some deltas, see below). The time is always about four hours ahead. 

The host is able to sync to time.windows.com without issue and does show the current time.
The host is in EST timezone, but changing the timezone does not sync the time.
Have tried to follow this thread, do not see a conclusive 
Source image: I'm using mcr.microsoft.com/dotnet/framework/aspnet:4.7.2 as my source image, so, servercore

This may be relevant: the hosts that exhibit this symptom are all **azure-hosted** virtual machines that **are not domain-joined**. Conversely, I do not see this symptom on corporate network win10 domain-joined 1903 hosted containers using the same image, these appear to work properly and sync time to the host.

Windows 10 1903 18362.387
Host: Wednesday, October 2, 2019 11:47:54 AM
Container: Wednesday, October 2, 2019 2:19:08 PM

Winver: 
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:39:49 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by coip** [comment]
As another datapoint, Im getting some ~similar behaviour:
``` ash
ethan@host:~$ echo "container: $(sudo docker run alpine date)" && echo "host:      $(TZ="UTC" date)"
container: Wed Jan 15 03:41:01 UTC 2020
host:      Wed Jan 15 20:06:12 UTC 2020

ethan@host:~$ sudo docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
