### ISSUE TITLE
LCOW Memory Limits

### ISSUE THREAD

**Issue by rdaniels6813** [moby/moby#37859]
Allowing to set the memory limit for LCOW

docker run -ti -m 3GB alpine sh -c "cat /proc/meminfo | grep MemTotal"

Received:
MemTotal:         985560 kB

Expected:
MemTotal:        3045340 kB

**Comment by oldium** [comment]
I am just a random visitor, but hasn't this been fixed by merging #37296 recently? I have tested it and supplying the memory `-m` option worked for me on LCOW. Maybe this could be closed, then.

**Comment by rdaniels6813** [comment]
Yeah, this is outdated and I'll close it.

**Comment by prochnowc** [comment]
@oldium Which version did you use? I used latest edge release which include docker-engine 18.09.3. For me it still doesnt work.

**Comment by oldium** [comment]
@prochnowc try to take latest master builds at https://master.dockerproject.com/windows/x86_64/docker.zip and https://master.dockerproject.com/windows/x86_64/dockerd.zip, not version from last year
