### ISSUE TITLE
Unhealthy cluster: grpc: received message larger than max (4246471 vs. XXXX)

### ISSUE THREAD

**Issue by caiohasouza** [moby/moby#37941]
**Description**

**Steps to reproduce the issue:**
1. I don't know, the problem happened randomly.

**Describe the results you received:**
I received this error on /var/log/messages

> Sep 24 10:05:06 manager1 dockerd: time="2018-09-24T10:05:06.149068150-03:00" level=error msg="Handler for GET /tasks returned error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246471 vs. 4194304)"
> Sep 24 10:05:08 manager1 dockerd: time="2018-09-24T10:05:08.164933960-03:00" level=error msg="Error getting tasks: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246471 vs. 4194304)"

**Describe the results you expected:**
Any error and health cluster.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue happens only occasionally, when the issue happen i remove some stacks (until grpc size message is lower than 4246471 and start again).

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 45
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: djwoo6fnyoioqjcjbrn9vtwux
 Is Manager: true
 ClusterID: 9ftd1qnqfm2kny7gk8bjsxss0
 Managers: 3
 Nodes: 30
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.0.16
 Manager Addresses:
  10.0.0.16:2377
  10.0.1.8:2377
  10.0.2.57:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.637GiB
Name: manager1.domain.local
ID: JPSI:X5AM:AAFW:SP5P:UK2Z:F6S2:MA23:HVMJ:TC2U:3WT2:QB7I:BUHV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: opentecnologia
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker swarm cluster on AWS.

**Comment by xdexter** [comment]
someone?

**Comment by ToGo101** [comment]
Downgrading to Docker version 18.03 worked for me.

see: https://github.com/moby/moby/issues/37997#issuecomment-428317978

**Comment by kjelle** [comment]
I run docker version 18.06.1-ce on Centos 7.5.1804. I have messages around 319 MB. We run ~200 services with 1 container in each on about 25 worker nodes and 3 managers....

**Comment by caiohaz** [comment]
@kjelle and do you have some problem?

**Comment by kjelle** [comment]
@caiohaz - yes, currently we can't launch all the services we want in our docker cluster. We run as mentioned a few hundred services on ~25 ish worker nodes.. Sometimes we reach >300 MB grpc messages, so increasing the limit to 4MB, 8MB or whatnot doesn't really fix the problem.

I can't believe this is an issue. We have a relative (to major users) small cluster with a small number of services...

The reason we'r using Docker Engine in Swarm Mode is because we have moved away from Mesos with Marathon.

Alas, we'll probably end up with Kubernetes, but we fear it will increase our IT Ops complexity. Docker Engine in Swarm Mode seems relatively simple to run...

To circumvent the problem we have compiled our own swarmkit with a much higher limitation than the current 4MB to be able to manage the cluster when we experience this error...

Hope this problem will be fixed soon.

**Comment by caiohaz** [comment]
@kjelle thank you for your explication, i believe that this problem will be fixed soon too.

**Comment by kjelle** [comment]
Hello, any ideas when this will be released?

**Comment by caiohaz** [comment]
The fix was released in 18.09 version (#38123)?

**Comment by caiohaz** [comment]
Someone?

**Comment by grove** [comment]
This is still an issue in 18.09. I've seen it with both 'docker service ls' and 'docker config ls':

$ docker config ls -q
Error response from daemon: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20071330 vs. 4194304)

**Comment by caiohaz** [comment]
;/

**Comment by aido93** [comment]
Guys, I have this issue too... Any updates?
Also in this state I cannot even do `docker stack rm`. =\

**Comment by aido93** [comment]
I found out very hard solution for this issue. Suppose you know scheme of config names, so you can do something like this: `for i in $(seq 1553687981 1553697981); do docker config rm foo-$i; done`. After a lot of configs will be cleaned, `docker config ls` will work as usual.

**Comment by aido93** [comment]
I cannot remember where I found answer of @thaJeztah with the sample of code:
```
configs:
  whitelist:
    name: balancer-whitelist-$CI_COMMIT_SHA
    file: ./balancer-whitelist.lst
```
but be careful of using `CI_COMMIT_SHA` here

**Comment by grove** [comment]
I can confirm that the `docker config ls` issue has been fixed in 18.09.4.

**Comment by grove** [comment]
Looks like there are still GRPC limits in 18.09.4. I just found this in out Docker daemon log:

`Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.491792420Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.491879420Z" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.491911220Z" level=info msg="waiting 7.12554ms before registering session" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.616584376Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.616661375Z" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.616697975Z" level=info msg="waiting 4.788995ms before registering session" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.764015105Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.764163005Z" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.764198605Z" level=info msg="waiting 58.701182ms before registering session" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.901166147Z" level=error msg="agent: session failed" backoff=100ms error="rpc error: code = ResourceExhausted desc = grpc: received message larger than max
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.901339947Z" level=info msg="manager selected by agent for new session: { }" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jh
Apr 01 10:21:37 00e77a68-swarm-00 dockerd[183991]: time="2019-04-01T10:21:37.901412246Z" level=info msg="waiting 80.484371ms before registering session" module=node/agent node.id=slgmzl3uocs0ghjfu0xpr09jhf`

**Comment by thaJeztah** [comment]
@dperny would this be because of https://github.com/docker/swarmkit/blob/1a0ebd43b2d156983a695f90e56f4ecba6ced902/manager/manager.go#L276 ?

That size is still `4194304`; https://github.com/docker/swarmkit/blob/486ad69951868792367a503042ef3f55b399cc40/manager/state/raft/transport/peer.go#L22-L23

**Comment by dperny** [comment]
The max message size in the raft code shouldn't be relevant, because those messages should use the raft streaming API.

@grove's error messages refer to session re-establishment. I'm looking along that code path to figure out what the overly-large message might be that's causing that issue, because it's the best lead I have right now.

**Comment by khmariem** [comment]
I encountered a similar message when running `helm ls`, I believe that the logs are full to a bigger extent than what the service can handle. In helm for example, this can be avoided if `--history_max` is set to a finite number, say 200.
From the documentation, they are mentioning this: 

> Setting --history-max on helm init is recommended as configmaps and other objects in helm history can grow large in number if not purged by max limit. Without a max history set the history is kept indefinitely, leaving a large number of records for helm and tiller to maintain.

You should probably look for something similar in docker.

**Comment by thaJeztah** [comment]
@dperny did you manage to find something?

**Comment by Fusl** [comment]
```
root@ip-100-64-1-43:~# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
root@ip-100-64-1-43:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 2uabqx0m2usi8ygrv78sy62ut
 Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4298547 vs. 4194304)
 Is Manager: true
 Node Address: 100.64.1.43
 Manager Addresses:
  100.64.1.43:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1035-aws
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 61.48GiB
Name: ip-100-64-1-43
ID: QAEW:C4ZN:PJFS:V4NI:H2CM:I3XI:RBTU:OHAF:W74I:UIG4:EJZH:CAVD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
root@ip-100-64-1-43:~# docker node ls
Error response from daemon: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4298547 vs. 4194304)
root@ip-100-64-1-43:~# docker service ls
Error response from daemon: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4298547 vs. 4194304)
root@ip-100-64-1-43:~#
```

**Comment by dperny** [comment]
fixing the last comment here (about failures of node ls) in #39306
