### ISSUE TITLE
[aarch64]Cannot be executed "strace rpm --rebuilddb"within the container 

### ISSUE THREAD

**Issue by longquan7** [moby/moby#39566]
docker version 18.09 and use Storage Driver: overlay2 on aarch64 kernel version is 4.19

renameat(AT_FDCWD, "/var/lib/rpm", AT_FDCWD, "/var/lib/rpmold.107") = -1 EXDEV (Invalid cross-device link)
write(2, "error: ", 7error: )                  = 7
write(2, "failed to replace old database w"..., 50failed to replace old database with new database!
) = 50
write(2, "error: ", 7error: )                  = 7
write(2, "replace files in /var/lib/rpm wi"..., 83replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.107 to recover
) = 83
fcntl(3, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by thaJeztah** [comment]
Looks the same as https://github.com/docker/for-linux/issues/480, which is a kernel bug in kernel 4.19, and was fixed in kernel 4.19.11

**Comment by longquan7** [comment]
@thaJeztah I still have this problem with the post-fix version

**Comment by thaJeztah** [comment]
@kolyshkin ptal

**Comment by longquan7** [comment]
@thaJeztah I solved the problem because the feature switch corresponding to overlayfs is not turned on /sys/module/overlay/parameters/redirect_dir. thanks

**Comment by longquan7** [comment]
problem solving close

**Comment by longquan7** [comment]
problem solving close
