### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error 

### ISSUE THREAD

**Issue by farso92** [moby/moby#40287]
**Description**

**Steps to reproduce the issue:**
1. `docker run hello-world`

**Describe the results you received:**
`docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/9c30ed864953d25cc6897703a536403c83e5b8497dcc3dd8a486321cdfe61ab8/log.json: no such file or directory): runc did not terminate sucessfully: unknown.`

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried to change docker version and kernel but the error is still here
**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          0.3
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-23-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.703GiB
 Name: umberto-Lenovo-B50-80
 ID: W6Y7:NQCH:RN4L:AKMY:DQRX:DIL7:UYO3:PCM4:42AR:TDFH:F3AH:GOJL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by thaJeztah** [comment]
```
runc:
  Version:          0.3
```

that looks like an odd version of runc

What method did you use to install docker? Did you install from the docker package repository, or the ubuntu `docker.io` package?

**Comment by farso92** [comment]
i used repository 
`sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"`
By the way i tried to upgrade runc and now i have this version:
`runc version 1.0.0-rc9+dev
commit: 5e6369538477c62b0f3a112f49d65e222cda1614
spec: 1.0.1-dev
`
if i run again docker info no i have this:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc9+dev
  GitCommit:        5e6369538477c62b0f3a112f49d65e222cda1614
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Now if i run `docker run hello-world` the error is:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"apply apparmor profile: apparmor: config provided but apparmor not supported\"": unknown.
`

**Comment by pglombardo** [comment]
Just found this issue via Google and I have the same problem after a new docker-ce install on Ubuntu 19.10.  I have more recent runc.

`docker run hello-world` outputs:

```
docker: Error response from daemon: OCI runtime create failed: json: cannot unmarshal object into Go value of type []string: unknown.
ERRO[0000] error waiting for container: context canceled
FAIL: 125
```

Happens on local box and remotely from a Mac via via DOCKER_HOST env var.

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc2
  GitCommit:        4f21aea40d060d0171b1c94861f2f63f4a6029d0
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by pglombardo** [comment]
This doesn't help the original issue but I nuked the VM and created anew with Ubuntu 18.04 and all is good.

**Comment by cpuguy83** [comment]
@pglombardo Your error is not the same thing at all and looks like some incompatibility in the data passed to runc.

@farso92 For the original error, errors like this are typically configuration issues on the host. runc either got oom-killed, couldn't write something (e.g. to `/run`), or something of this nature.
Unfortunately these types of errors are not simple to debug (and as such difficult to report detailed information back to users), but I would start by making sure the system has plenty of memory available, that `/run` is not full (typically this is a tmpfs), and other such things.

For the 2nd error it looks like you are using a dockerd that is configured with apparmor support but the runc binary is not.

**Comment by farso92** [comment]
i fixed It...i made some changes but i think that the problem was apparmor...i m not sure but after removing that program everything goes well... thanks everybody

**Comment by ashish235** [comment]
@farso92 was it fixed? I am still having the same issue on Ubuntu 18.04. 

root@slave-node2:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:8e3114318a995a1ee497790535e7b88365222a21771ae7e53687ad76563e8e76
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/55fc63482321b66d14283d69b3f681f216b7500c6247bdf59cfb1569b39a81e0/log.json: no such file or directory): runc did not terminate sucessfully: unknown.
ERRO[0012] error waiting for container: context canceled
root@slave-node2:~# free -m
              total        used        free      shared  buff/cache   available
Mem:          11968        2389        6924           2        2654        9278
Swap:             0           0           0
root@slave-node2:~# touch test
root@slave-node2:~# docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by void-arch** [comment]
I am having the same problem. I am running aa VPS on Ubuntu 18.04.4 and cannot start more than 8 containers. When trying to start more project, no matter what, I get the same error like farso92 mentioned in the original post.
My `docker version` output:
`Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:      `

**Comment by thaJeztah** [comment]
@void-arch from the output of your `docker version`, I suspect you may be running either the "snap" package of docker, or a distro package of docker (as built/maintained by Ubuntu). I've seen various issues reported with those packages; are you able to reproduce the problem on the official packages? (https://docs.docker.com/engine/install/ubuntu/) ?

**Comment by void-arch** [comment]
Thanks for responding @thaJeztah 
It was neither a docker nor moby issue. The hosting provider used Virrtuoozo for virtualization and limited the number of processes for my VPS. That costed me a lot f merves...

In the meantime I switched to an other provider that uses KVM and everything works just fine!

**Comment by thaJeztah** [comment]
Good to hear!
