### ISSUE TITLE
Error with userns-remap and shared network: OCI runtime create failed / permission denied: unknown

### ISSUE THREAD

**Issue by chilikk** [moby/moby#42081]
**Description**

Running with userns-remap, starting a container with shared network fails with OCI runtime create failed / permission denied: unknown error.

**Steps to reproduce the issue:**
1. /usr/bin/dockerd --userns-remap=default &
2. docker run -d --name network alpine sleep infinity
3. docker run -d --net container:network alpine sleep infinity

**Describe the results you received:**

The second container does not start with the following error (started in reproduction step 3):
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:48: preparing rootfs caused: permission denied: unknown.

**Describe the results you expected:**

Both containers up and running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.7
 Git commit:        48d30b5b32e99c932b4ea3edca74353feddd83ff
 Built:             Thu Feb  4 04:42:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.7
  Git commit:       46229ca1d815cfd4b50eb377ac75ad8300e13a85
  Built:            Thu Feb  4 04:41:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: 
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.10.15-0-virt
 Operating System: Alpine Linux v3.13
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.948GiB
 Name: alpine313.localdomain
 ID: BU6M:3RNE:Z2TU:TD2Y:C756:TER3:JUPL:Y25X:N3B6:NNPV:KZS3:YPGE
 Docker Root Dir: /var/lib/docker/100000.100000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am reproducing this with a clean vagrant VM, so I'm starting with
vagrant init generic/alpine313
vagrant up
vagrant ssh
sudo su
apk add --no-cache shadow docker
mount -t cgroup cgroup /sys/fs/cgroup
touch /etc/subuid /etc/subgid

**Comment by Crypter** [comment]
I'm having a very, very similar error, however, I'm not able to consistently reproduce it.
It happens with v20.10.3 and v19.03.15
It doesn't happen with v20.10.2 and v19.03.14

Error line numbers a +/- there, I just don't remember if this one was from v19 or v20
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:47: preparing rootfs caused: permission denied: unknown.

**Comment by akana** [comment]
I have the same error on the latest version of Docker v20.10.5. Any workaround would be appreciated.

**Docker Info**
 ```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.5
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  userns
  cgroupns
 Kernel Version: 5.11.11-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.58GiB
 Name: arch
 ID: PUB4:TML3:FYDO:YFAE:RLFC:3563:GNLO:WGMK:UPOI:GYQ5:KIH5:CV4B
 Docker Root Dir: /var/lib/docker/231072.231072
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Support for cgroup v2 is experimental

```

**Comment by casdevs** [comment]
me too 
I use docker in docker with user namespacing enabled and am trying to start a docker-compose project with two services sharing the same network (```network_mode: "service:app"```), which gives me
```
ERROR: Cannot start service: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:48: preparing rootfs caused: permission denied: unknown
```

> I'm having a very, very similar error, however, I'm not able to consistently reproduce it.
> It happens with v20.10.3 and v19.03.15
> It doesn't happen with v20.10.2 and v19.03.14

Could it be that the fix for https://github.com/moby/moby/security/advisories/GHSA-7452-xqpj-6rpc is causing this bug since Docker v20.10.3?

**Comment by akana** [comment]
The problem was solved after I updated to v20.10.6

**Comment by casdevs** [comment]
> The problem was solved after I updated to v20.10.6

unfortunately, the issue still exists in docker v20.10.6 for me
