### ISSUE TITLE
Docker stop doesn't work,  the container state is still Running after docker stop, but shim process is reaped.

### ISSUE THREAD

**Issue by kkltcjk1** [moby/moby#43022]
**Description**
After execute docker stop, we can see the container is still Running from docker ps, but the shim process is reaped. From the log, we found after docker stop. dockerd received exec exit event and container exit event, then no other information. Form the stack, we found the exit event hang in CloseStreams method. So the container exit event will not be handled and the container state will not changed to Exited. This happened occasionally on our servers. We don't know what happend, but we have a way to reproduce it(Maybe same reason).

**Steps to reproduce the issue:**
This is one of the situations which can reproduce it, but maybe not the real reason
1. docker run -itd --name test ubunut:latest /bin/bash
2. docker exec test test.sh(test.sh will echo a long words in a while loop)
3. kill -19 $(pidof docker exec) (just to interrupt the outstream read)
4. docker stop test

**Describe the results you received:**
container state is Running from docker ps, and the shim process is reaped from ps -ef | grep shim.

**Describe the results you expected:**
container state is Exited, shim process is Exited.

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.15.7
 Git commit:        4c80d53
 Built:             Sat Nov 13 09:00:31 2021
 OS/Arch:           linux/arm64
 Experimental:      true

Server:
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.15.7
  Git commit:       1439754
  Built:            Tue Nov 16 12:54:40 2021
  OS/Arch:          linux/arm64
  Experimental:     true
```

**Comment by cpuguy83** [comment]
You are running a 2.5 yr old version of Docker.
Can you update to the latest release?
18.09 is not supported and has known issues such as this which are fixed in later releases.

**Comment by kkltcjk1** [comment]
> You are running a 2.5 yr old version of Docker. Can you update to the latest release? 18.09 is not supported and has known issues such as this which are fixed in later releases.

I tried 20.10.9 version, but still have this problem.

docker version:
```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by kkltcjk1** [comment]
> You are running a 2.5 yr old version of Docker. Can you update to the latest release? 18.09 is not supported and has known issues such as this which are fixed in later releases.

I install 20.10.9 version, test several times, and it produce only once. Could you kindly show me which issue or patch fix it? Actually I have a fix for it, but after check the code, I wonder how it is fixed.  ^-^

**Comment by kkltcjk1** [comment]
Unfortunately, this bug might not be fixed.
I build the master version, and find the this patch(https://github.com/moby/moby/commit/7fd23345c9ad9cc81616b635f6d6a56a1b9ab11a) fix part of it.

For now, the docker stop process is as below:
```
1. send sigterm signal from containerd
2. send sigkill signal from containerd
3. send sigkill signal directly
```
The patch(https://github.com/moby/moby/commit/7fd23345c9ad9cc81616b635f6d6a56a1b9ab11a) work in the second step, since the processEvent func can't handle exit event in time, so the containerd will return "no such container", and handleContainerExit func will be called to set the container state to "Exited".

So in the first step, if container exit a little slowly, in the second step, containered will not return "no such container" err, then the handleContainerExit will not be called. This bug will reproduce again.

So for docker stop command, we can reproduce as follow:
```
1. docker run -itd --name test ubunut:latest /bin/bash
2. docker exec test test.sh(test.sh will echo a long words in a while loop)
3. kill -19 $(pidof docker exec) (just to interrupt the outstream read)
4. kill -19 $(pidof container) (simulating container exit slowly, make sure the container not exit in the first step)
5. docker stop test
6. kill -9 $(pidof shim)
```
Then this bug will reproduce, shim process exit and container is Running from docker ps.

Since docker kill doesn't have the first step, so we can use docker kill to reproduce.
```
1. docker run -itd --name test ubunut:latest /bin/bash
2. docker exec test test.sh(test.sh will echo a long words in a while loop)
3. kill -19 $(pidof docker exec) (just to interrupt the outstream read)
4. docker kill test
```
Still reproduce...

**Comment by cpuguy83** [comment]
Can you take a stack trace from when your daemon is stuck?

You can get the stack trace by hitting `/debug/pprof/gorouintes?debug=2` (or maybe it's `goroutine` not `goroutines`, I can never remember).
Example with curl: `curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutines?debug=2 > stack.txt`

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
