### ISSUE TITLE
Latest version breaks DNS lookup for internal domains

### ISSUE THREAD

**Issue by DesignByOnyx** [moby/moby#44470]
### Description

The following Dockerfile works on 4.13.0 and 4.13.1, but not 4.14.0. The `customdomain` is an internal domain accessible only within our company network/vpn.

```
FROM alpine
RUN ping -c 1 customdomain
```

### Reproduce

Unfortunately I don't know how to tell you to reporduce from outside our network/vpn (which we cannot give you access). 

The following works on 4.13.1 but not 4.14.0:

```
echo -e "FROM alpine\nRUN ping -c 1 customdomain" >> Dockerfile
docker build --no-cache .
```

### Expected behavior

The above Dockerfile should still work. It has worked for years before the most recent update.

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.2)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.87GiB
 Name: docker-desktop
 ID: U264:2JXB:F6RQ:P7AJ:T255:PNZL:B3IW:INGA:YQE4:7OZP:3BMX:RDHG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info

This is currently breaking all of our builds. We have collectively downgraded to 4.13.1, so it's not a complete blocker - but we generally prefer to be on the latest and greatest version. Here is some additional information which might help:

- I'm running a vanilla docker-desktop install with all "default" settings.
- I'm on a Windows machine using the WSL backend. I get the same errors from powershell and ubuntu 18.04.5.
- My local `hosts` file contains the correct IP mapping for our custom domain
- I updated the docker daemon.json to include our internal DNS server: `{ "dns": ["192.168.x.x", "8.8.8.8"] }`.
- I have downgraded to 4.13.1 mutliple times, run the above command, and verified that it worked. I then upgraded to 4.14.0 without making any changes and have experienced the issues. Another teammate has done the same and has verified the issue.
- In the course of troubleshooting, we have gone so far as to reboot our physical machines after every change... to no avail.
- Thanks for providing such a great tool for the community. I hope we can help you fix a bug.

**Comment by thaJeztah** [comment]
Looking at the diff between docker engine v20.10.20 (used in Docker Desktop v4.13.1) and v20.10.21 (used in Docker Desktop v4.14), I don't see any differences related to networking; https://github.com/moby/moby/compare/v20.10.20...v20.10.21

I suspect this may be an issue in Docker Desktop; I see there's a fix related to DNS resolution in the upcoming v4.14.1 release (release notes are in draft, but it's not released yet); https://github.com/docker/docs/pull/16170

**Comment by thaJeztah** [comment]
I'm not sure if the update above will fix the issue; but perhaps you could let us know once it's available? I'll also let the Desktop team know, in case it's a separate issue.

**Comment by ebriney** [comment]
A fix has been released in Docker Desktop 4.14.1. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by thaJeztah** [comment]
Thanks @ebriney !

@DesignByOnyx I'll go ahead and close this ticket for housekeeping, but let us know if the update fixes your issue; feel free to comment after I closed 👍

**Comment by DesignByOnyx** [comment]
Thanks for the quick update. The latest 4.14.1 did not fix our particular issue, however one of our SREs was able to help fix our issue by adding our company domain to the `dns-search` daemon config. So the following is what fixed it for us:

```
{
  "dns": ["192.168.x.x", "1.1.1.1"],
  "dns-config": ["ourcompany.com"]
}
```

Prior to 4.14.X, docker seemed to inherit these settings from our host machines, which are configured as follows:

```
$ cat /etc/resolv.conf
nameserver 1.1.1.1
nameserver 192.168.x.x 

$ cat /etc/hosts
192.168.x.y   customdomain
192.168.x.y   customdomain.ourcompany.com
```

**Comment by djs55** [comment]
@DesignByOnyx thanks for the update. If you have time could you reproduce the problem (remove the `dns-search`, restart Docker and try a `ping`) and then upload a diagnostic? The logs will include those from the DNS server inside Desktop. You can upload a diagnostic from the UI (whale menu -> troubleshoot) or from [the command-line](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal)
```
 /Applications/Docker.app/Contents/MacOS/com.docker.diagnose -upload
```
If you quote the diagnostics ID here I can take a look at the logs and investigate further.

**Comment by DesignByOnyx** [comment]
@djs55 - thanks so much for looking into this. I removed both the `dns` and `dns-search` entries from the daemon config because neither were needed prior to 4.14.x. Running the diagnotstic was kind of strange in that I couldn't tell it when to start or stop.... but after some time it eventually gave me a diagnostic ID:

`6B161433-70B8-41AB-A428-47C06480040E/20221121184255`

And to be clear, I ran the following docker command multiple times using the following dockerfile, all while connected to my company VPN. I verified that I could ping our custom domain from my host machine. I've redacted part of our custom domain, but the logs should hopefully contain what you need:

```bash
docker build --no-cache .
```

```dockerfile
FROM alpine
RUN ping -c 1 <REDACTED>svr5
```

**Comment by DesignByOnyx** [comment]
I just added back the settings from `dsn` and `dns-search`,  I ran the above docker build many times in a row, and I experienced several intermittent DNS lookup failures. It mostly works, but the intermittent failures are a bit troublesome. I feel like my internet is pretty stable, and I was still able to ping from my host machine whenever the failures were happening. Here's the diagnostic ID for this most recent run:

`6B161433-70B8-41AB-A428-47C06480040E/20221121190615`

**Comment by henryzhao95** [comment]
Hi, a few colleagues including myself are also getting a similar issue resolving internal DNS from Docker Desktop v4.14.0, v4.14.1 and v4.15.0 on Windows (v4.13.1 is fine):

`docker run -it --rm tutum/dnsutils nslookup foo.company.org` (or any internal domain) is now taking over 10 seconds to resolve the A record.

Our host /etc/hosts file doesn't have or need any entries for *.company.org.
The /etc/hosts and /etc/resolv.conf files viewed within busybox for v4.13.1 and v4.14.0 are identical.
