### ISSUE TITLE
Encrypted overlay network between nodes on 29.1.3 and 28.x versions doesn't pass traffic

### ISSUE THREAD

**Issue by smin** [moby/moby#51798]
### Description

With a node on 29.1.3 and another on 28.5.2 (or lower) it appears that encrypted overlay networks stop working i.e. no traffic can be sent between containers on the overlay network (DNS resolution of containers on the other node still works). If both are 29.1.3 or both are 28.5.2, traffic flows.

### Reproduce

On node1
`docker network create --driver overlay --attachable --opt encrypted encnet`
`docker run -d --name test1 --network encnet alpine sleep 1d`

On node2
```
docker run --rm --name test2 --network encnet alpine sh -c "apk add -q iputils && ping -c3 test1"
PING test1 (10.0.2.2) 56(84) bytes of data.

--- test1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2066ms
```
### Expected behavior

```
PING test1 (10.0.2.2) 56(84) bytes of data.
64 bytes from test1.encnet (10.0.2.2): icmp_seq=1 ttl=64 time=0.893 ms
64 bytes from test1.encnet (10.0.2.2): icmp_seq=2 ttl=64 time=1.94 ms
64 bytes from test1.encnet (10.0.2.2): icmp_seq=3 ttl=64 time=0.796 ms
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.5.2
 API version:       1.51
 Go version:        go1.25.3
 Git commit:        ecc6942
 Built:             Wed Nov  5 14:43:11 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.5.2
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.25.3
  Git commit:       89c5e8f
  Built:            Wed Nov  5 14:43:11 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.28
  GitCommit:        b98a3aace656320842a23f4a392a33f46af97866
 runc:
  Version:          1.3.0
  GitCommit:        v1.3.0-0-g4ca628d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.5.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /root/.docker/cli-plugins/docker-sbom

Server:
 Containers: 37
  Running: 18
  Paused: 0
  Stopped: 19
 Images: 30
 Server Version: 28.5.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: active
  NodeID: 8y1hquegv1kbinh82tijyteh1
  Is Manager: true
  ClusterID: zfdcacibg74wivs2j429pn45l
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.15.13.189
  Manager Addresses:
   10.15.13.189:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b98a3aace656320842a23f4a392a33f46af97866
 runc version: v1.3.0-0-g4ca628d1
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1044-aws
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.36GiB
 Name: testhost
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Grateful for any information or workaround to make upgrades to 29 easier.

**Comment by thaJeztah** [comment]
Not sure if related, but there was another report about encrypted overlay with v29.x here;

- https://github.com/moby/moby/issues/51672

That one got closed as (per that reporter) it was resolved in v29.1.3 ? 🤔 


cc @corhere any ideas?

**Comment by smin** [comment]
Thanks, yes we were hopeful when we saw #51672 closed that this would be resolved as well but it's still an issue

**Comment by smin** [comment]
Hello, just tried 29.1.4 and 29.1.5 for completeness and they show the same sort of problem when paired with 28.5.2.

It would be great to get confirmation on whether this is something that mixing major releases can cause and if there's an expectation of compatibility or not. As above, a temporary workaround would be fine, we just need a process to get our estate upgraded.

While I'm here, is the 28.x branch going to be supported until a particular point i.e. is there any more info than here?
https://github.com/moby/moby/blob/master/project/BRANCHES-AND-TAGS.md#docker-engine-branches

**Comment by corhere** [comment]
Confirmed. The different engine versions disagree on the Security Parameter Index values so the recipient can't locate the decryption key to use.
https://github.com/moby/moby/blob/4e0413091127027fc88b30bc48909b616bf7b828/libnetwork/drivers/overlay/encryption.go#L176
https://github.com/moby/moby/blob/9c623849a9e6ce2add344fa1453c454dce75340f/daemon/libnetwork/drivers/overlay/encryption.go#L138

Sixteen-byte wide net.IP values strike again! The 28.x branch is hashing IPv4-mapped IPv6 addresses while 29.x is hashing four-byte IPv4 values, yielding different results. (Ironically, this means using an IPv6 underlay network would work around this issue.)

Moby v25.0.13-v25.0.14, v28.2.2 and v29.0.0-v29.2.0 can pass encrypted overlay traffic with each other but not with other daemon versions. How do we move forward with a fix? If we were to apply the obvious fix, the outcome would be a (for example) v29.3.0 which could pass encrypted overlay traffic with v28.5.2 but not with v29.0.0-v29.2.0. ~Calculating and programming both SPIs into the kernel concurrently would allow v29.3.0 to pass traffic with all previous versions, but doubling the number of encryption state entries we program into the kernel is not the greatest outcome either. It might be time to add a "compatibility level" sort of field to overlay_peer_table entries so engines can signal that they are not impacted by the bug and peers can elide the double-state workaround.~

**Comment by nowheresly** [comment]
Trying 29.x  hashing first. If it fails, trying 28.x hashing then. If it fails again, give up ?

Behavior activated through a compatibility mode that migrates all 28.x hashing to 29.x hashing.
